### ISSUE TITLE
`drizzle-kit introspect:pg` generates invalid result

### ISSUE THREAD

**Issue by jbl428** [drizzle-team/drizzle-kit-mirror#102]
drizzle-kit: v0.19.2
drizzle-orm: v0.27.0

Here is postgresql table

```sql
CREATE TABLE users
(
    id       SERIAL PRIMARY KEY,
    status_a varchar(255) DEFAULT 'ACTIVE':: CHARACTER VARYING NOT NULL,
    status_b varchar      DEFAULT 'ACTIVE':: CHARACTER VARYING NOT NULL
);

```

After running `drizzle-kit introspect:pg`

```ts
import { pgTable, pgEnum, pgSchema, AnyPgColumn, serial, varchar } from "drizzle-orm/pg-core"


import { sql } from "drizzle-orm"

export const users = pgTable("users", {
	id: serial("id").primaryKey().notNull(),
	statusA: varchar("status_a", { length: 255 }).default('ACTIVE'::character varying).notNull(), // invalid
	statusB: varchar("status_b").default('ACTIVE').notNull(), // valid
});
```

It generates `::character varying` in code if length property of varchar is specified

**Comment by CareTiger** [comment]
i got the same error on one of my tables and a supabase generated table

**Comment by albertovasquez** [comment]
I'm still getting this issue.

**Comment by MoaathAlattas** [comment]
I keep getting this behaviour as well, example:
<img width="983" alt="Screenshot 2023-09-19 at 6 03 40 PM" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/18528024/8bd073b2-be9f-4a1c-b4f3-2bdbb0e7666f">

**Comment by qaynam** [comment]
any update?

**Comment by L-Mario564** [comment]
This should be fixed in latest.
