### ISSUE TITLE
drizzle-kit push:mysql needs connection strings to support `sslaccept` to connect to PlanetScale

### ISSUE THREAD

**Issue by jimmywalsh** [drizzle-team/drizzle-kit-mirror#103]
## Context
- I'm trying to push schema changes to PlanetScale using `drizzle-kit push:mysql` using the connection string PlanetScale generated for me. 
- _*I'll note that the connection string from PlanetScale ends with `?sslaccept=strict`*_

My `drizzle.config.ts` looks like this:
```
import type { Config } from "drizzle-kit";
import 'dotenv/config'

export default {
  schema: './db/schemas/**',
  driver: 'mysql2',
  dbCredentials: {
    connectionString: process.env.DATABASE_URL as string
  }
} satisfies Config;
```

## Problem
- When using the `mysql2` driver, the driver will will ignore this ssl query parameter. 
- This is a problem because SSL is required by PlanetScale for proper connection.
- I've listed the output from the npm script below

## Output
```sh
Ignoring invalid configuration option passed to Connection: sslaccept. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
~/my-project/node_modules/.pnpm/drizzle-kit@0.19.2/node_modules/drizzle-kit/index.cjs:34259
      const createConnectionErr = new Error();
                                  ^

Error: unknown error: Code: UNAVAILABLE
server does not allow insecure connections, client must use SSL/TLS

    at createConnection2 (~/my-project/node_modules/.pnpm/drizzle-kit@0.19.2/node_modules/drizzle-kit/index.cjs:34259:35)
    at connectToMySQL (~/my-project/node_modules/.pnpm/drizzle-kit@0.19.2/node_modules/drizzle-kit/index.cjs:36340:60)
    at Command.<anonymous> (~/my-project/node_modules/.pnpm/drizzle-kit@0.19.2/node_modules/drizzle-kit/index.cjs:51785:28) {
  code: 'ER_UNKNOWN_ERROR',
  errno: 1105,
  sqlState: 'HY000'
}

Node.js v18.12.1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by patrykmaron** [comment]
Any workaround for this?

**Comment by HegarGarcia** [comment]
<img width="604" alt="image" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/10493888/fd6d2893-ea12-4d0d-b2f0-5bfcbfbce62c">
I'm adding `{"rejectUnauthorized":true}` on the `ssl` param. It's not a good solution but makes it work

**Comment by jimmywalsh** [comment]
@HegarGarcia thanks for following up, and this solution works great! 

@patrykmaron I ended up using the same solution above ^. The issue was that I was copying the connection string from PlanetScale based on selecting `Prisma` in the env dropdown. Prisma's mysql adapter expects the `sslaccept` query param. 

Alternatively, if you select `Node.js` in PlanetScale's dropdown it will prompt you to use the `ssl` query param rather than `sslaccept`. 

The following works great:
`<your-prisma-db-url>?ssl={"rejectUnauthorized":true}`.

I think it would be a good idea for the Drizzle team to include in their documentation that if you're working with PlanetScale DB you should be using the Nodejs connection string environment variable specifically.
