### ISSUE TITLE
[Request] Check DB before trying to truncate table

### ISSUE THREAD

**Issue by TiltedToast** [drizzle-team/drizzle-kit-mirror#105]
I was wondering if it was possible for drizzle-kit to query the database when trying to push a new schema to check if the data inside is maybe already compatible.

As it is right now, drizzle-kit will just give you the option to wipe the whole table when you're for example lowering a varchar's length and try to push that schema.

It doesn't matter if all the data inside the database already conforms to the new schema, it'll still try to truncate the table. 

I'm sure doing this for every changed schema property would result in a lot of extra work, especially when there are multiple different databases that need to be supported. 

Admittedly the way it works now isn't the end of the world since you can just dump the whole table beforehand and fill it up again but having drizzle-kit handle this automatically would still definitely be a nice quality of life improvement.

**Comment by AndriiSherman** [comment]
We will have more handlers for that. The reason is to release the push feature already, so you can try it out and make it work for most cases. The next steps will be to improve the behavior and make Drizzle-Kit 'smarter' for such cases.

**Comment by L-Mario564** [comment]
Kit has improved a lot since this issue was created, so I'll be closing this issue. If you got any specific ideas or feature requests you want to make for Kit, you can file a new issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues.
