### ISSUE TITLE
`generate:sqlite` generates invalid migration statement for integer field that use auto-increment

### ISSUE THREAD

**Issue by WPitak** [drizzle-team/drizzle-kit-mirror#106]
## Context
* drizzle-kit: v0.19.2
* drizzle-orm: v0.27.0
* pnpm: v8.6.3

## Setup
* schema.ts
```ts
import {
  sqliteTable,
  integer,
  text,
  uniqueIndex,
  primaryKey,
  foreignKey,
} from "drizzle-orm/sqlite-core";

export const users = sqliteTable(
  "users",
  {
    id: integer("id", { mode: "number" }).primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
  },
  (table) => ({
    uniqueName: uniqueIndex("uniqueNameIdx").on(table.name),
  })
);

export const tags = sqliteTable(
  "tags",
  {
    userId: integer("user_id", { mode: "number" }).notNull(),
    tag: text("tag").notNull(),
  },
  (table) => ({
    pk: primaryKey(table.userId, table.tag),
    userIdFk: foreignKey(() => ({
      columns: [table.userId],
      foreignColumns: [users.id],
    })),
  })
);
```

* run command `pnpm exec drizzle-kit generate:sqlite --schema=schema.ts`

## Issue
The generated migration file contains the following
```sql
CREATE TABLE `tags` (
	`user_id` integer NOT NULL,
	`tag` text NOT NULL,
	PRIMARY KEY(`user_id`, `tag`),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` integer AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`name` text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `uniqueNameIdx` ON `users` (`name`);
```

After preparing the database with generated script directly or with `drizzle-kit push:sqlite`, running code inserting data or directly executing insert statement into `users` table with only `users.name` result in error `NOT NULL constraint failed: users.id`.

According to [SQLite documentation](https://www.sqlite.org/lang_createtable.html), the line declaring `users.id` should probably be
```sql
`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
```
which is also what is currently shown in `drizzle-kit` [documentation](https://orm.drizzle.team/docs/column-types/sqlite#integer).

Preparing database with script modified with above fragment seems to fix the issue.

**Comment by AndriiSherman** [comment]
Should be fixed in `drizzle-kit@0.19.5`, thanks!
