### ISSUE TITLE
`push:sqlite` does not recognize `--schema` option

### ISSUE THREAD

**Issue by WPitak** [drizzle-team/drizzle-kit-mirror#107]
## Context
* drizzle-kit: v0.19.2
* drizzle-orm: v0.27.0
* pnpm: v8.6.3

## Setup
* run `pnpm exec drizzle-kit push:sqlite --schema=./schema.ts --driver=better-sqlite --url=./test.db`

## Issue
Running the command result in an error `error: unknown option '--schema=./schema.ts'`

Current `drizzle-kit` [documentation](https://orm.drizzle.team/kit-docs/commands#prototype--push) list param `schema`  as required, but result of running the command with `--help` **does not** list `--schema` as an option
```sh
$ pnpm exec drizzle-kit push:sqlite --help
Usage: index push:sqlite [options]

Options:
  --config <config>                      Path to a config.ts file, drizzle.config.ts
                                         by default
  --tableFilters                         Table name filters
  --connectionString <connectionString>  SQLite connection string
  --driver <driver>                      SQLite database path
  --url <url>                            SQLite database path
  --auth-token <authToken>               SQLite database path
  --verbose                              Print all statements for each push
  --strict                               Always ask for confirmation
  -h, --help
```

`schema` can still be specified and perform `push:sqlite` successfully through configuration file.

**Comment by AndriiSherman** [comment]
Fixed in `drizzle-kit@0.19.5`, thanks!
