### ISSUE TITLE
Support for data types with parameters added by extensions (e.g. pgvector)

### ISSUE THREAD

**Issue by avanderbergh** [drizzle-team/drizzle-kit-mirror#115]
I would like to use the `vector` data type provided by [pgvector](https://github.com/pgvector/pgvector)

The type can be used with or without a parameter to specify the number of dimensions.

The issue is that the generated SQL puts `""` around the type so its seen as a literal.

I've found the following function in the compiled source:
```javascript
var isPgNativeType = (it) => {
  if (pgNativeTypes.has(it))
    return true;
  const toCheck = it.replace(/ /g, "");
  return toCheck.startsWith("varchar(") || toCheck.startsWith("char(") || toCheck.startsWith("numeric(") || toCheck.startsWith("timestamp(") || toCheck.startsWith("intervalyear(") || toCheck.startsWith("intervalmonth(") || toCheck.startsWith("intervalday(") || toCheck.startsWith("intervalhour(") || toCheck.startsWith("intervalminute(") || toCheck.startsWith("intervalsecond(") || toCheck.startsWith("intervalyeartomonth(") || toCheck.startsWith("intervaldaytohour(") || toCheck.startsWith("intervaldaytominute(") || toCheck.startsWith("intervaldaytosecond(") || toCheck.startsWith("intervalhourtominute(") || toCheck.startsWith("intervalhourtosecond(") || toCheck.startsWith("intervalminutetosecond(") || /^(\w+)(\[\d*])+$/.test(it);
};
```

This explains while built-in types don't have the `"`.

How could we use new types introduced by extensions that need to take parameters?

The maintainer of pgvector has already created an [implementation](https://github.com/pgvector/pgvector-node#drizzle-orm) for drizzle, but it seems to be blocked by this issue...

**Comment by AndriiSherman** [comment]
Already know how to fix 🫡

**Comment by gvkhna** [comment]
Bumping, any updates on this?

**Comment by AndriiSherman** [comment]
It's in my backlog in high priority

**Comment by zigenis** [comment]
Just dropping in to voice my support for this as well. Having vector compatibility with drizzle-kit would be wonderful!

**Comment by avanderbergh** [comment]
By the way, I'm using a workaround until this is fixed.

Just replace `"vector()"` with `vector()` in the generated SQL migrations before migrating.

I was quite optimistic that we'll get these issues fixed in a reasonable time when I saw [this post](https://github.com/drizzle-team/drizzle-orm/issues/580#issuecomment-1547314200) saying `drizzle-kit` would open open-sourced "very soon".

This was 4 months ago...

I'm starting to get worried... 😰

**Comment by zigenis** [comment]
> By the way, I'm using a workaround until this is fixed.
> 
> Just replace `"vector()"` with `vector()` in the generated SQL migrations before migrating.
> 
> I was quite optimistic that we'll get these issues fixed in a reasonable time when I saw [this post](https://github.com/drizzle-team/drizzle-orm/issues/580#issuecomment-1547314200) saying `drizzle-kit` would open open-sourced "very soon".
> 
> This was 4 months ago...
> 
> I'm starting to get worried... 😰

@avanderbergh 
I ended up doing something similar. Introspecting my existing Postgres database resulted in a schema that contained an "unknown()" function in place of the vector datatype. Swapped it out and it seems to be fine. You're saying that migrations work after that?

**Comment by avanderbergh** [comment]
> > By the way, I'm using a workaround until this is fixed.
> > 
> > Just replace `"vector()"` with `vector()` in the generated SQL migrations before migrating.
> > 
> > I was quite optimistic that we'll get these issues fixed in a reasonable time when I saw [this post](https://github.com/drizzle-team/drizzle-orm/issues/580#issuecomment-1547314200) saying `drizzle-kit` would open open-sourced "very soon".
> > 
> > This was 4 months ago...
> > 
> > I'm starting to get worried... 😰
> 
> @avanderbergh 
> I ended up doing something similar. Introspecting my existing Postgres database resulted in a schema that contained an "unknown()" function in place of the vector datatype. Swapped it out and it seems to be fine. You're saying that migrations work after that?

Yes, I had no issue with running a migration after editing the generated .sql files. 

It looks like the checksums stored in the migrations table are for SQL files as they are when running the migration.

**Comment by deansher** [comment]
Any progress on this? Also, any update on opensourcing drizzle kit?

**Comment by L-Mario564** [comment]
Vector types are now officially supported in ORM and Kit: https://orm.drizzle.team/docs/extensions/pg#pg_vector.
