### ISSUE TITLE
Nix package manager support

### ISSUE THREAD

**Issue by StrayArrow4** [drizzle-team/drizzle-kit-mirror#121]
I wish there were support for the Nix package manager, and, by extension NixOS. Prisma has support natively, and Drizzle's lack of it is causing me to consider using Prisma instead despite loving the project.

**Comment by L-Mario564** [comment]
I'm not familiar with the Nix package manager but Drizzle is just JS/TS code unlike Prisma which leverages Rust binaries for migrations and queries.
