### ISSUE TITLE
`push:sqlite` after adding a nullable reference truncated the table

### ISSUE THREAD

**Issue by arjunkomath** [drizzle-team/drizzle-kit-mirror#122]
I added a nullable reference to a table and after running `push:sqlite` the table was truncated without any warning :(
Fortunately this was not a production DB, but if this happened in prod it would have been a disaster.

This is the schema change I made:

```ts
export const document = sqliteTable("Document", {
  id: integer("id", { mode: "number" }).primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  markdownContent: text("markdownContent").notNull(),
  status: text("status").notNull(),
  createdAt: integer("createdAt", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updatedAt", { mode: "timestamp" }).notNull(),
  projectId: integer("projectId")
    .notNull()
    .references(() => project.id, { onDelete: "cascade", onUpdate: "cascade" }),

// Added this relation
  folderId: integer("folderId").references(() => documentFolder.id, {
    onDelete: "cascade",
    onUpdate: "cascade",
  }),

  createdByUser: text("createdByUser")
    .notNull()
    .references(() => user.id, { onDelete: "cascade", onUpdate: "cascade" }),
});
```

After running `push:sqlite`, I got this error:
```
> drizzle-kit push:sqlite

No config path provided, using default 'drizzle.config.ts'
Reading config file '/Users/arjunkomath/Developer/manage-v2/drizzle.config.ts'
drizzle-kit: v0.19.5
drizzle-orm: v0.27.2

TypeError: Cannot read properties of undefined (reading 'columns')
    at _moveDataStatements (/Users/arjunkomath/Developer/manage-v2/node_modules/drizzle-kit/index.cjs:52262:61)
    at logSuggestionsAndReturn2 (/Users/arjunkomath/Developer/manage-v2/node_modules/drizzle-kit/index.cjs:52462:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (/Users/arjunkomath/Developer/manage-v2/node_modules/drizzle-kit/index.cjs:52740:11)
```

I opened drizzle studio and all data in document table is gone. I'm not sure what happened, is there a way to do a dry-run and print the changes before actually applying them? This was a scary experience.

**Comment by arjunkomath** [comment]
> It should not truncate any tables without your approval. Such actions were covered. I'll check this one.

I understand, I've seen the CLI warning before making destructive changes, also prompting for changes when there is renamed columns etc, but in this specific instance there were no warnings. After running the migration, I checked studio first, the table was empty. I had a dev instance running locally, I refreshed the page to double check and as expected data was gone.

Here is the screenshot of running the command, as you can see there are no warnings.

<img width="888" alt="image" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/2555067/7a5360fe-ce39-4e2b-926c-63a45535e46f">


------

> I would also suggest never using push on a production database. Push is only suitable for local development, especially to avoid such or similar cases.

You're 💯  right, I don't think I'll run `push` on production anymore. I've used Prisma in the past and have been running migrations on Production using it, but I realised it too dangerous.

**Comment by arjunkomath** [comment]
@AndriiSherman I think I found the issue, it didn't truncate the table, but it renamed the table to `__old_push_Document`, didn't finish the whole migration because of the error, and unfortunately messed up the DB.

<img width="370" alt="image" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/2555067/5108c97c-7bb5-4d63-ac6c-4700246f4b80">

**Comment by jakeleventhal** [comment]
@AndriiSherman not sure if i should open a new issue, but dry run would be a very useful feature

use case: i want to know in CI if i can push a change without it causing loss of data

context: https://www.youtube.com/watch?v=jeWrbAiA1D0

**Comment by arjunkomath** [comment]
@jakeleventhal  You can set `verbose` and `strict` as true in Drizzle config, the migration queries will be logged to the console and you will have to explicitly permit the queries to be run. Not as great as dry-run, but its an additional layer of caution.

**Comment by jakeleventhal** [comment]
@arjunkomath my use case im looking to solve is automation in CI and i cant seem to pipe in a way to select "no" always. im just trying to fail CI if you try to update the schema in a way that leads to data loss

**Comment by L-Mario564** [comment]
Closing this in favor of other related issues over on the [main repo](https://github.com/drizzle-team/drizzle-orm).
