### ISSUE TITLE
Add ability to name migrations

### ISSUE THREAD

**Issue by RIP21** [drizzle-team/drizzle-kit-mirror#126]
It would be nice to pass `--name` CLI parameter, to get the migration file named manually.

E.g. `drizzle-kit generate:mysql --name="Add user table"` > generates `add-user-table.sql`
Or  `drizzle-kit generate:mysql --name=add-users-table` > generates `add-user-table.sql`

Generated names are all cool, but having sql files named in a meaningful way would be nice. 

Now I have to go and rename them manually.

**Comment by matiasmarcodelpont** [comment]
I'm loving Drizzle so far, but I'm surprised this basic feature isn't implemented

**Comment by L-Mario564** [comment]
This is available in newer versions of Kit: https://orm.drizzle.team/docs/drizzle-kit-generate#custom-migration-file-name.
