### ISSUE TITLE
Foreign key length

### ISSUE THREAD

**Issue by paul-uz** [drizzle-team/drizzle-kit-mirror#128]
With succinct table and column names, the foreign key constraint names are sometimes too long, more than 64 characters, which is the limit in mysql.

**Comment by AndriiSherman** [comment]
Known issue, working on it next

**Comment by JonaAnders** [comment]
My fix for now is generating the migration and then going into the files and renaming the keys. This is nessecairy for each migration, as migrations rename the keys.

**Comment by troykollar** [comment]
Any update on this issue?

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3244.
