### ISSUE TITLE
drizzle studio rearrange tabs through dragging

### ISSUE THREAD

**Issue by deadcoder0904** [drizzle-team/drizzle-kit-mirror#129]
i like to keep them in order of tables so i can quickly find them.

but right now the only way to do it is close all tabs & re-open them in order.

a drag & drop of tabs would be really useful. seems like a basic feature.

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3241.
