### ISSUE TITLE
Forcing a schema push

### ISSUE THREAD

**Issue by penberg** [drizzle-team/drizzle-kit-mirror#132]
It's possible to get a database in a bad state so that `push` stops working. It would be great to have an option to force push a schema change so that you don't have to manually do that:

```console
drizzle-kit push:sqlite --force
```

The command should probably print out a warning telling the user that this is a destructive operation.

**Comment by nasso** [comment]
any updates? 😅

**Comment by harunalrd** [comment]
any updates? (

**Comment by harunalrd** [comment]
any updates (2)

**Comment by edamazzio** [comment]
We really need a way to run drizzle-kit commands in a non-interactive way for CI/CD

**Comment by pencilcheck** [comment]
My solution right now is to run drizzle-kit migrate to generate the SQL files for migration, and manually run it on psql.
It is weird because if I can do this, why can't drizzle-kit push work? it just hangs there.

**Comment by byteballet** [comment]
> We really need a way to run drizzle-kit commands in a non-interactive way for CI/CD

It is really necessary, why doesn't drizzle provide a non-interactive command?
Any other way?

**Comment by ChoaibMouhrach** [comment]
Speedy fix:

Within your drizzle.config.ts file, either eliminate the strict key or set it to false, and the functionality will operate as intended.

Drawbacks:
Executing the push command will proceed without requiring your permission.

Drizzle should look into this, we need a proper solution.

**Comment by bchoii** [comment]
> Within your drizzle.config.ts file, either eliminate the strict key or set it to false, and the functionality will operate as intended.

Drizzle will ask for confirmation if the change is destructive.

**Comment by migsdeving** [comment]
Would love an update on this, I keep getting stuck here

**Comment by adriangalilea** [comment]
Bump.

Very annoying having to nuke my db every so often on dev.

**Comment by agcty** [comment]
would also love a force push command

**Comment by trykers** [comment]
Any updates? We really need this feature.

**Comment by devnarkha** [comment]
I used the migrate() command by creating a migrate.js file and used it to push the schema in my ci/cd pipeline.
That does not cause any CLI prompts. But make sure you know what changes you're doing to the DB.

I use Drizzle kit for local schema changes, as it's nice and it warns me of any wrong changes. 
Refer Point-4
https://orm.drizzle.team/docs/migrations

**Comment by darylteo** [comment]
I would use this to teardown / reset the database for e2e tests.

**Comment by vasyaqwe** [comment]
really need this

**Comment by mhosnyessa** [comment]
needed!!

**Comment by tkandr** [comment]
[drizzle-kit push](https://orm.drizzle.team/kit-docs/overview#prototyping-with-db-push) is more for local prototyping, not for a production run. There is a `migrator` for migrations.

I have a `migrate.ts` file:
```
import 'dotenv/config';

import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate as migratePgJs } from 'drizzle-orm/postgres-js/migrator';
import { join } from 'node:path';
import postgres from 'postgres';

import * as schema from './database/drizzle/schema';
import { pgConfigObj } from './config';

const client = postgres(pgConfigObj.connectionString, { max: 1 });

const migrate = async () => {
  await migratePgJs(drizzle(client, { schema }), {
    migrationsFolder: join(__dirname, '/database/drizzle/migrations'),
  });

  await client.end();
};

migrate();
```

Then I just run `ts-node src/migrate.ts` in my pipeline

**Comment by nasso** [comment]
> There is a migrator for migrations.

the whole point of platforms like planetscale is that you do not do migrations, you just push your schema and let the platform figure out the rest

this is precisely the reason why we need a proper way to run `drizzle-kit push` in non-interactive environments like CI

**Comment by Thinkscape** [comment]
This is breaking builds! 
It's temperamental depending on what drizzle decides to update.

Given there are still lots of bugs around schema diffing, in our case it keeps removing and re-adding the same indexes over and over, and it can't complete in CI.

**Comment by jaydenrasmussen** [comment]
Bumping this. It's breaking CI for my team using Planetscale as well.

**Comment by alexandergirardet** [comment]
Really needed

**Comment by MrBarracuda** [comment]
Bumping this

**Comment by joepetrillo** [comment]
This should exist

**Comment by AndriiSherman** [comment]
It is this one?
https://orm.drizzle.team/docs/drizzle-kit-push#extended-list-of-configurations

**Comment by migsdeving** [comment]
> It is this one? https://orm.drizzle.team/docs/drizzle-kit-push#extended-list-of-configurations
Yes this exists right now. I think this issue can be closed

**Comment by Thinkscape** [comment]
Sigh ... sadly the implementation only works half way :(
Continuing as #608
