### ISSUE TITLE
Suggestion : new cli command : drizzle-kit migrate

### ISSUE THREAD

**Issue by anshour** [drizzle-team/drizzle-kit-mirror#134]
I want to run the migrations file that previously generated by command `drizzle-kit generate:sqlite `. i know i can create a js or ts file to do the migration. but i think it will be more comfortable if there is a command to 'migrate' the generated migration file (like laravel have, php artisan migrate)

**Comment by pedrovrima** [comment]
I endorse this idea!

**Comment by olup** [comment]
I am amazed to discover that there is no such command and that a ts script is needed.

**Comment by L-Mario564** [comment]
A `migrate` command is now available in newer versions of Kit.
