### ISSUE TITLE
[BUG]: Data loss warning when changing varchar size

### ISSUE THREAD

**Issue by MendyLanda** [drizzle-team/drizzle-kit-mirror#139]
Changing a VARCHAR size shouldn't cause the table to truncate (At least in `pg` and `mysq`l) but:
 ```
Warning  Found data-loss statements:
· You're about to change name column type from varchar(191) to varchar(255) with 2 items
· You're about to change logo_url column type from varchar(191) to varchar(255) with 2 items
· You're about to change ad_city column type from varchar(191) to varchar(255) with 2 items
· You're about to change ad_first_row column type from varchar(191) to varchar(255) with 2 items
...

THIS ACTION WILL CAUSE DATA LOSS AND CANNOT BE REVERTED
```
From `MySql` [specification](https://dev.mysql.com/doc/refman/8.0/en/alter-table.html) under operation that support the `INPLACE` algorithm:
>As of MySQL 8.0.14, changing a column character set, when these conditions apply:
> - The column data type is [CHAR](https://dev.mysql.com/doc/refman/8.0/en/char.html), [VARCHAR](https://dev.mysql.com/doc/refman/8.0/en/char.html), a [TEXT](https://dev.mysql.com/doc/refman/8.0/en/blob.html) type, or [ENUM](https://dev.mysql.com/doc/refman/8.0/en/enum.html).
> - The character set change is from utf8mb3 to utf8mb4, or any character set to binary.
> - There is no index on the column.

Context:
drizzle-kit: `v0.19.12`
db: `planetscale`

**Comment by pyrexfm** [comment]
+1
Same for adding new enum values

**Comment by stabildev** [comment]
+1
Same for switching from `text` to `varchar`

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/2047 over on the main repo.
