### ISSUE TITLE
Feature request:  option to match generated column name case to db column name

### ISSUE THREAD

**Issue by robkallen** [drizzle-team/drizzle-kit-mirror#14]
**Feature Request:**

I posted this in your Discord and was asked to create an issue.  It would be nice if you included an option in the `introspect` command to have the column  field names match the case of the corresponding column name from the database. For example, for this column, `userId: bigint("user_id", { mode: "number" }),`, instead of the column field name being generated as `userId` it would match the table column name of `user_id`.  Thanks!

**Comment by hellnation** [comment]
+1

I have been trying to create an NextAuth adapter for Drizzle, but spent the last couple of hours trying to work out why it wasn't working. I eventually figured out that one object that NextAuth is trying to persist has some keys with underscores, which DrizzleKit is renaming so the keys don't line up.

The error and stack trace you get from Drizzle when this happens is very not helpful.

Note that the other ORMs that NextAuth supports (e.g. Prisma) don't rename the column names so they work fine.

**Comment by bcerquiare** [comment]
+1

It will be very welcome.

**Comment by AndriiSherman** [comment]
Added in 0.19.0
Please check https://orm.drizzle.team/kit-docs/config-reference#casing
