### ISSUE TITLE
Running studio config don't accept mysql2 driver

### ISSUE THREAD

**Issue by peterszarvas94** [drizzle-team/drizzle-kit-mirror#140]
When I try to run `drizzle-kit studio`, with the config below, _sometimes_ me and [others on Discord](https://discord.com/channels/1043890932593987624/1124768693549797416/1125397377440825384) got an error:

```ts
import type { Config } from 'drizzle-kit';
import * as dotenv from "dotenv";
dotenv.config();

export default {
  schema: "src/schema.ts",
  out: "/migrations",
  driver: "mysql2",
  dbCredentials: {
    connectionString: process.env.DATABASE_URL!,
  }
} satisfies Config;
```

> Invalid input  "mysql2" is not a valid driver. Available drivers: "pg", "mysql2", "better-sqlite", "libsql", "turso".

Package versions:

```
"dotenv": "^16.3.1",
"drizzle-kit": "^0.19.12",
"drizzle-orm": "^0.27.2"
```

I tried this patch:

I modified `node_modules/drizzle-kit/index.cjs` line 51894:

```ts
// old code
options.driver === "mysql"
// new code
options.driver === "mysql2"
```

It solved for me.

**Comment by AndriiSherman** [comment]
should be fixed in `drizzle-kit@0.19.13`
