### ISSUE TITLE
Studio allow to configure listening host

### ISSUE THREAD

**Issue by anbraten** [drizzle-team/drizzle-kit-mirror#141]
If running drizzle-kit studio it currently listens to `127.0.0.1` only. This is a secure default setting, but in some cases like when using dev-container, gitpod, so from inside a container ... it is necessary to listen to sth like `0.0.0.0`.

Adding an option like `--host 0.0.0.0` similar to  `drizzle-kit studio --port 1234` could solve the problem.

**Comment by SinPP** [comment]
+1. Often needed in reverse proxy environments

**Comment by AndriiSherman** [comment]
should be fixed in `drizzle-kit@0.19.13`. By default 0.0.0.0 will be used and also --host option is available
