### ISSUE TITLE
`drizzle-kit introspect:mysql` codegen broken

### ISSUE THREAD

**Issue by 205g0** [drizzle-team/drizzle-kit-mirror#142]
Now, a `drizzle-kit introspect:mysql` forgets the comma after the the generated ...`primaryKey(table.id)` line, check line 6 in following example:
```ts
export const users = mysqlTable("users", {
        ...
},
(table) => {
	return {
		usersId: primaryKey(table.id)
		email: unique("email").on(table.email),
	}
});
```

_Originally posted by @205g0 in https://github.com/drizzle-team/drizzle-kit-mirror/issues/124#issuecomment-1665338932_

**Comment by AndriiSherman** [comment]
fixed in an internal branch. Planned to be released today

**Comment by 205g0** [comment]
You are AMAZING, thanks. You know what ,I just used a sed command to postprocess the output but a real fix a so much better, closing. BTW, if you find some time, there's also another issue with codegen: https://github.com/drizzle-team/drizzle-kit-mirror/issues/90
