### ISSUE TITLE
Support for bun:sqlite

### ISSUE THREAD

**Issue by Atmos4** [drizzle-team/drizzle-kit-mirror#143]
Drizzle ORM works with bun:sqlite, which is very nice.
However, DrizzleKit has no support for it yet. Since better-sqlite3 does not work on Bun, using Drizzle with bun:sqlite is not really possible. Applying migrations works, but generating them is currently not available AFAIK.

Any plans on supporting it in the future? Maybe I am doing something wrong, any idea or `drizzle.config.ts` sample?

**Comment by juanma1331** [comment]
Im in the same spot. Would be nice to have the support.

**Comment by t18n** [comment]
Seems like `drizzle-kit` is a little behind `drizzle-orm`. Here is my workaround
```
// drizzle.config.ts

import { Config } from "drizzle-kit";

export default {
  schema: "./src/db/schema.ts",
  out: "./src/db/migrations",
} satisfies Config;
```

Then run `bun drizzle-kit generate:sqlite`. This will generate the migration files, and it does not need db connection at this point. Then use `drizzle-orm` to run the migrations with this script:

```
// migrate-db.ts
import { drizzle } from 'drizzle-orm/bun-sqlite';
import { migrate } from 'drizzle-orm/bun-sqlite/migrator';
import { Database } from 'bun:sqlite';

const sqlite = new Database('sqlite.db');
const db = drizzle(sqlite);

// this will automatically run needed migrations on the database
migrate(db, { migrationsFolder: './src/db/migrations' });
```

Create the file and run `bun scripts/migrate-db.ts`.

**Comment by xantiagoma** [comment]
I've tried running the studio locally
```ts
import * as schema from "./schema";

import studio, { Setup } from "@drizzle-team/studio";

import { Database } from "bun:sqlite";
import { drizzle } from "drizzle-orm/bun-sqlite";

const db = drizzle(new Database("db.sqlite"));
const setup: Setup = {
  type: "sqlite",
  db: db,
  schema: schema,
};

const server = await studio.prepareServer(setup);

const port = 4983;
const host = "0.0.0.0";
server.start({
  host,
  port,
  cb: (err2, address) => {
    if (err2) {
      console.error(err2);
    } else {
      console.log(
        `
Hey Drizzle Studio is up and running`
      );
    }
  },
});
```
And works just fine, the fastify server it works with underneath runs as expected.

I think it is just a matter of adding an extra option, as they made with "turso".

**Comment by albbus-stack** [comment]
Bump, support for Bun should be pretty straightforward since it is already implemented in drizzle-orm. Take care 🤘

**Comment by L-Mario564** [comment]
Closing in favor  of https://github.com/drizzle-team/drizzle-orm/issues/1520 over on the main repo.
