### ISSUE TITLE
control infer mode for timestamp columns in `drizzle-kit introspect:pg`?

### ISSUE THREAD

**Issue by Sejmou** [drizzle-team/drizzle-kit-mirror#144]
Hi,

first of all thanks for all the amazing work around drizzle and drizzle-kit. I really love the developer experience <3

However, I am having an issue with the `drizzle-kit introspect:pg` command. I can't find a way to control the way timestamp columns in my DB are handled upon introspection/schema generation.

The [drizzle docs](https://orm.drizzle.team/docs/column-types/pg#timestamp) state that there are two types of 'infer modes' one can specify: `date` or `string`. In my case, I would need the `date` infer mode, as I use Dates in my application instead of parsing strings (I use Next.js with tRPC and superjson as the [transformer](https://trpc.io/docs/server/data-transformers) to work around the Date object JSON serialization issue when transferring data between server and client).

My temporary workaround to get what I want is to remove all occurrences of `mode: 'string'` from my schema file after running `drizzle-kit introspect:pg`. What is the proper way to do this?

**Comment by sfsr12** [comment]
I am also facing this issue.  For me, I am DB first workflow so when I re-run drizzle-kit pull the changes are overwritten or I need to manually fix it.

**Comment by sfsr12** [comment]
For future people finding this like I did.  Until it is added to drizzle-kit - this is my workaround:

``` json5
// package.json
{
  "scripts": {
    "db:pull": "drizzle-kit pull  && sed -ie \"s/{ mode: 'string' }/{ mode: 'date' }/g\" ./src/db/schema.ts"
  }
}
```

Basically just add a very sketchy sed after the schema is pulled.

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/3239.
