### ISSUE TITLE
'AnyPgColumn' is a type and must be imported using a type-only import

### ISSUE THREAD

**Issue by JustMrMendez** [drizzle-team/drizzle-kit-mirror#147]
#### AnyPgColumn is a type and must be imported using a type-only import when preserveValueImports and isolatedModules are both enabled.

Generated imports
```js
import { pgTable, pgEnum, pgSchema, AnyPgColumn, foreignKey, ... } from "drizzle-orm/pg-core"
```

I am using svelte-kit

just adding `type` would clear this warning/error

**Comment by AndriiSherman** [comment]
should be fixed in `drizzle-kit@0.19.13`
