### ISSUE TITLE
Docs Incorrect: Default Config File 

### ISSUE THREAD

**Issue by shellscape** [drizzle-team/drizzle-kit-mirror#148]
The docs here https://orm.drizzle.team/kit-docs/commands#introspect--pull state that the default config file is `drizzle.config.ts`. However, that doesn't seem to be aligned with the current version of the drizzle-kit CLI. Upon creating `drizzle.config.ts` and running `drizzle-kit introspect:pg` I'm presented with this:

```
drizzle-kit: v0.19.12
drizzle-orm: v0.28.1

No config path provided, using default 'drizzle.config.json'
```

I'm trying to convince a team to move over to Drizzle. Consistency in areas like this are important to a "stable" image.

**Comment by AndriiSherman** [comment]
Do you have `drizzle.config.json` file? Or you didn't have any config file?

**Comment by AndriiSherman** [comment]
This was intentional because we are supporting ts/js and json files. If no ts file is found, we try to find a js file and use it by default. If no js file is found, we try to find a json file and use it by default. If none of them are found and no custom schema path was defined, we throw an error. It seems like you had a JSON path, but we need to be sure.

**Comment by shellscape** [comment]
A `drizze.config.ts` file existed. Drizzle threw the error above, as provided. I assumed that because a valid file existed and Drizzle threw that error anyways, that the docs were wrong, given the content of the error message.

A few things here on the DX:
- Drizzle could state in the console output what it tries to find
- The docs could mention the waterfall you just described (if they do, the section I mentioned above doesn't contain that info)
- The error message could describe what it tried to find, but it should really avoid using the filename of the last file it looks for as the authoritative default file name. Instead, it could simply state a config file wasn't found and provide a link to the docs (or state which files plural weren't found) 

If there's a repo somewhere I could contribute to Id be happy to PR this

**Comment by shellscape** [comment]
Thanks!
