### ISSUE TITLE
drizzle-orm is missing for introspecting with npx

### ISSUE THREAD

**Issue by birdy90** [drizzle-team/drizzle-kit-mirror#15]
I'm really excetied to start working with drizzle, but it won't let me start. I have an existing DB, and I want to get its' schema
using `introspect`, but I'm getting error `please install required packages: drizzle-orm`. as you can see on a screenshot, I already have it installed:

![image](https://user-images.githubusercontent.com/4995346/224999375-a7ab3b7f-1102-4b1e-b656-d22ba6ccff25.png)

environment:
windows: 10
nodejs: v18.14.2
npm: 9.5.1
terminal: powershell inside ItelliJ IDEA

**Comment by AlexBlokh** [comment]
please use `npx drizzle-kit...`, I've updated the doc

**Comment by birdy90** [comment]
Unfortunately, it gives me the same error

**Comment by AlexBlokh** [comment]
I see, you don't have drizzle-kit installed in the project as dev dependency
as a global file it won't have access to `drizzle-orm` installed in your project
