### ISSUE TITLE
`introspect` Creates a `schema.ts` File with Unused Imports

### ISSUE THREAD

**Issue by shellscape** [drizzle-team/drizzle-kit-mirror#150]
Upon running `introspect:pg` this evening, drizzle-kit did it's thing and created a `schema.ts` file successfully. However, it included named imports in the file which aren't used in the schema.

For anyone running a strict `tsconfig.json`, that's a problem which requires manual intervention. Not ideal for automation. Here's what was imported:

```
import { pgTable, pgEnum, pgSchema, AnyPgColumn, serial, bigint, boolean, timestamp, uuid, text, jsonb, integer } from "drizzle-orm/pg-core"
```

With these two being the offenders `pgSchema, AnyPgColumn`. I'm not exactly keen on having to have another `tsconfig.json` in the directory to turn off strictness just for drizzle, either.

**Comment by AndriiSherman** [comment]
pgSchema, pgENum, and AnyPgColumn should be included in imports only when needed in `drizzle-kit@0.19.13`

**Comment by shellscape** [comment]
Thanks!

**Comment by shellscape** [comment]
@AndriiSherman I'm still getting unused `pgTable` in the generated schema file.

**Comment by xsjcTony** [comment]
@AndriiSherman I'm still getting unused imports with `mysql`:
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/45784210/6a2c0063-1eb4-4471-b367-7a4a9db22595)
