### ISSUE TITLE
PG: Unable to connect with SSL

### ISSUE THREAD

**Issue by rphlmr** [drizzle-team/drizzle-kit-mirror#157]
Hello,

When we use a PG DB with self signe SSL (Supabase), it is not possible to connect:
(`npx drizzle-kit introspect:pg ` for example)

```terminal
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: self-signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1545:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:959:8)
    at ssl.onhandshakedone (node:_tls_wrap:743:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
```

Maybe `dbCredentials` should follow `pg` ssl config when driver is `pg`?

https://node-postgres.com/features/ssl#self-signed-cert

```txt
ssl: {
    rejectUnauthorized: boolean,
    ca: fs.readFileSync('/path/to/server-certificates/root.crt').toString(),
    key: fs.readFileSync('/path/to/client-key/postgresql.key').toString(),
    cert: fs.readFileSync('/path/to/client-certificates/postgresql.crt').toString(),
  },
```

drizzle-kit: v0.19.12
drizzle-orm: v0.28.2

**Comment by laubonghaudoi** [comment]
This is related to https://github.com/drizzle-team/drizzle-orm/issues/831, currently there is no way to connect to postgresql db with SSL.

**Comment by olehferents-lnoks** [comment]
Try `sslmode=no-verify`. It works for me.

**Comment by zigenis** [comment]
> Try `sslmode=no-verify`. It works for me.

For the benefit of future readers:
You can append it to the end of your connection string like so:
```
postgres://USERNAME:PASSWORD@HOST:PORT/DATABASE?sslmode=no-verify
```

**Comment by pboling** [comment]
I think this is what I need to be able to do, but I can't:
```
export default {
	schema: './src/lib/db/schema.server.ts',
	out: './migrations',
	driver: 'pg',
	dbCredentials: {
		connectionString: DATABASE_URL,
// The ssl option is not supported...
		ssl: {
			rejectUnauthorized: false
		}
	}
} satisfies Config;
```
So, for now I'm trying the `no-verify` ideas from the previous comments.

**Comment by kazdegroot** [comment]
From some looking around the code; drizzle-kit validates the config using zod; so the types not aligning with actually available config options causes some additional issues. 

On my end (beyond this ssl issue), both postgres.js and and pg allow passing the password as an (async) function returning the password, so we can get a fresh RDS IAM token on (re)connection; this is not allowed by the schema, so my team can't actually use either the new command line features or studio

**Comment by bigbakaboo** [comment]
> I came across this issue while troubleshooting the connection to my Supabase database. I was eventually able to get SSL working for both drizzle-kit and my Next.js app and thought I'd share what I did here. I haven't confirmed with 100% certainty that it's using `verify-full` in all cases, but I'm not intentionally working around it (`no-verify`, `require`, etc.).
> 
> I downloaded the Supabase public CA cert (from Supabase console) and added it to my project (I put it in `/db/supabase/root.crt`).
> 
> My `drizzle.config.ts` looks like this:
> 
> ```
> import { defineConfig } from "drizzle-kit";
> require("dotenv").config({ path: [".env.local", ".env"] });
> 
> const databaseUrl = process.env.DATABASE_URL;
> 
> if (!databaseUrl) {
>   throw new Error("DATABASE_URL environment variable is not set");
> }
> 
> export default defineConfig({
>   schemaFilter: ["public"],
>   dialect: "postgresql",
>   schema: "./db/schema.ts",
>   out: "./db/migrations",
>   dbCredentials: {
>     url:
>       databaseUrl +
>       "?sslmode=verify-full" +
>       "&sslrootcert=db/supabase/root.crt",
>   },
> });
> ```
> 
> and my `db.ts` looks like this:
> 
> ```
> import { drizzle } from "drizzle-orm/postgres-js";
> import postgres from "postgres";
> import fs from "fs";
> 
> const connectionString = process.env.DATABASE_URL;
> 
> if (!connectionString) {
>   throw new Error("DATABASE_URL environment variable is not set");
> }
> 
> // Disable prefetch as it is not supported for "Transaction" pool mode
> export const client = postgres(connectionString + "?sslmode=verify-full", {
>   prepare: false,
>   ssl: { ca: [fs.readFileSync("db/supabase/root.crt")] },
> });
> export const db = drizzle(client);
> ```
> 
> and my environment variable is defined as:
> 
> ```
> DATABASE_URL=postgresql://postgres.myProjectId:myPassword@aws-0-us-east-1.pooler.supabase.com:6543/postgres
> ```
> 
> After doing everything above, the app will work but drizzle-kit will still not work, giving the `self-signed certificate in certificate chain` error.
> 
> The app is using the `postgres` NPM package. I noticed that Drizzle-kit uses it too, since when I ran `drizzle-kit studio` one of the console messages said `Using 'postgres' driver for database querying`.
> 
> I then installed the `pg` NPM package (without removing `postgres`).
> 
> After that drizzle-kit says `Using 'pg' driver for database querying` and it works (studio loads, etc).
> 
> Result: SSL is working in my local environment for both drizzle-kit and my Next.js app (and at least on the surface it looks like it's using `verify-full`, but not confirmed). 🎉

man i dont think this works anymore :(

**Comment by bigbakaboo** [comment]
https://supabase.com/docs/guides/database/connecting-to-postgres#connecting-with-drizzle
ok this fixed it
