### ISSUE TITLE
[BUG] Custom types generating "" around non-standard types (pg)

### ISSUE THREAD

**Issue by eajr** [drizzle-team/drizzle-kit-mirror#167]
### What version of drizzle-orm are you using?
^0.28.3

### What version of drizzle-kit are you using?
^0.19.13

### Describe the Bug

When using custom types it puts quotes around the type string on `generate:pg`

#### Example `schema.ts`
```typescript
import { timestamp, uuid, customType, pgTable } from "drizzle-orm/pg-core";

const geometryCType = customType<
    { 
        data: string,
        config: { type: string; SRID: number }
    }
>({
    dataType(config) {
        return `geometry(${config?.type},${config?.SRID})`;
    },
});

export const locations = pgTable("locations", {
    id: uuid("id").defaultRandom().notNull(),
    geom: geometryCType("geom", { type: "POINT", SRID: 4326 }),
    createdAt: timestamp("created_at")
});
```

#### Example output from `generate:pg`

```sql
CREATE TABLE IF NOT EXISTS "locations" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"geom" "geometry(POINT,4326)",
	"created_at" timestamp
);
```

#### How it should look

```sql
CREATE TABLE IF NOT EXISTS "locations" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"geom" geometry(POINT,4326),
	"created_at" timestamp
);
```

#### Additional Info

If you create a custom type that returns a standard pg data type ie "varchar" from `dataType() {}` the "" are not there (as expected).

### Workarounds
After `generate:pg` you can just modify the migration sql that was generated and remove the "", and it works, but this is obviously not ideal.

**Comment by mikerockett** [comment]
I noticed that this does not happen in the context of `ALTER TABLE`. I had my SQL in lowercase, but decided to change it to upper case. Running `generate:pg` again created the new migration file without the double-quotes.

**First Run**

```sql
CREATE TABLE IF NOT EXISTS "chat_events" (
  "id" "BIGINT generated always as identity" PRIMARY KEY NOT NULL,
  -- ...
```

**Second Run (after changing case)**

```sql
ALTER TABLE "chat_events" ALTER COLUMN "id" SET DATA TYPE BIGINT GENERATED ALWAYS AS IDENTITY;
```

**Comment by nikelborm** [comment]
@eajr, did `getSQLType` mentioned [here](https://github.com/drizzle-team/drizzle-kit-mirror/issues/210#issuecomment-1758776817) worked for you?

**Comment by arjunyel** [comment]
`patch-package` to fix this with drizzle-kit

```patch
diff --git a/node_modules/drizzle-kit/bin.cjs b/node_modules/drizzle-kit/bin.cjs
index 9b92321..d347342 100755
--- a/node_modules/drizzle-kit/bin.cjs
+++ b/node_modules/drizzle-kit/bin.cjs
@@ -15496,6 +15496,7 @@ var init_sqlgenerator = __esm({
       "interval minute to second"
     ]);
     isPgNativeType = (it) => {
+      return true
       if (pgNativeTypes.has(it))
         return true;
       const toCheck = it.replace(/ /g, "");

```

I've only tested this type, test other custom types as I have no clue if this will break them

```typescript
import { customType } from "drizzle-orm/pg-core";
export const identity = (name: string) =>
  customType<{
    data: string;
    notNull: true;
    default: true;
  }>({
    dataType() {
      return "BIGINT GENERATED ALWAYS AS IDENTITY";
    },
  })(name);
```
