### ISSUE TITLE
Introspect:mysql invalid params

### ISSUE THREAD

**Issue by AidanNichol** [drizzle-team/drizzle-kit-mirror#17]
I wanted to introspect my existing databases 

I tried
```
drizzle-kit introspect:mysql --out=migrations/ --host=localhost --port=3306 --user=user --password=pass database=db_name
```
Which failed with the following
```
drizzle-kit: v0.17.0
drizzle-orm: v0.22.0

Missing required params
```
I eventually noticed that I had missed the ```--``` from the ```database``` option.
The error message should have told me that  it was missing ```--database```.

**Comment by AndriiSherman** [comment]
Whole `cli` experience is in refactor process right now
We will have proper error messages, multiple configs, improved cli options, etc
Thanks for you feedback!
