### ISSUE TITLE
Error on removal of composite keys on `pgTable` in `postgres`

### ISSUE THREAD

**Issue by Odas0R** [drizzle-team/drizzle-kit-mirror#170]
When removed a composite primary key and renamed a pgTable defined:
```ts
//old
const table = pgTable(
  "table",
  {
    id: text("id").notNull(),
    name: text("name").notNull(),
  },
  (t) => ({
    pk: primaryKey(t.id, t.name),
  }),
);

// new
const table = pgTable(
  "table_two",
  {
    id: text("id").notNull().primaryKey(),
    name: text("name").notNull(),
  }
);
```

Throws the error when `npx drizzle-kit generate:pg`:

```
TypeError: Cannot read properties of undefined (reading 'compositePrimaryKeys')
```

**Versions:**
```
"drizzle-kit": "^0.19.13",
"drizzle-orm": "0.28.2",
```

**Comment by dBianchii** [comment]
Happening to me a lot

**Comment by bestickley** [comment]
This is happening to me too when renaming a column which is a part of a composite primary key. After selecting "rename column" option here:
```
Is issue_id column in issue_upvote table created or renamed from another column?
❯ + issue_id               create column
  ~ feedback_id › issue_id rename column
```

I temporarily fixed it by changing node_modules/.pnpm/drizzle-kit@0.20.14/node_modules/drizzle-kit/bin.cjs:17115
from:
`constraintName: json1.tables[tableName].compositePrimaryKeys[PgSquasher.unsquashPK(it).name].name`
to
`constraintName: json1.tables[tableName]?.compositePrimaryKeys[PgSquasher.unsquashPK(it).name].name`

This issue did result in this line:
`ALTER TABLE "lh"."issue_upvote" DROP CONSTRAINT "undefined";--> statement-breakpoint`
but I just commented it out.

**Comment by mdingena** [comment]
I just ran into this same issue when choosing `rename table` option during generation. I followed @bestickley's steps and was able to resolve it.

**Comment by prichodko** [comment]
I saw this landed in v.0.21.3 - https://github.com/drizzle-team/drizzle-orm/issues/2344.

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/2344 over on the main repo.
