### ISSUE TITLE
`@drizzle-team/studio`  Unknown license

### ISSUE THREAD

**Issue by davlet61** [drizzle-team/drizzle-kit-mirror#173]
Hi, 
I am trying to introduce `drizzle` to a codebase to use with existing `knex` queries for better typesafety. 
However, I am getting a `License violation` in **Snyk**, so I was wondering if it would be possible to add a license to it.

Thanks in advance!

**Comment by brianopedal** [comment]
Yes, the license issue is important to have settled, is Drizzle open source or not, and if it is what license does it have?

**Comment by septatrix** [comment]
Especially for drizzle-kit this is really important. Currently there is no information under which license the generated migrations can be used!

**Comment by septatrix** [comment]
x-ref: https://github.com/drizzle-team/drizzle-orm/issues/580

**Comment by L-Mario564** [comment]
Kit is now open-source under Apache License 2.0. Drizzle Studio is and will remain closed-source though.
