### ISSUE TITLE
[BUG]: Drizzle Kit migrations should include `foreign_key_checks` statements

### ISSUE THREAD

**Issue by paul-uz** [drizzle-team/drizzle-kit-mirror#176]
### What version of `drizzle-orm` are you using?

0.28.2

### What version of `drizzle-kit` are you using?

0.19.12

### Describe the Bug

MySQL migration files created by Drizzle Kit do not include `foreign_key_checks` statements when it generates migration files that deal with FK constraints.

Issue submitted upon request, see [here](https://discord.com/channels/1043890932593987624/1144572247579828315/1145780231144218764)

**Comment by L-Mario564** [comment]
We'll continue tracking this issue over here: https://github.com/drizzle-team/drizzle-orm/issues/3265.
