### ISSUE TITLE
Concern about Unauthorized drizzle-kit push Commands

### ISSUE THREAD

**Issue by wojtekKrol** [drizzle-team/drizzle-kit-mirror#180]
#### Summary:

I'm using `drizzle-kit` for database operations. I'm concerned about securing the database against unauthorized `drizzle-kit push` commands that could alter the schema or data.

#### Steps to Reproduce:

1. Run `drizzle-kit push:pg` from the shell.
2. Notice that the database schema can be modified without additional verification of user credentials or roles.

#### Expected Behavior:

There should be some form of protection or verification to ensure that only authorized developers can run `drizzle-kit push` commands that modify the database schema or data.

#### Possible Solutions:

1. Implement a two-factor authentication mechanism before accepting `push` commands that modify the schema or data.
2. Introduce a digital signature verification for schema changes, where only approved digital signatures can execute schema-altering commands.
3. Create an authorization layer that works independently of the database or front-end technology, requiring explicit permission for schema modifications.
  
#### Additional Context:

The `db:push` command is currently executed from `package.json` as follows:
```json
"db:push": "drizzle-kit push:pg"
```

Would be great to hear if you have any recommendations or if this is in the pipeline for future releases.

**Comment by lukeweston1234** [comment]
Not a member of the Drizzle team, so correct me if I am wrong, but if someone can access your shell or has access to your credentials you have an even larger problem no? Additionally, if you're worried about an intern making changes to your schema on accident, they could probably do the same with whatever credentials you have in the project. The solution here seems to be having separate branches for dev and production, and that is going to be a potential problem with any ORM.

**Comment by L-Mario564** [comment]
Push command is only meant to be used in dev, not prod. You can also specify the level of access via users, roles and permissions in your respective databaase; these are things that Drizzle can't and won't manage.
