### ISSUE TITLE
Inability to Revert Migrations in Drizzle

### ISSUE THREAD

**Issue by wojtekKrol** [drizzle-team/drizzle-kit-mirror#183]
### Problem Description

In TypeORM, reverting a database migration is straightforward due to the `up()` and `down()` methods generated with each migration file. Drizzle, however, lacks this essential feature, making it difficult to rollback database schema changes.

#### Steps to Reproduce

1. **Initial Schema**: Assume we have a table `TODO` with fields `{id, title}`.
2. **Add Field**: Add a new field `description` to the `TODO` table so that the schema becomes `{id, title, description}`.
    - Generate a migration file and migrate changes to the database.
3. **Attempt to Revert**: Now, let's say you want to revert these changes to `{id, title}`.
    - Run `drizzle-kit drop` to choose which migration file to delete. Assume you remove the last generated file that adds the 'description' field.
    - Run the application to try and revert the schema change. This fails to revert the database to `{id, title}`.

#### Issues Encountered

1. Drizzle doesn't offer an automatic way to revert migrations.
2. After dropping the last migration file, generating a new migration file via `drizzle-kit generate:{dialect}` results in an empty file. This is because Drizzle checks the last migration file and the current schema, both of which are `{id, title}`, thus seeing no changes to migrate.

#### Suggested Improvement

Implement functionality similar to TypeORM’s `up()` and `down()` methods to facilitate easy migration rollbacks.

### Note
I would have contributed this feature myself, but unfortunately, Drizzle-kit doesn't seem to be open source.

**Comment by AndriiSherman** [comment]
@fireayehu what is the case for you to revert the migration? Would it be production deploy or something else?

**Comment by fireayehu** [comment]
> @fireayehu I created [post on reddit](https://www.reddit.com/r/nextjs/comments/169f483/navigating_drizzles_migration_handling_a_new/?utm_source=share&utm_medium=web2x&context=3) how to work with migrations and what to not do because of potential mess up.

Got your concerns, but at least there needs to be a way to revert last run migrations. Awesome post btw

**Comment by fireayehu** [comment]
> @fireayehu what is the case for you to revert the migration? Would it be production deploy or something else?

@AndriiSherman  In both cases, but for now on development. Let's say I created a couple of table schemas, then generated and run the migration. After that if I changed my mind and wanted to remove on of those tables from my last migration, in drizzle way I can drop my last migration, then remove one of the schema and generate a new migration and run it. But in the database both of the tables with their constraints will be available. So I manually have to go to the db and make the changes

The way am seeing it is `npx drizzle-kit drop` should only drop the last migration and also do rollback on the database for the dropped migration. 

NB: One more thing I noticed is dropping a migration does not remove the migration row from the migration table in the database.

**Comment by JeromeBu** [comment]
linked to  #36

**Comment by StationSoen** [comment]
In the drizzle-orm repository, the issue was closed by the drizzle team with a wont fix. (Note: [link](https://github.com/drizzle-team/drizzle-orm/issues/263)) 
I still think a revert migration feature is needed, but I also agree with the Drizzle team on some points.

Anyway, Drizzle has a DX that I'm happy with, and I'm using it well. Thanks to the Drizzle team. 👍🏻

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/2352 over on the main repo.
