### ISSUE TITLE
Drizzle studio doesn't message about localhost, instead 0.0.0.0

### ISSUE THREAD

**Issue by janat08** [drizzle-team/drizzle-kit-mirror#185]
Drizzle Studio is up and running on http://0.0.0.0:4983

0.0.0.0 isn't something that will work on windows or chrome. I just assumed that something is broken.

**Comment by deadcoder0904** [comment]
yes, this is true but if you open up http://localhost:4983, it will work.

however, i'd also like the terminal to print http://localhost:4983 (i don't like 0.0.0.0 for some reason)

and this doesn't print http://localhost:3001 either which i guess it should:

```bash
drizzle-kit studio --host localhost --port 3001 --verbose --config drizzle.config.ts
```

it instead prints http://[::1]:3001 which is weird. idk if this is a syntax for ipv6 or something.

**Comment by cat394** [comment]
I am using pnpm package manager and started a local server as pnpm drizzle-kit studio --host 127.0.0.1 and it worked. Maybe [package manager name] drizzle-kit studio --host 127.0.0.1 might work.

**Comment by janat08** [comment]
Doesn't work on windows

**Comment by deadcoder0904** [comment]
i've used it on both mac & windows. worked fine for me :)

**Comment by janat08** [comment]
Then not chrome

**Comment by johnsethsalazar** [comment]
You can try this URL: http://127.0.0.1:4983 too. It works for me.

**Comment by devlopersabbir** [comment]
### I'm facing the same problem,
The below window only shows 
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/82939905/99a548ec-530e-4b3e-acdc-0461d2c04a3f)

**Comment by abdullahmujahidali** [comment]
same issue

**Comment by chrisdruta** [comment]
Same for me on windows 10, tried with npm & bun. Think I narrowed it down to inside the `certs` function under `node_modules\drizzle-kit\bin.cjs`

if you search for `const { key, cert } = await certs() || {};` and remove the `await certs()` part it works (at least for me)

**Comment by smrdotgg** [comment]
> if you search for `const { key, cert } = await certs() || {};` and remove the `await certs()` part it works (at least for me)

Tried that on my Windows + WSL setup, works like a charm! ❣️

**Comment by monpy** [comment]
Hi. I have same issues. showing Welcome page and not any changes. I tried my Mac & chrome. 

I resolved this issue.
try
`brew install mkcert` & `mkcert -install`

chrome debgguer said RR_BLOCKED_BY_PRIVATE_NETWORK_ACCESS_CHECKS
I need mkcert insall same as safari.

**Comment by shige** [comment]
https://github.com/drizzle-team/drizzle-kit-mirror/issues/185#issuecomment-2081952781

I encountered the same problem and resolved it by executing the following:

```sh
brew install mkcert & mkcert -install
```

Thank you!

**Comment by sifengjing** [comment]
> [#185 (comment)](https://github.com/drizzle-team/drizzle-kit-mirror/issues/185#issuecomment-2081952781)
> 
> I encountered the same problem and resolved it by executing the following:
> 
> ```shell
> brew install mkcert & mkcert -install
> ```
> 
> Thank you!




I use codespace. I also encounter this problem. But I execute "brew install mkcert & mkcert -install" and it doesn't work. Has anyone encountered this?

**Comment by janat08** [comment]
The issue is just about showing the right error message or changing messages about ports used. I’ll close the issue as its relatively evident what’s it’s about, but it got hijacked and is old.

**Comment by Jordanburch101** [comment]
> Hi. I have same issues. showing Welcome page and not any changes. I tried my Mac & chrome.
> 
> I resolved this issue. try `brew install mkcert` & `mkcert -install`
> 
> chrome debgguer said RR_BLOCKED_BY_PRIVATE_NETWORK_ACCESS_CHECKS I need mkcert insall same as safari.

This worked for me :)
