### ISSUE TITLE
address error. drizzle-kit studio not opening in chrome

### ISSUE THREAD

**Issue by mxnan** [drizzle-team/drizzle-kit-mirror#191]
terminal shows no error, but npx drizzle-kit studio shows that it is up and running and gives an address but the address shows error in browser and not working.

//drizzle.config.ts
import type { Config } from "drizzle-kit";
import * as dotenv from "dotenv";
dotenv.config({ path: ".env" });

export default {
  driver: "pg",
  schema: "./src/lib/db/schema.ts",
  dbCredentials: {
    connectionString: process.env.DATABASE_URL!,
  },
} satisfies Config;

//

**Comment by deadcoder0904** [comment]
console log your `process.env.DATABASE_URL`... most of the time that was my error.

alternatively, if you are on windows, you need to open up http://localhost:3001 if you are not using other port instead of 3001 as mentioned in https://github.com/drizzle-team/drizzle-kit-mirror/issues/185
