### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by gaonkarBhai** [drizzle-team/drizzle-kit-mirror#195]
I run this command `npx drizzle-kit studio `
it showing like this
`No config path provided, using default path
Reading config file 'A:\Mern Stack\Next js\kanoon-ai\drizzle.config.ts'

[Warning] Drizzle Studio is currently in Beta. If you find anything that is not working as expected or should be improved, feel free to create an issue on GitHub: https://github.com/drizzle-team/drizzle-kit-mirror/issues/new or write to us on Discord: https://discord.gg/WcRKz2FFxN

Drizzle Studio is up and running on http://0.0.0.0:4983`

but chrome is showing :

- This site can’t be reachedThe webpage at http://0.0.0.0:4983/ might be temporarily down or it may have moved permanently to a new web address.
ERR_ADDRESS_INVALID

my drazzile.config.ts file:

`import type { Config } from "drizzle-kit";
import * as dotenv from "dotenv";
dotenv.config({ path: ".env" });

export default {
  driver: "pg",
  schema: "./src/lib/db/schema.ts",
  dbCredentials: {
    connectionString: process.env.DATABASE_URL!,
  },
} satisfies Config;
`

please can anyone help to get rid out of this .....
it is urgent 😥😭

**Comment by gaonkarBhai** [comment]
just try http://127.0.0.1:4983

**Comment by anaskhan28** [comment]
thanks I had the same issue, now it's resolved

**Comment by aadarsh-nagrath** [comment]
> just try http://127.0.0.1:4983

Yeah site has been moved to domain -> http://127.0.0.1:4983/ for now it seems
