### ISSUE TITLE
Purpose of `_meta` directory

### ISSUE THREAD

**Issue by septatrix** [drizzle-team/drizzle-kit-mirror#196]
It is unclear what the `_meta` directory is used for as there is no documentation for it (and the source code is not available yet, see https://github.com/drizzle-team/drizzle-orm/issues/580). Currently I wonder if it has to be checked in to git, and under what circumstances it is required to read from as well as write to this directory.

This would influence how drizzle migrations can/will be deployed on production: Does have to be part of the deployed code, can it be non-existent, is it only needed for ephemeral data or does it have to persist (i.e. in docker this would have to be a mounted volume), is it sufficient to only read from there (i.e. in docker this would allow increased security by marking the filesystem as readonly) etc...

**Comment by LubomirGeorgiev** [comment]
I was wondering the same thing

**Comment by laurensV** [comment]
this should really be explained in the documentation..

**Comment by LubomirGeorgiev** [comment]
Should be checked into git?

**Comment by septatrix** [comment]
Any comment @AlexBlokh? Based on https://github.com/drizzle-team/drizzle-orm/discussions/2832 it seems like all files are mandatory but there is no clear documentation on this...

**Comment by L-Mario564** [comment]
We'll keep track of this issue over here: https://github.com/drizzle-team/drizzle-orm/issues/3261.

**Comment by septatrix** [comment]
> We'll keep track of this issue over here: [drizzle-team/drizzle-orm#3261](https://github.com/drizzle-team/drizzle-orm/issues/3261).

Wouldn't it have more sense to simply move this issue to the other repo? That way all the history, thumbs up, and subscribers would have been preserved...which are lost now :/
