### ISSUE TITLE
Error: type "serial" does not exist

### ISSUE THREAD

**Issue by MuhammadSharyar** [drizzle-team/drizzle-kit-mirror#197]
When I push my schema using "npx drizzle-kit push:pg" it throws this error
error: type "serial" does not exist
severity: 'ERROR',
code: '42704',

### My Schemas
import { pgEnum, pgTable, text, serial, integer, timestamp, varchar } from "drizzle-orm/pg-core";

export const userSystemEnum = pgEnum("user_system_enum", ["user", "system"]);

export const chats = pgTable("chats", {
  id: serial("id").primaryKey(),
  pdfName: text("pdf_name").notNull(),
  pdfUrl: text("pdf_url").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  userId: varchar("user_id", { length: 256 }).notNull(),
  fileKey: text("file_key").notNull(),
});

export const messages = pgTable("messages", {
  id: serial("id").primaryKey(),
  chatId: integer("chat_id")
    .references(() => chats.id)
    .notNull(),
  content: text("content").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  role: userSystemEnum("role").notNull(),
});

### My drizzle.config.ts file

import type { Config } from "drizzle-kit";
import * as dotenv from "dotenv";
dotenv.config({ path: ".env" });

export default {
  driver: "pg",
  schema: "./src/lib/db/schema.ts",
  dbCredentials: { connectionString: process.env.DATABASE_URL! },
} satisfies Config;

**Comment by MrOxMasTer** [comment]
https://github.com/drizzle-team/drizzle-orm/issues/663

**Comment by OpenSource03** [comment]
+1

**Comment by enkemande** [comment]
are you guys going to fix this? also having this error with serial https://github.com/drizzle-team/drizzle-orm/issues/663

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/834.
