### ISSUE TITLE
Allow skipping the confirmation prompt for the `drizzle-kit push` command

### ISSUE THREAD

**Issue by myftija** [drizzle-team/drizzle-kit-mirror#198]
There is currently a `--strict` flag to always prompt for confirmation. It would be useful to also have a flag to always skip the confirmation prompt for cases where interaction is not viable. E.g., cleaning up a local DB in the CI after integration tests have been run.

More generally, it would also be useful to have a top level configuration key to disable interactive mode across all commands. Is this something you would consider adding?

**Comment by the-simian** [comment]
this is related to https://github.com/drizzle-team/drizzle-kit-mirror/issues/166

**Comment by edamazzio** [comment]
We really need a way to run drizzle-kit commands in a non-interactive way for CI/CD

**Comment by L-Mario564** [comment]
The `push` command now has a `--force` flag to achieve exactly this: https://orm.drizzle.team/docs/drizzle-kit-push#extended-list-of-configurations.
