### ISSUE TITLE
generated enums are not camel cased

### ISSUE THREAD

**Issue by capaj** [drizzle-team/drizzle-kit-mirror#2]
I used command `drizzle-kit introspect:pg --out=migrations/ --connectionString=postgresql://user:pass@host:port/db_name` and
![image](https://user-images.githubusercontent.com/1305378/216294318-954f5b31-b3a3-48dd-9477-d34704ecc20c.png)

why are these not camel cased?
Sure I can go in and fix it manually, but I think camel casing is best practice when it comes to naming stuff in JS/TS.

**Comment by AlexBlokh** [comment]
@capaj will fix this asap, seems like a problem with PascalCase

**Comment by AndriiSherman** [comment]
Fixed in [0.17.0](https://github.com/drizzle-team/drizzle-kit-mirror/releases/tag/v0.17.0)
