### ISSUE TITLE
[MySQL] generate timestamp .defaultNow() bug

### ISSUE THREAD

**Issue by peppasd** [drizzle-team/drizzle-kit-mirror#20]
I'm using drizzle-kit v0.17.0 and a planetscale db. I have the following demo schema:

```ts
export const accounts = mysqlTable(
  "accounts",
  {
    id: serial("id").primaryKey(),
    email: varchar("email", { length: 30 }).notNull(),
    lastLogin: timestamp("last_login").notNull().defaultNow(),
  },
  (accounts) => ({
    emailIdx: uniqueIndex("email_unq").on(accounts.email),
  })
);
```

Using `drizzle-kit generate:mysql` I get the following SQL:

```sql
CREATE TABLE `accounts` (
	`id` serial AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`email` varchar(30) NOT NULL,
	`last_login` timestamp NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX email_unq ON accounts (`email`);
```

If I try to apply those changes to my database, I get the error `SQL Error [1067] [42000]` warning me that the `last_login` field is not set right. Following the [MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/timestamp-initialization.html) on how to initialize timestamps, I changed `(now())` to `CURRENT_TIMESTAMP` and now works it works just fine. Curiously enough, those two expressions should be the same.

**Comment by craigerm** [comment]
@peppasd I had a similar issue and was able to work around it by passing in some raw sql (wrapped in an instance of `SQL`) to use `CURRENT_TIMESTAMP` as the default.

```typescript
import { SQL } from 'drizzle-orm/sql'

const CURRENT_TIMESTAMP = new SQL(['CURRENT_TIMESTAMP'])

export const accounts = mysqlTable(
  "accounts",
  {
    id: serial("id").primaryKey(),
    email: varchar("email", { length: 30 }).notNull(),
    lastLogin: timestamp("last_login").notNull().default(CURRENT_TIMESTAMP),
  },
  (accounts) => ({
    emailIdx: uniqueIndex("email_unq").on(accounts.email),
  })
);
```

Now, when you generate migrations it will output as expected without having to manually edit the sql file. Hope it helps!

**Comment by AndriiSherman** [comment]
@craigerm is right. The case with .defaultNow() - is that orm using `now()` expression in migrations. Which is not acceptable at PlanetScale for example, but seems to be the same in MySQL docs

In case you want exactly `CURRENT_TIMESTAMP ` you can even use this syntax

```ts
export const accounts = mysqlTable(
  "accounts",
  {
    id: serial("id").primaryKey(),
    email: varchar("email", { length: 30 }).notNull(),
    lastLogin: timestamp("last_login").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (accounts) => ({
    emailIdx: uniqueIndex("email_unq").on(accounts.email),
  })
);
```
