### ISSUE TITLE
`driver: 'postgres'`

### ISSUE THREAD

**Issue by mkantor** [drizzle-team/drizzle-kit-mirror#200]
Drizzle ORM supports using [Postgres.js](https://github.com/porsager/postgres) as a driver, but it doesn't seem like Drizzle Kit does. It would be great if I could avoid installing `pg` separately just for Drizzle Kit/Studio.

By the way, great work on Drizzle. It's been a joy to use so far.

**Comment by mkantor** [comment]
Looks like this [is already planned](https://discord.com/channels/1043890932593987624/1124768693549797416/1124780468085207161). Looking forward to it!

**Comment by sajaghori** [comment]
Would be a great addition!
