### ISSUE TITLE
Drizzle push not working.

### ISSUE THREAD

**Issue by Sukrittt** [drizzle-team/drizzle-kit-mirror#207]
# Description
I made changes in my schema.ts and tried to push it to the database.
But there is a weird sql command that is being displayed even though the changes I have made has nothing to do with the model 'books'.

![drizzle-error](https://github.com/drizzle-team/drizzle-kit-mirror/assets/106579296/b9a74906-2774-40fc-b423-d64f36aee342)

This is what I got after regenerating the sql for the updated schema:
```
ALTER TABLE `dues` ADD `transferAccountType` varchar(100);--> statement-breakpoint
ALTER TABLE `dues` ADD `transferAccountId` int;
```

However, when I delete my database (PlanetScale) and create a new one and again regenerate the sql for the whole schema and push it. It works.

```
// Books schema
export const books = mysqlTable("books", {
  id: serial("id").primaryKey(),
  userId: varchar("userId", { length: 255 }).notNull(),
  monthIncome: float("monthIncome").notNull(),
  totalSpendings: float("totalSpendings").notNull().default(0),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
  needsPercentage: float("needsPercentage").notNull(),
  wantsPercentage: float("wantsPercentage").notNull(),
  investmentsPercentage: float("investmentsPercentage").notNull(),
});
```

Would like to know if I am doing something wrong.

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/2458.
