### ISSUE TITLE
Drizzle studio is not working

### ISSUE THREAD

**Issue by thegreatestcompany** [drizzle-team/drizzle-kit-mirror#208]
Can't fin the URL http://0.0.0.0:4983/ when running Drizzle studio. Here is my drizzle.config.ts :

import type { Config } from "drizzle-kit";
import * as dotenv from "dotenv";

dotenv.config({ path: ".env" });

export default {
    driver: "pg",
    schema: "./lib/db/schema.ts",
    dbCredentials: {
        connectionString: process.env.DATABASE_URL!,
    }
} satisfies Config;

**Comment by Ayush-v** [comment]
Please make sure that u are using the latest version of "drizzle-kit": "^0.19.13" this is working for me 
and check if the drizzle.config.ts is in the root directory

**Comment by arielvieira** [comment]
Try adding `--host localhost` or `--host 127.0.0.1` when running the `drizzle-kit studio` cli command

```
$ drizzle-kit studio --host localhost

or

$ drizzle-kit studio --host 127.0.0.1
```

It worked for me

**Comment by Indu-Chandana** [comment]
@arielvieira Thanks. It work for me. -> npx drizzle-kit studio --host 127.0.0.1

**Comment by L-Mario564** [comment]
Fixed in latest.
