### ISSUE TITLE
drizzle studio is not running and it shows the following error

### ISSUE THREAD

**Issue by Ruby-abym** [drizzle-team/drizzle-kit-mirror#209]
The web page at http://0.0.0.0:4983/ might be temporarily down or it may have moved permanently to a new web address.

**Comment by xmayukx** [comment]
@Ruby-abym  Try http://localhost:4983/

**Comment by Ayush-v** [comment]
> The web page at http://0.0.0.0:4983/ might be temporarily down or it may have moved permanently to a new web address.

can you please explain the problem a little more?

**Comment by L-Mario564** [comment]
Studio no longer runs on localhost.
