### ISSUE TITLE
Don't add quotes for interpolated dataTypes. 

### ISSUE THREAD

**Issue by seivan** [drizzle-team/drizzle-kit-mirror#210]
Was trying to add a fix for it myself, only to find out the code isn't available, or am I wrong?

Related: https://github.com/drizzle-team/drizzle-orm/issues/295#issuecomment-1722510868

This kinda breaks custom types completely.

**Comment by eajr** [comment]
Same as my open issue: https://github.com/drizzle-team/drizzle-kit-mirror/issues/167

No traction on it tho

**Comment by seivan** [comment]
@eajr Yeah though I suspect there is somewhat of a solution in using `PgCustomColumn` and `getSQLType` but I just haven't figured it out yet.

**Comment by arjunyel** [comment]
For Postgres users here is a `patch-package` to fix this with drizzle-kit

```patch
diff --git a/node_modules/drizzle-kit/bin.cjs b/node_modules/drizzle-kit/bin.cjs
index 9b92321..d347342 100755
--- a/node_modules/drizzle-kit/bin.cjs
+++ b/node_modules/drizzle-kit/bin.cjs
@@ -15496,6 +15496,7 @@ var init_sqlgenerator = __esm({
       "interval minute to second"
     ]);
     isPgNativeType = (it) => {
+      return true
       if (pgNativeTypes.has(it))
         return true;
       const toCheck = it.replace(/ /g, "");

```

I've only tested this type, test other custom types as I have no clue if this will break them

```typescript
import { customType } from "drizzle-orm/pg-core";
export const identity = (name: string) =>
  customType<{
    data: string;
    notNull: true;
    default: true;
  }>({
    dataType() {
      return "BIGINT GENERATED ALWAYS AS IDENTITY";
    },
  })(name);
```

**Comment by nikelborm** [comment]
@arjunyel You coulld've just write this patch once in one comment and link all of the >= 5 issues together with links to your original one (github will automatically set backlinks). This way people can also see different discussions happening about your answer and extend their research of the problem

**Comment by arjunyel** [comment]
> @arjunyel You coulld've just write this patch once in one comment and link all of the >= 5 issues together with links to your original one (github will automatically set backlinks). This way people can also see different discussions happening about your answer and extend their research of the problem

Sorry friend, I put it everywhere because I didn't know how else to make sure everyone who needs it, saw it. Since like you said it's spread over 5 issues

**Comment by nikelborm** [comment]
You can link them just by pasting comment with link to your comment with patch here in all of the following issues:
https://github.com/drizzle-team/drizzle-orm/issues/295#issuecomment-2093697013
https://github.com/drizzle-team/drizzle-kit-mirror/issues/167#issuecomment-2093700443
https://github.com/drizzle-team/drizzle-orm/pull/1471#issuecomment-2093705309
https://github.com/drizzle-team/drizzle-orm/issues/579#issuecomment-2093706141

But's that's not necessary already

**Comment by L-Mario564** [comment]
We'll continue tracking this over here: https://github.com/drizzle-team/drizzle-orm/issues/3264.
