### ISSUE TITLE
`drizzle-kit generate:mysql --custom` ignores `--custom` flag

### ISSUE THREAD

**Issue by rbuchberger** [drizzle-team/drizzle-kit-mirror#213]
Hello! Thanks for the great library.

I'm handling schema changes with planetcale's branching & deploy request workflow, but I would like to use drizzle's migration files to handle changes to existing data. I believe the `--custom` flag is meant to handle this use case, but when I run `drizzle-kit generate:mysql --custom` it behaves as it would without the flag. (On the first run it creates a SQL file that builds all my existing tables, and on subsequent runs it exits saying that no changes are required.)

- Is my understanding correct? Is this the correct use case?
- Is there any reason I can't just delete everything in the generated SQL file and replace it with my own instructions?
- Is this a bug? It seems like a bug.

Thanks!

**Comment by rbuchberger** [comment]
Update: The answer to my second point appears to be yes. As a workaround I can trick drizzle into generating migrations by modifying the schema file, undo said schema changes, delete the generated SQL, and replace it with whatever I need.

Would be nice to skip that dance, though

**Comment by L-Mario564** [comment]
This is fixed in latest.
