### ISSUE TITLE
BUG]: Ignoring table definitions with the same table name but in different schema

### ISSUE THREAD

**Issue by jfcieslak** [drizzle-team/drizzle-kit-mirror#221]
⚠️ This issue was also added in https://github.com/drizzle-team/drizzle-orm/issues/1435

### What version of `drizzle-orm` are you using?

0.28.6

### What version of `drizzle-kit` are you using?

0.19.13

### Describe the Bug

Defining two tables that have the same name, but are in different schemas, will result in one of them overriding the other. As a result a migration for only one of the tables is created.
Example:
```ts
const customSchema = pgSchema('custom')

export const customTableA = customSchema.table('table_a',
	{id: uuid('id').primaryKey()}
)
export const customTableB = customSchema.table('table_b',
	{id: uuid('id').primaryKey()}
)
export const defaultTableA = pgTable('table_a',
	{id: uuid('id').primaryKey()}
)
```

Will result in migrations for the following tables:
```
table_a 1 columns 1 indexes 0 fks // in schema 'public'
table_b 1 columns 1 indexes 0 fks // in schema 'custom'
```
However there will be no migration created for `table_a` in schema 'custom'

### Expected behavior

Schema definition should result in migrations for the following tables:
```
table_a 1 columns 1 indexes 0 fks // in schema 'public'
table_a 1 columns 1 indexes 0 fks // in schema 'custom'
table_b 1 columns 1 indexes 0 fks // in schema 'custom'
```

**Comment by L-Mario564** [comment]
Fixed in latest.
