### ISSUE TITLE
Support for import aliases in drizzle-kit

### ISSUE THREAD

**Issue by sdarnell** [drizzle-team/drizzle-kit-mirror#223]
For some projects we use the helpful import aliases that typescript offers.
For example, in sveltekit, $lib maps to `src/lib` and is commonly used in imports.
In my case, my schema.ts file references some common constants in a file off $lib, and I (unwisely) had some custom column types declared in a file that also referenced other aliased paths.

When I try to create a migration I get an error like:
```
> drizzle-kit generate:sqlite

drizzle-kit: v0.19.13
drizzle-orm: v0.28.6

No config path provided, using default 'drizzle.config.ts'
Reading config file '/Users/redacted/drizzle.config.ts'
Error: Cannot find module '$db/schema'
Require stack:
- /Users/redacted/src/lib/server/db/db-helpers.ts
- /Users/redacted/src/lib/server/db/schema.ts
- /Users/redacted/node_modules/drizzle-kit/index.cjs
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/Users/redacted/src/lib/server/db/db-helpers.ts:7:25)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Module._compile (/Users/redacted/node_modules/drizzle-kit/index.cjs:8623:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Object.newLoader [as .ts] (/Users/redacted/node_modules/drizzle-kit/index.cjs:8627:13)
    at Module.load (node:internal/modules/cjs/loader:1074:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/redacted/src/lib/server/db/db-helpers.ts',
    '/Users/redacted/src/lib/server/db/schema.ts',
    '/Users/redacted/node_modules/drizzle-kit/index.cjs'
  ]
```
Ultimately, the solution/work-around for now is to separate the custom column types, and use relative import paths, but it would be good if drizzle-kit didn't need that.

It would be nice if there was way for drizzle-kit to understand import aliases. Either from the real tsconfig.json (which is complicated a little by sveltekit which uses `extends` to reference a file in `./.sveltekit/tsconfig.json` which defines the aliases:
```
{
	"compilerOptions": {
		"paths": {
			"$db": [ "../src/lib/server/db" ],
			"$db/*": [ "../src/lib/server/db/*" ],
			"$lib": [ "../src/lib" ],
			"$lib/*": [ "../src/lib/*" ]
		},
		"rootDirs": ... etc
```

Another option would be to allow path aliases to be added to `drizzle.config.ts`.

**Comment by Nick-Lucas** [comment]
Also having issues related to this in an Nx monorepo, I moved some types into a shared library for use everywhere and wanted to construct enum columns with them, but ended up having to relative import

**Comment by L-Mario564** [comment]
This should be as simple as adding `drizzle.config.ts` to the array value of the `"include"` key in `tsconfig.json`.

**Comment by sdarnell** [comment]
@L-Mario564  I don't understand how that would solve the problem.

The issue is that when drizzlekit is doing the build for migrations, it doesn't seem to use the aliases in tsconfig.json (which in svelte extends ./.svelte-kit/tsconfig.json.  If drizzle-kit were using that tsconfig.json the aliases would probably work.

It is during the drizzlekit compilation of schema.ts or any related files that reference $lib/... or $db/... (in my case) where the error.
Presumably drizzle-kit is generating a tsconfig.json to use? And presumably that isn't extending the one in the project root or the sveltekit one?
