### ISSUE TITLE
Option to specify or ask for migration name when creating one

### ISSUE THREAD

**Issue by sdarnell** [drizzle-team/drizzle-kit-mirror#225]
The developer experience of creating migrations could be improved if there was a way for us to specify what the migration name suffix should be.  Random names aren't particularly useful.
Currently we have to create the migration, then hunt around and change the filename, and then update the _journal.json file.

One improvement would be if the journal didn't include the suffix, as it can work out from the prefix number. Hence one less place to change.

But I suspect the easiest fix is to have an option to specify the name, and if not, ask on the console.

**Comment by antmarot** [comment]
Totally agree.
We currently have to look at all migration files in order to find where something was added.
eg. it's easier to find the user table creation in `create_users_table.sql` and not in `worthless_vargas.sql`

**Comment by sdarnell** [comment]
Here's the temporary solution that I now use. It is a script wrapper around `npx drizzle-kit generate:sqlite` that updates the silly name with one specified on the command line.
```sh
npx run migration:add expand_widgets
```
This in turn uses package.json script:
```json
"migration:add": "tsx scripts/migration.ts",
```
This runs platform agnostic script written in typescript, but could be a bash/zsh/perl/etc. script:
```ts
import { spawnSync } from 'node:child_process';
import { readFileSync, renameSync, writeFileSync } from 'node:fs';

const migrationsFolder = 'migrations';
const journalPath = `${migrationsFolder}/meta/_journal.json`;

function readJson(path: string) {
	const data = readFileSync(path, 'utf-8');
	return JSON.parse(data);
}

const newName = process.argv[2];
if (!newName) {
	console.error('Missing name for migration');
	process.exit(1);
}

const result = spawnSync('npx', 'drizzle-kit generate:sqlite'.split(' '));
const stdout = result.stdout.toString();
const stderr = result.stderr.toString();

process.stdout.write(stdout);
process.stderr.write(stderr);

const stdoutName = stdout.match(/Your SQL migration file . (.*\.sql)/)?.[1];
const journal = readJson(journalPath);
const journalName = `${journal.entries.at(-1)?.tag}.sql`;

if (!stdoutName || !journalName) {
	console.error('ERROR: Unable to detect new migration');
	process.exit(1);
}

if (!stdoutName.endsWith(journalName)) {
	console.error('ERROR: Mismatching migration names found');
	process.exit(1);
}

const finalName = journalName.substring(0, 5) + newName + '.sql';

console.log(`Renaming ${journalName} to ${finalName}`);
renameSync(`${migrationsFolder}/${journalName}`, `${migrationsFolder}/${finalName}`);
journal.entries.at(-1).tag = finalName.substring(0, finalName.length - '.sql'.length);
writeFileSync(journalPath, JSON.stringify(journal, null, 2));
```

In practice, it is only the last three lines that do the real work... :(

**Comment by ikhvost** [comment]
I've been following this thread with great interest, as the ability to specify migration names would indeed streamline the development workflow. I'm curious about when we might expect this feature to be added. Is there any estimated timeline for when this feature might be officially added?

**Comment by tinypell3ts** [comment]
I'm also interested in this. It will make migrations much easier.

**Comment by John-Colvin** [comment]
@sdarnell's suggestion can be improved with the following diff, allowing arguments to be passed through to generate:

```
2a3
> import { Command } from 'commander'
12c13,23
< const newName = process.argv[2];
---
> const program = new Command()
> 
> program
>     .option("--name <name>", "name for migrations file (not including numerical prefix)")
>     .helpOption(false)
>     .allowUnknownOption()
>     .allowExcessArguments()
> 
> program.parse()
> 
> const newName = program.opts().name
18c29
< const result = spawnSync('npx', 'drizzle-kit generate:sqlite'.split(' '));
---
> const result = spawnSync('npx', 'drizzle-kit generate:sqlite'.split(' ').concat(program.args));
```

**Comment by iursevla** [comment]
Bump.

**Comment by sdarnell** [comment]
There are also times when you need to answer questions during the generation of the migration, for example selecting whether to add a column or rename an existing one. So, I now spawn with stdin/out shared (not sure if windows can do this).
For simplicity it doesn't include @John-Colvin 's change, but it is trivial enough to apply on top.
```ts
import { spawnSync } from 'node:child_process';
import { readFileSync, renameSync, writeFileSync } from 'node:fs';

const migrationsFolder = 'migrations';
const journalPath = `${migrationsFolder}/meta/_journal.json`;

function readJson(path: string) {
	const data = readFileSync(path, 'utf-8');
	return JSON.parse(data);
}

const newName = process.argv[2];
if (!newName) {
	console.error('Missing name for migration');
	process.exit(1);
}

const oldJournal = readJson(journalPath);
const oldJournalName = `${oldJournal.entries.at(-1)?.tag}.sql`;

spawnSync('npx', 'drizzle-kit generate:sqlite'.split(' '), {stdio: 'inherit'});

const journal = readJson(journalPath);
const journalName = `${journal.entries.at(-1)?.tag}.sql`;

if (!journalName || journalName === oldJournalName) {
	console.error('ERROR: Unable to detect new migration');
	process.exit(1);
}

const finalName = journalName.substring(0, 5) + newName + '.sql';

console.log(`Renaming ${journalName} to ${finalName}`);
renameSync(`${migrationsFolder}/${journalName}`, `${migrationsFolder}/${finalName}`);
journal.entries.at(-1).tag = finalName.substring(0, finalName.length - '.sql'.length);
writeFileSync(journalPath, JSON.stringify(journal, null, 2));
```

Note that instead of wrapping the generation, it would be relatively simple to have a script that renames the most recent migration.  But to be honest, it seems so much more appropriate for the generation to take the name as a parameter.

**Comment by AlexBlokh** [comment]
@sdarnell @antmarot @limegorilla @iursevla @John-Colvin @tinypell3ts @ikhvost 

that's implemented with `--name=custom_suffix` for `generate` command - [see docs](https://orm.drizzle.team/kit-docs/commands#generate-migrations)

we will also add `mode=supabase` for timestamps instead of incremental index prefixes
