### ISSUE TITLE
postgres: foreign key relation to a table within a schema not working properly

### ISSUE THREAD

**Issue by hexcowboy** [drizzle-team/drizzle-kit-mirror#226]
issue described here https://github.com/drizzle-team/drizzle-orm/issues/636

seems like the patch in the comments towards the bottom fixes this. is there any way to contribute to `drizzle-kit` or is it closed source? seems like this bug could already be fixed if there was a way to commit the patch.

**Comment by L-Mario564** [comment]
Fixed in latest.
