### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by ModAllama** [drizzle-team/drizzle-kit-mirror#228]
I run that==> "Drizzle Studio is up and running on http://0.0.0.0:4983"

i get that ==>"This site can’t be reachedThe webpage at http://0.0.0.0:4983/ might be temporarily down or it may have moved permanently to a new web address.
ERR_ADDRESS_INVALID
"

**Comment by L-Mario564** [comment]
Studio no longer runs on localhost.
