### ISSUE TITLE
Generating Migrations: Update to 0.20.0 causes dropping of all tables except last declared Schema

### ISSUE THREAD

**Issue by pascalmtts** [drizzle-team/drizzle-kit-mirror#229]
**Issue Description:**

After a recent update to drizzle-kit 0.20.0, we've encountered a critical issue where generating new SQL migrations results in the unintended dropping of all tables, with the exception of the last declared schema. This behavior is unexpected and deviates from our previous migrations, where all schemas were recognized and preserved accordingly.

**Configuration:**

We are utilizing the following configuration for our migrations:

```javascript
export default defineConfig({
  schema: "./schema/*",
  out: "./drizzle",
  driver: "pg",
  dbCredentials: {
    connectionString: env.DATABASE_URL,
  },
});
```

Our schema is based on the following structure:
```
schema
├── enums
│   └── enums.ts
├── shared
│   └── timestampColumns.ts
└── tables
    ├── bookingResources.ts
    ├── bookingServices.ts
    ├── ...
```

**Expected Behavior:**

The expected behavior upon generating migrations would be the recognition of all declared schemas and the preservation of their respective tables in the database.

**Actual Behavior:**

Only the last declared schema is recognized, and as a result, only one table remains post-migration, leading to the loss of all other tables.

**Steps to Reproduce:**

Update drizzle-kit to the latest version (0.20.0).
Run the command to generate new SQL migrations.
Observe that all tables except for the last one declared in the schema are dropped.
Impact:

This issue is critically impacting our development workflow and potentially could affect our production environment if not addressed promptly.

**Additional Context:**

This problem began after updating drizzle-kit to 0.20.0.
No errors are thrown during the migration generation; the tables are simply dropped.

**Comment by ptts** [comment]
Additional info:
- We are using postgres `"drizzle-orm/pg-core"`
- All our schemas are in `schema/tables` and look like this

```ts
// schema/tables/exampleTable.ts

import { pgTable, serial } from "drizzle-orm/pg-core";

export const exampleTable = pgTable("example_table", {
  id: serial("id").primaryKey(),
  // ...
});
```

- Only the last file as ordered alphabetically is recognized by drizzle-kit. When we rename a file in `/tables` to become the new `last` file (e.g. by appending `z` to the filename), now only the containing table is recognized.

**Comment by AndriiSherman** [comment]
Looking into this one

**Comment by AndriiSherman** [comment]
Can reproduce it, will work on a fix asap

**Comment by ivomastre** [comment]
is this fixed?

**Comment by callmeberzerker** [comment]
Hitting this as well 😀

**Comment by AndriiSherman** [comment]
Going to release it today. Running last tests

**Comment by AndriiSherman** [comment]
Fixed in `drizzle-kit@0.20.2`

**Comment by AndriiSherman** [comment]
Please check and close this ticket if it works for you

**Comment by pascalmtts** [comment]
Works again, thanks!
