### ISSUE TITLE
Drizzle Studio Infinite Loading

### ISSUE THREAD

**Issue by alexbchr** [drizzle-team/drizzle-kit-mirror#230]
Using the following versions:

```
drizzle-kit: v0.20.1
drizzle-orm: v0.29.0
```

Drizzle Studio loads indefinitely on the "Open a Table" view (see below).
<img width="498" alt="image" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/3542313/4fddb4b4-f694-40c4-958e-4c32038f313b">

Everything was working fine before upgrading to the latest versions of drizzle-kit and drizzle-orm.

We have a very simple `drizzle.config.ts` file (I only changed the export to use the new `defineConfig` export, but still no luck.

```ts
export default defineConfig({
  schema: './src/db/schema.ts',
  out: './drizzle',
  driver: 'pg',
  dbCredentials: {
    connectionString: '...',
  },
})
```

**Comment by taep96** [comment]
It did work for some time after updating for me so I think it's an issue with the website

**Comment by natedunn** [comment]
Yeah, I haven't been able to access studio once, since upgrading.

**Comment by natedunn** [comment]
Worth noting that @alexbchr that there is an undocumented change that you seem to be missing. If you are using typescript it should be catching it, but `connectionString` is now `uri`.

**Comment by taep96** [comment]
> Worth noting that @alexbchr that there is an undocumented change that you seem to be missing. If you are using typescript it should be catching it, but `connectionString` is now `uri`.

The field's name depends on what driver you are using: https://orm.drizzle.team/kit-docs/config-reference#dbcredentials

**Comment by natedunn** [comment]
Strange, cause I was using `connectionString` with mysql2 and had to change it to `uri` after this update. 🤷‍♂️ maybe they "corrected" it this update

**Comment by natedunn** [comment]
Back this morning and things seems to be working. Double edged sword that it is its own site now, cause as quickly as it can be fixed, it can also be broken. @alexbchr are things working for you? If they are, we should close this.

**Comment by taep96** [comment]
Maybe make it an option to run it the old way?

**Comment by AlexBlokh** [comment]
that's fixed yesterday, please check

**Comment by alexbchr** [comment]
I can confirm this has been fixed, hopefully this does not happen again in the future... 🤞 It's cool that the Studio can be updated remotely like that, but I kind-of fear that the versioning might become tricky for the Drizzle Teams. It's gonna be hard for Drizzle users to pinpoint issues as well with their setup if at some point the Studio drops support for certain Drizzle versions. Hopefully the drizzle-kit CLI checks the versions of the Drizzle packages locally to ensure the remote Studio is compatible with those...

**Comment by AlexBlokh** [comment]
@alexbchr we've introduced API versioning, so everything will be explicitly communicated in the UI
