### ISSUE TITLE
i can't open the drizzle studio

### ISSUE THREAD

**Issue by chrhi** [drizzle-team/drizzle-kit-mirror#231]
![desktop](https://github.com/drizzle-team/drizzle-kit-mirror/assets/116351398/052de104-ef61-4976-a856-de6e4bb76af6)

this is my terminal 
dell@DESKTOP-99VVTUU MINGW64 ~/Documents/GitHub/stack-over-flow (main)
$ pnpm drizzle-kit studio --port 3000 --verbose
No config path provided, using default path
Reading config file 'C:\Users\dell\Documents\GitHub\stack-over-flow\drizzle.config.ts'

[Warning] Drizzle Studio is currently in Beta. If you find anything that is not working as 
expected or should be improved, feel free to create an issue on GitHub: https://github.com/drizzle-team/drizzle-kit-mirror/issues/new or write to us on Discord: https://discord.gg/WcRKz2FFxN

Drizzle Studio is up and running on http://0.0.0.0:3000

**Comment by chrhi** [comment]
i tried port 3000 and i get the same thing on prisma when i changed the port i solved the problem but drizzle seems to be a bit harder

**Comment by theonlyway** [comment]
You wouldn't want it running on port 3000. Depending on your local setup you might not want it running on 0.0.0.0 though which is what that error more than likely indicates. Try `drizzle-kit studio --host 127.0.0.1`

**Comment by chrhi** [comment]
thanks

**Comment by websharkdev** [comment]
Have the same issue, thanks @theonlyway
