### ISSUE TITLE
BUG: v0.20.2 push:mysql error: there can be only one auto column and it must be defined as a key

### ISSUE THREAD

**Issue by sexnine** [drizzle-team/drizzle-kit-mirror#234]
When pushing schema changes to a Planetscale database, drizzle-kit attempts to drop the primary key, resulting in an unexpected error that crashes the program and does not push schema changes.

---

- Windows 11 x64
- Node v20.8.0
- Planetscale DB
```sh
$ drizzle-kit -v

drizzle-kit: v0.20.2
drizzle-orm: v0.29.0
```

```ts
// drizzle.config.ts

import type { Config } from "drizzle-kit";
import "dotenv/config";

export default {
  schema: "shared/db-schema/schema.ts",
  driver: "mysql2",
  strict: false,
  dbCredentials: {
    uri: `${process.env.SECRET_DATABASE_URL_DK}?ssl={"rejectUnauthorized":true}`,
  },
} satisfies Config;
```

```ts
// schema.ts

import { int, mysqlTable, varchar } from "drizzle-orm/mysql-core";

export const registrationsT = mysqlTable("Registrations", {
  id: int("id").primaryKey().autoincrement(),
  eventId: varchar("eventId", { length: 20 }).notNull(),
});
```

## Reproduction Steps
1. Drop tables in database
2. `drizzle-kit push:mysql` - works as expected
```sh
$ drizzle-kit push:mysql

drizzle-kit: v0.20.2
drizzle-orm: v0.29.0

No config path provided, using default path
Reading config file 'C:\PROJECT_ROOT\drizzle.config.ts'
Reading schema files:
C:\PROJECT_ROOT\shared\db-schema\schema.ts

[✓] Changes applied
```
3. `drizzle-kit push:mysql` - subsequent pushes error like this
```sh
$ drizzle-kit push:mysql

drizzle-kit: v0.20.2
drizzle-orm: v0.29.0

No config path provided, using default path
Reading config file 'C:\PROJECT_ROOT\drizzle.config.ts'
Reading schema files:
C:\PROJECT_ROOT\shared\db-schema\schema.ts

Error: target: hackpnw.-.primary: vttablet: rpc error: code = InvalidArgument desc = Incorrect table definition; there can be only one auto column and it must be defined as a key (errno 1075) (sqlstate 42000) (CallerID: ndpdojjc6bnbmig6gvkg): Sql: "alter table Registrations drop primary key", BindVars: {REDACTED}
    at PromiseConnection.query (C:\PROJECT_ROOT\node_modules\.pnpm\drizzle-kit@0.20.2\node_modules\drizzle-kit\bin.cjs:42296:26)
    at Command.<anonymous> (C:\PROJECT_ROOT\node_modules\.pnpm\drizzle-kit@0.20.2\node_modules\drizzle-kit\bin.cjs:61038:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ER_WRONG_AUTO_KEY',
  errno: 1075,
  sql: 'ALTER TABLE `Registrations` DROP PRIMARY KEY;',
  sqlState: '42000',
  sqlMessage: 'target: hackpnw.-.primary: vttablet: rpc error: code = InvalidArgument desc = Incorrect table definition; there can be only one auto column and it must be defined as a key (errno 1075) (sqlstate 42000) (CallerID: ndpdojjc6bnbmig6gvkg): Sql: "alter table Registrations drop primary key", BindVars: {REDACTED}'
}
```

## Introspection Results
```sql
-- drizzle/0000_married_rocket_racer.sql

-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE `Registrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eventId` varchar(20) NOT NULL,
	CONSTRAINT `Registrations_id_pk` PRIMARY KEY(`id`)
);

*/
```
```ts
// drizzle/schema.ts

import { mysqlTable, mysqlSchema, AnyMySqlColumn, primaryKey, int, varchar } from "drizzle-orm/mysql-core"
import { sql } from "drizzle-orm"


export const registrations = mysqlTable("Registrations", {
	id: int("id").autoincrement().notNull(),
	eventId: varchar("eventId", { length: 20 }).notNull(),
},
(table) => {
	return {
		registrationsIdPk: primaryKey({ columns: [table.id], name: "Registrations_id_pk"}),
	}
});
```

**Comment by sexnine** [comment]
Downgrading to `drizzle-kit v0.19.3` and `drizzle-orm v0.28.6` fixes this issue for now.

**Comment by natedunn** [comment]
Adding `verbose: true` to config shows that Kit is dropping and re-adding PKs every time. Other than downgrading, the only other work around I found was dropping all tables before re-adding. Which essentially wrecks local development

**Comment by natedunn** [comment]
Found this issues as well: #216

**Comment by jakobevangelista** [comment]
downgrading is the only thing that worked for me as well

**Comment by natedunn** [comment]
I would bet that this isn't getting fixed until they finish opening sourcing Kit, as they have said that is the priority right now. And with the holidays coming up, I also expect that to slow things down a bit.

**Comment by AndriiSherman** [comment]
taking this one and #216 to be fixed in next release

**Comment by AndriiSherman** [comment]
Fixed locally. Preparing release notes and sending beta tag for tests

**Comment by AndriiSherman** [comment]
So it should be fixed on `drizzle-kit@beta` now. Please check this tag, and I would appreciate your feedback. I will release to the latest version after a few approves here

**Comment by KingXP-Pythoner** [comment]
> So it should be fixed on `drizzle-kit@beta` now. Please check this tag, and I would appreciate your feedback. I will release to the latest version after a few approves here

Can confirm this has not been fixed for me in `drizzle-kit@beta`

**Comment by AndriiSherman** [comment]
@KingXP-Pythoner what error do you see?

**Comment by KingXP-Pythoner** [comment]
You have removed the primary key from a user table without removing the auto-increment property from this table. As the database error states: 'there can be only one auto column, and it must be defined as a key. Make sure to remove auto-increment from user table

**Comment by AndriiSherman** [comment]
That's because you can't have autoincrement on columns without primaryKey constraint. You need to either remove autoincrement or bring primaryKey back

**Comment by AndriiSherman** [comment]
This issue was fixed in drizzle-kit@0.20.7

**Comment by KingXP-Pythoner** [comment]
> That's because you can't have autoincrement on columns without primaryKey constraint. You need to either remove autoincrement or bring primaryKey back

I don't have autoincrement on columns without primary key constraint. That's why this is a bug. Only the Id columns have a primarykey constraint and autoincrement on them.

**Comment by bpinney** [comment]
> Can confirm this has not been fixed for me in `drizzle-kit@beta`

I am experiencing similar behavior to @KingXP-Pythoner with drizzle-kit@0.20.7 when defining composite primary keys, though I'm not sure if it is related to the original issue.

``` javascript
// drizzle/schema.ts

const accountsTable = mysqlTable(
  "accounts",
  {
    id: serial("id").primaryKey(),
  }
);

const accountConnectionsTable = mysqlTable(
  "account_connections",
  {
    id: int("id").notNull(),
    accountId: int("account_id").notNull(),
  },
  (table) => ({
    pk: primaryKey({ columns: [table.accountId, table.id] }),
  }),
);
```

```shell
$ drizzle-kit push:mysql --config ./drizzle.config.ts

drizzle-kit: v0.20.7
drizzle-orm: v0.29.1

Custom config path was provided, using './drizzle.config.ts'
Reading config file '/Development/app/drizzle.config.ts'
Reading schema files:
/Development/app/drizzle/tables/accounts.ts

 Warning  You have removed the primary key from a accounts table without removing the auto-increment property from this table. As the database error states: 'there can be only one auto column, and it must be defined as a key. Make sure to remove autoincrement from accounts table
```

The same happens when defining a single primary key with the `extraConfig.pk` property:
``` javascript
// drizzle/schema.ts

const accountsTable = mysqlTable(
  "accounts",
  {
    id: serial("id"),
  }
  (table) => ({
    pk: primaryKey({ columns: [table.id] }),
  }),
);
```
