### ISSUE TITLE
Outdated docs: defineConfig import wrong path

### ISSUE THREAD

**Issue by egegungordu** [drizzle-team/drizzle-kit-mirror#235]
Configuration section in the drizzle-kit docs here [https://orm.drizzle.team/kit-docs/overview#configuration](https://orm.drizzle.team/kit-docs/overview#configuration) show the `defineConfig` function imported from `drizzle-kit/utils`, but this is not possible in `0.20.2`.

**Comment by jonbiemond** [comment]
Is there a way to submit a PR for the docs? Would be happy to resolve.

**Comment by L-Mario564** [comment]
Docs have been updated and the mistake was corrected.
