### ISSUE TITLE
2 deprecated subdependencies found

### ISSUE THREAD

**Issue by giacomoferretti** [drizzle-team/drizzle-kit-mirror#240]
Running `pnpm i drizzle-kit` it gives the following warning:

```
WARN  2 deprecated subdependencies found: rollup-plugin-inject@3.0.2, sourcemap-codec@1.4.8
```

This is not a bug/issue, but it's annoying :laughing:

**Comment by motopods** [comment]
Should Wrangler be an optional dependency? It might not necessarily need the D1 database.

**Comment by blefnk** [comment]
@giacomoferretti As a temporary solution:
```json
"pnpm": {
  "allowedDeprecatedVersions": {
    "rollup-plugin-inject": "3.0.2",
    "sourcemap-codec": "1.4.8"
  }
}
```

**Comment by L-Mario564** [comment]
This shouldn't be an issue in latest.
