### ISSUE TITLE
studio should works offline

### ISSUE THREAD

**Issue by nagy-nabil** [drizzle-team/drizzle-kit-mirror#243]
first of all, thank you for your efforts.

I understand that making the studio page in [https://local.drizzle.studio/](https://local.drizzle.studio/) makes pushing UI updates easier, but sometimes we work offline, and it would be great to have drizzle studio with us.
is making the studio available offline on your roadmap? like making it PWA

**Comment by skyf0l** [comment]
I'm pushing this issue.

I was frustrated trying to open the studio on the plane in vain. Honestly using the studio without internet is pretty unusual but it would be nice to have a little offline studio with drizzle-kit, like before.

**Comment by L-Mario564** [comment]
This is likely not going to be worked on anytime soon.
