### ISSUE TITLE
Drizzle Studio doesn't show all the available tables.

### ISSUE THREAD

**Issue by vkpdeveloper** [drizzle-team/drizzle-kit-mirror#247]
I was trying drizzle with better-sqlite and bun (somehow bun:sqlite is not yet support I think), I made two schemas and it's accessaible from my code and I have able to perform all the ops and everything is working fine but drizzle studio is not showing both of the tables, it only showing the latest migrated table in my case i have two tables (users and vaults) recently I created vaults and it's only visible.

### My Config
<img width="563" alt="Screenshot 2023-11-22 at 8 56 09 AM" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/45169573/e4c59c92-aa67-4bba-94fb-eb7b84aba2ab">

### Drizzle Studio
<img width="567" alt="Screenshot 2023-11-22 at 8 56 40 AM" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/45169573/fbe77365-2cde-4828-b7eb-f95d8cff37b4">

**Comment by L-Mario564** [comment]
This should be fixed in latest.
