### ISSUE TITLE
drizzle kit studio does not work when public schema has no tables

### ISSUE THREAD

**Issue by tonyxiao** [drizzle-team/drizzle-kit-mirror#250]
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/696842/d4fdbaa7-399a-4b37-bc9d-0f9143aa4135)

All of my table are in non `public` schema and this seems to trip drizzle kit up

**Comment by mkoreo** [comment]
Same issue here.
Drizzle config contains the schemaFilter option, but drizzle studio fails to show anything.

This was working a couple of months ago.

**Comment by lsemerini** [comment]
I got the same blank page when clicking filters or something like that. Resolved by clearing `localStorage`.

**Comment by kaustubhxd** [comment]
Worked by clearing localStorage as well. 
Thanks!

> I got the same blank page when clicking filters or something like that. Resolved by clearing `localStorage`.
