### ISSUE TITLE
Issue loading environment variables for Drizzle kit

### ISSUE THREAD

**Issue by zessu** [drizzle-team/drizzle-kit-mirror#251]
`process.env.SOME_PASSWORD` does not seem to work  under `orm.config.json`
Had to change from variable to string. The others seem to work 

export default {
  ...
  dbCredentials: {
    host: process.env.SOME_HOST || "localhost",
    user: process.env.SOME_USER,
    password: process.env.SOME_PASSWORD, // ===> have to change this to string to get it to work
    database: "mydatabase".
  },
} satisfies Config;

**Comment by Bogdan-101** [comment]
I believe that easiest way here to load environmental variables into drizzle config file is to use `ts` or `js` file with `dotenv` library instead of plain `json` since `json` file will not have any reference to the `process.env`. You can see how it can be done [here](https://orm.drizzle.team/kit-docs/conf#push-and-pull) (open "connection params" to see example of using `dotenv` library).

**Comment by JamesSingleton** [comment]
So I tried doing

```ts
import { type Config } from 'drizzle-kit'
import * as dotenv from 'dotenv'

dotenv.config()

export default {
  schema: './server/db/schema.ts',
  out: './drizzle',
  driver: 'mysql2',
  dbCredentials: {
    uri: process.env.DATABASE_URL as string,
  },
} satisfies Config
```

And when doing `dotenv drizzle-kit studio` I get

```
 Invalid input  Either "uri" or "host", "database" are required for database connection
```

I have to specify the actual `.env.local` in order for this to run

```
import * as dotenv from 'dotenv'

dotenv.config({
  path: '.env.local',
})
```

The [docs](https://orm.drizzle.team/kit-docs/conf/#push-and-pull) are kind of _misleading_ where `Connection URI` shows you don't need the `dotenv` library and that you only need it when using `Connection params`.

**Comment by deadcoder0904** [comment]
yes, environment variables are hard to get right when using `drizzle-kit`. see [my comment](https://github.com/drizzle-team/drizzle-kit-mirror/issues/21#issuecomment-1929133689) on a similar issue.
