### ISSUE TITLE
Move tab "x" button to left of text

### ISSUE THREAD

**Issue by ridafkih** [drizzle-team/drizzle-kit-mirror#262]
When switching contexts, it's very common to want to close out all of your tabs. This would make doing so much easier & predictable rather than engaging in a fast-paced game of whack-a-mole each time. :) 

![CleanShot 2023-12-07 at 16 51 06](https://github.com/drizzle-team/drizzle-kit-mirror/assets/9158485/e5116779-021e-4dc3-b7b5-6c70f9f36823)
![CleanShot 2023-12-07 at 16 50 27](https://github.com/drizzle-team/drizzle-kit-mirror/assets/9158485/ac1ea8d6-ee1a-480a-82e9-2b3520056126)

**Comment by Bogdan-101** [comment]
Maybe there is a shortcut to close focused studio tab? I believe adding some kind of shortcut to close current tab and a tooltip for hovering a `x` button would be a UX enhancement worth implementing.

**Comment by L-Mario564** [comment]
The Studio UI has changed since this issue was created and this issue no longer applies to the current UI.
