### ISSUE TITLE
[FEATURE]: adding a --silent, --yes or --force option to drizzle push:<driver>

### ISSUE THREAD

**Issue by Bogdan-101** [drizzle-team/drizzle-kit-mirror#263]
When applying migrations to the db you are forced to review sql code that is about to be executed in your db. Even though I love this feature I cannot see any flag for the `push` command to accept all changes without an interactive cli. This may be required on ci/cd when migrating cloud database. There is a `strict` option available but I think you cannot use this variable to skip migrations review.
My suggestions for such flag are:
`yes, silent, force, no-verify`

Also in the [docs](https://orm.drizzle.team/kit-docs/commands/#prototype--push) in the usage example there is a `--ssl` option listed but it is not present in the `push` list of commands.

**Comment by L-Mario564** [comment]
There's now a `--force` option for the `push` command: https://orm.drizzle.team/docs/drizzle-kit-push#extended-list-of-configurations.
