### ISSUE TITLE
BUG: generate:mysql outputs migration files without shema/database prefixes for unique indexes

### ISSUE THREAD

**Issue by stagr** [drizzle-team/drizzle-kit-mirror#274]
What version of drizzle-orm are you using?
0.29.2

What version of drizzle-kit are you using?
0.20.8

### Describe the Bug

Running 

`npx drizzle-kit generate:mysql`

generates migration files with non-unique indexes without schema/database prefixes:

``CREATE INDEX `some_index_name` ON `some_table` (`some_column`);``

In contrast to tables where the schema/database prefixes are present:

``CREATE TABLE `some_schema`.`some_table` ( ...);``

Note that unique indexes and primary keys are generated inside the "CREATE TABLE" statement.

### Expected behavior
I expect migration files with non-unique indexes including schema/database prefixes:

``CREATE INDEX `some_index_name` ON `some_schema`.`some_table` (`some_column`);``

### Environment & setup
Node v21.5.0
MacOS Sonoma 14.0
MySQL 8.2.0-1.el8

**Comment by L-Mario564** [comment]
Multiple schemas/databases are no longer handled by Kit.
