### ISSUE TITLE
Introspect error

### ISSUE THREAD

**Issue by pencilcheck** [drizzle-team/drizzle-kit-mirror#277]
```
drizzle-kit: v0.20.9
drizzle-orm: v0.29.2

No config path provided, using default path
Reading config file '/drizzle.config.ts'
(node:70457) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
[✓] 69  tables fetched
[✓] 510 columns fetched
[✓] 9   enums fetched
[✓] 0   indexes fetched
[✓] 15  foreign keys fetched

/node_modules/drizzle-kit/bin.cjs:4239
      const tables = Object.values(schema4.tables);
                                           ^

TypeError: Cannot read properties of undefined (reading 'tables')
    at schema (/node_modules/drizzle-kit/bin.cjs:4239:44)
    at writeResult (/node_modules/drizzle-kit/bin.cjs:15202:21)
    at Command.<anonymous> (/node_modules/drizzle-kit/bin.cjs:63497:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.10.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by lxia1220** [comment]
writeResult was changed to accept an object as an argument, but this was not applied to introspect. (migrate functions are using correctly)

<img width="1228" alt="image" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/43934024/cac9c03b-f61e-420e-8d21-32df9a635e93">

you can temp fix it with the code below. 

```js
    writeResult({
      cur: schema4,
      sqlStatements,
      journal,
      _meta,
      outFolder: validatedConfig.out,
      breakpoints: validatedConfig.breakpoints,
      type: "introspect"
    });
   ```

**Comment by pencilcheck** [comment]
> writeResult was changed to accept an object as an argument, but this was not applied to introspect. (migrate functions are using correctly)
> 
> <img alt="image" width="1228" src="https://private-user-images.githubusercontent.com/43934024/293488498-cac9c03b-f61e-420e-8d21-32df9a635e93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNDcxMzQsIm5iZiI6MTcwNDA0NjgzNCwicGF0aCI6Ii80MzkzNDAyNC8yOTM0ODg0OTgtY2FjOWMwM2ItZjYxZS00MjBlLThkMjEtMzJkZjlhNjM1ZTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE4MjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMzhkNzhkNGQ4N2NlMTg1OTQxNTI5NmRjNzk0NzNlZmM5NzM0MGFhNDVkZjFhMmY1MzM1ZDg1ZWFlNmUzNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._iRm6ZrLIMNM0Kt12nS1yrh_Z18nSVLiE-Hg7W48FME">
> you can temp fix it with the code below.
> 
> ```js
>     writeResult({
>       cur: schema4,
>       sqlStatements,
>       journal,
>       _meta,
>       outFolder: validatedConfig.out,
>       breakpoints: validatedConfig.breakpoints,
>       type: "introspect"
>     });
> ```

Thanks. Do you know the rough version number that this fix might be merged in? Or is it not planned? Seeing this error always makes it uneasy when making instropsect

**Comment by lxia1220** [comment]
i used this patch for 0.20.8

```diff
diff --git a/bin.cjs b/bin.cjs
index 27ca3175a6169a152137049c2e83514b24ac280e..60ec88391ff0b2d31b85b5c44d4c5f26e82ae0f3 100755
--- a/bin.cjs
+++ b/bin.cjs
@@ -16075,8 +16075,8 @@ var init_sqlgenerator = __esm({
           statement.new
         );
         const tableNameWithSchema = statement.schema ? `"${statement.schema}"."${statement.tableName}"` : `"${statement.tableName}"`;
-        return `ALTER TABLE ${tableNameWithSchema} DROP CONSTRAINT ${statement.oldConstraintName};
-${BREAKPOINT}ALTER TABLE ${tableNameWithSchema} ADD CONSTRAINT ${statement.newConstraintName} PRIMARY KEY(${newColumns.join(",")});`;
+        return `ALTER TABLE ${tableNameWithSchema} DROP CONSTRAINT "${statement.oldConstraintName}";
+${BREAKPOINT}ALTER TABLE ${tableNameWithSchema} ADD CONSTRAINT "${statement.newConstraintName}" PRIMARY KEY(${newColumns.join(",")});`;
       }
     };
     MySqlAlterTableCreateCompositePrimaryKeyConvertor = class extends Convertor {
@@ -19529,8 +19529,8 @@ var init_introspect_pg = __esm({
         statement += `		${idxKey}: `;
         statement += it.isUnique ? "uniqueIndex(" : "index(";
         statement += `${escapedIndexName})`;
-        statement += `.on(${it.columns.map((it2) => `table.${withCasing(it2, casing)}`).join(", ")}),`;
-        statement += `
+        statement += `.on(${it.columns.map((it2) => `table.${withCasing(it2, casing)}`).join(", ")})`;
+        statement += `,
 `;
       });
       return statement;
@@ -19545,7 +19545,7 @@ var init_introspect_pg = __esm({
           return `table.${withCasing(c, casing)}`;
         }).join(", ")}]${it.name ? `, name: "${it.name}"` : ""}}`;
         statement += ")";
-        statement += `
+        statement += `,
 `;
       });
       return statement;
```

**Comment by lxia1220** [comment]
> > writeResult was changed to accept an object as an argument, but this was not applied to introspect. (migrate functions are using correctly)
> > <img alt="image" width="1228" src="https://private-user-images.githubusercontent.com/43934024/293488498-cac9c03b-f61e-420e-8d21-32df9a635e93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNDcxMzQsIm5iZiI6MTcwNDA0NjgzNCwicGF0aCI6Ii80MzkzNDAyNC8yOTM0ODg0OTgtY2FjOWMwM2ItZjYxZS00MjBlLThkMjEtMzJkZjlhNjM1ZTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE4MjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMzhkNzhkNGQ4N2NlMTg1OTQxNTI5NmRjNzk0NzNlZmM5NzM0MGFhNDVkZjFhMmY1MzM1ZDg1ZWFlNmUzNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._iRm6ZrLIMNM0Kt12nS1yrh_Z18nSVLiE-Hg7W48FME">
> > you can temp fix it with the code below.
> > ```js
> >     writeResult({
> >       cur: schema4,
> >       sqlStatements,
> >       journal,
> >       _meta,
> >       outFolder: validatedConfig.out,
> >       breakpoints: validatedConfig.breakpoints,
> >       type: "introspect"
> >     });
> > ```
> 
> Thanks. Do you know the rough version number that this fix might be merged in? Or is it not planned? Seeing this error always makes it uneasy when making instropsect

I still don't know when drizzle-kit will reflect this. I am using pnpm patch to fix several errors.

**Comment by AndriiSherman** [comment]
will be fixed today

**Comment by AndriiSherman** [comment]
should be fixed in `drizzle-kit@beta`. Can you check it please?

**Comment by nazif786** [comment]
> should be fixed in `drizzle-kit@beta`. Can you check it please?

it's fixed now

**Comment by AndriiSherman** [comment]
Fixed in `drizzle-kit@0.20.10`

**Comment by pencilcheck** [comment]
I will try once I have the opportunity. I am glad someone else is confirming.

**Comment by arshia-gh** [comment]
Hi, I'm getting the following error when I try to push a change.

```
if (unsquashed.columns.length === 1 && currentSchema.tables[statement.tableName].columns[unsquashed.columns[0]].type === "serial" && prevSchema.tables[statement.tableName].columns[unsquashed.columns[0]].type === "serial" && currentSchema.tables[statement.tableName].columns[unsquashed.columns[0]].name === unsquashed.columns[0]) {

TypeError: Cannot read properties of undefined (reading 'type')
```


I'm trying to push a change from:
```ts
export const documents = mysqlTable('documents', {
	url: varchar('url', { length: 255 }).primaryKey(),
	name: varchar('name', { length: 255 }).notNull(),
	description: varchar('description', { length: 255 }),
	createdAt: timestamp('created_at', { mode: 'date', fsp: 6 }).defaultNow()
});
```

to the following:

```ts
export const documents = mysqlTable('documents', {
	name: varchar('name', { length: 255 }).primaryKey(),
	description: varchar('description', { length: 255 }),
	createdAt: timestamp('created_at', { mode: 'date', fsp: 6 }).defaultNow()
});
```
