### ISSUE TITLE
Typo in custom migration file,

### ISSUE THREAD

**Issue by Neeraj319** [drizzle-team/drizzle-kit-mirror#291]
When i generate custom migrations using the command
`drizzle-kit generate:pg --custom`

There is a typo with in the generated migration file. 

```sql
-- Custom SQL migration file, put you code below! --

```

drizzle-kit version: 0.20.12

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/3384.
