### ISSUE TITLE
[BUG]: Drizzle kit with Postgres does not create hash indexes

### ISSUE THREAD

**Issue by nklisch** [drizzle-team/drizzle-kit-mirror#292]
### What version of drizzle-orm are you using?
0.29.3

### What version of drizzle-kit are you using?
0.20.12

### Describe the Bug
With the below piece of code, I'd expect the index_sessions_on_session_id index to be of type HASH, but the generated SQLs do not have the type, hence defaulting to BTREE.

```typescript
export const sessions = pgTable(
  "sessions",
  {
    sessionId: uuid("id").primaryKey().defaultRandom().notNull(),
    userId: bigint("user_id", { mode: "number" })
      .notNull()
      .references(() => users.id),
    permissions: jsonb("data").default({}).notNull().$type<Permission[]>(),
    updatedAt: timestamp("created_at", { mode: "string" })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("updated_at", { mode: "string" })
      .defaultNow()
      .notNull(),
  },
  (table) => {
    return {
      indexSessionsOnSessionId: uniqueIndex("index_sessions_on_session_id")
        .on(table.sessionId)
        .using(sql`hash`),
    };
  }
);
```

### Expected behavior
Expected generated SQL to be –

```sql
CREATE UNIQUE INDEX IF NOT EXISTS "index_sessions_on_session_id" ON "sessions" ("sessionId") USING HASH ("sessionId");
``` 

but instead it is –

```sql
CREATE UNIQUE INDEX IF NOT EXISTS "index_sessions_on_session_id" ON "sessions" ("sessionId");
```
### Environment & setup
Node.js server-side, with PostgreSQL and the postgres.js driver.

**Comment by L-Mario564** [comment]
Drizzle Kit and ORM now both fully support indexes. If you have any issues after upgrading, feel free to report it in the main repo: https://github.com/drizzle-team/drizzle-orm/issues.
