### ISSUE TITLE
`drizzle-kit drop` command requires 'out' parameter despite documentation

### ISSUE THREAD

**Issue by nmwur** [drizzle-team/drizzle-kit-mirror#293]
`drizzle-kit drop` command requires 'out' parameter despite [documentation](https://orm.drizzle.team/kit-docs/commands#drop-migration):

`Err: 'out' folder param must be set through '--out' param or in config file`.

Probably needs documentation update or command adjustment.

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/3386.
