### ISSUE TITLE
Postgres introspection incorrect on  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY

### ISSUE THREAD

**Issue by galaczi** [drizzle-team/drizzle-kit-mirror#297]
drizzle-kit: v0.20.13
drizzle-orm: v0.29.3

Take this simple table in Posgres:

```
CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL
);
```

After introspection Kit creates this schema:

```
export const roles = pgTable("roles", {
	id: integer("id").primaryKey().notNull(),
	name: varchar("name").notNull(),
});
```
  This is incorrect, since ids are generated automatically. Should I just use sql serial type?

**Comment by L-Mario564** [comment]
Generated columns are now supported in both ORM and Kit.
