### ISSUE TITLE
timestamp is not in the import statement in schema.ts

### ISSUE THREAD

**Issue by capaj** [drizzle-team/drizzle-kit-mirror#3]
Today I used `drizzle-kit introspect:pg --out=migrations/ --connectionString=postgresql://user:pass@host:port/db_name` on my current work project and wow, it's so fast. It generated 2k of TS code in couple hundred miliseconds. Nicely done. Much faster than prisma again.
I bumped into this though:

![image](https://user-images.githubusercontent.com/1305378/216294948-7e0c3ed8-8250-4680-9305-a698ef0faa51.png)

I would expect the generated `schema.ts` file to be free from type errors.
I can provide the full output and migration sql file if needed.

**Comment by AndriiSherman** [comment]
Fixed in [0.17.0](https://github.com/drizzle-team/drizzle-kit-mirror/releases/tag/v0.17.0)
