### ISSUE TITLE
[BUG]: Not able to make a selection on the terminal between created or renamed

### ISSUE THREAD

**Issue by techgerm** [drizzle-team/drizzle-kit-mirror#300]
### What version of `drizzle-orm` are you using?

v0.28.6

### What version of `drizzle-kit` are you using?

0.19.13

### Describe the Bug

When I'm prompted to select between "table created or renamed from another column?" I am unable to make a selection.

Please reference the attached video:

https://github.com/drizzle-team/drizzle-kit-mirror/assets/38846104/c9ed9db6-bca4-4f98-b296-81ab6fb94e64

Initially, this felt like a local issue so I tried all sorts of potential fixes and nothing worked. I'm now wondering if other folks are experiencing this issue as well?

### Expected behavior

I should be able to select between created or renamed to generate a migration.

### Environment & setup

macOS: Sonoma 14.2.1
zsh terminal

**Comment by israelcrux** [comment]
Experiencing the exact same same issue
```
drizzle-kit: v0.19.13
drizzle-orm: v0.28.6
```

**Comment by goncalomp** [comment]
@techgerm From the video you posted you appear to be using the nx workspace.
There is an issue with their cli commands that was already merged but is yet to be released. I think your problem might be related to that. https://github.com/nrwl/nx/pull/21195
In any case you should try to run the command without using nx
