### ISSUE TITLE
Unclear error when no DB connection is setup and trying to run migrations

### ISSUE THREAD

**Issue by MarkSFrancis** [drizzle-team/drizzle-kit-mirror#308]
I'm currently using `drizzle-kit` with D1 and attempted to use `drizzle-kit up:sqlite` to sync to the D1 database. Because D1 has no connection string, `drizzle-kit` couldn't publish the migrations. However, instead of telling me that, it simply printed "Everything's fine 🐶🔥" and then exited with a `0` status code (indicating success). 

![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/16414147/d07c8c89-f082-456d-9dde-9c876a071611)

`drizzle.config.ts`:
```ts
import type { Config } from 'drizzle-kit';

export default {
  schema: './src/db',
  out: './migrations',
} satisfies Config;
```

This makes debugging hard. I can't tell whether the migrations were ran or not and if not then what I need to do to get them to run.

Ideally, I'd like to see an error status code if credentials are not configured and therefore no migrations could be synced. Or more specifically to D1, I'd love to see some docs for the fact that I need to update via the Cloudflare wrangler CLI instead (e.g. "Did you mean `npx wrangler db migrations apply {db_name}`?")

**Comment by multiplehats** [comment]
Came here with the same problem. I couldn't figure out why this error was happening!

**Comment by L-Mario564** [comment]
Drizzle Kit has improved its documentation, you can read about `up` here: https://orm.drizzle.team/docs/drizzle-kit-up. Syncing the DB isn't `up`'s purpose.
