### ISSUE TITLE
✨Feature: allow customizing introspect pg date type (don't default to string)

### ISSUE THREAD

**Issue by alan-funded** [drizzle-team/drizzle-kit-mirror#313]
Right now, when you introspect, PG dates default to `{ mode: 'string' }`, but if you want `{ mode: 'date' }` you have to go in and edit by hand.

Unless I'm missing something?

**Comment by sfsr12** [comment]
I am also facing this issue and not sure the solution besides manually fixing the schema each pull or just using strings?

**Comment by sfsr12** [comment]
For future people finding this like I did.  Until it is added to drizzle-kit - this is my workaround:

``` json5
// package.json
{
  "scripts": {
    "db:pull": "drizzle-kit pull  && sed -ie \"s/{ mode: 'string' }/{ mode: 'date' }/g\" ./src/db/schema.ts"
  }
}
```

Basically just add a very sketchy sed after the schema is pulled.

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/3239.
