### ISSUE TITLE
BUG: Empty array is not reflected as a valid default value in migration

### ISSUE THREAD

**Issue by shabashab** [drizzle-team/drizzle-kit-mirror#314]
At the moment I have a field in my table:

```js
tags: text('tags').array().default([]).notNull()
```

The typescript definition does not mark this as invalid, but when running `drizzle-kit generate:pg` the output migration creates invalid definition of the column:

```sql
"tags" text[] DEFAULT  NOT NULL
```

This leaves an empty space instead of an actual default value.

Possible fix is to generate an empty array definition of the type that is required, for example:

```sql
"tags" text[] DEFAULT array[]::text[] NOT NULL
```

**Comment by L-Mario564** [comment]
This should be fixed in latest.
