### ISSUE TITLE
Drizzle studio not opening 

### ISSUE THREAD

**Issue by fmchisti** [drizzle-team/drizzle-kit-mirror#315]
When I run studio 

Hey 👋
Welcome to Drizzle Studio
Connecting to the Drizzle Kit on localhost:4983

it showing me that screen. 

My config 

import type { Config } from "drizzle-kit";
import { env } from "./src/config/env";

import * as dotenv from "dotenv";
dotenv.config();

export default {
  schema: "./src/db/schema/index.ts",
  out: "./migrations",
  driver: "pg",
  dbCredentials: {
    connectionString: env.DATABASE_CONNECTION,
  },
  verbose: true,
  strict: true,
} satisfies Config;
 
 
 Also, I tried to use a direct process.env 
 
 Same issue 
 
 //
 
Note: My schema is not I one file. its  different files but I export from the index.ts 

 export {
  applications,

  // user
  users,
  profile,
  roles,
  userToRole,

  // For billing
  billings,
  packages,
  transactions,

  // Theme table
  themeMarket,
  activeTheme,

  // Login Theme table
  activeLoginThemes,
  loginThemes,
};

**Comment by LModipane** [comment]
try to be specific which file your environment variables are loading from by modifying the .config() function to:
ex:
`dotenv.config({ path: '.env.development.local' })`

This should load your credential directly into the file.

**Comment by L-Mario564** [comment]
Studio no longer runs on localhost. This issue should be fixed in the latest version.
