### ISSUE TITLE
Provide `drizzle-kit migrate:sqlite` command to simplify Dockerfile process?

### ISSUE THREAD

**Issue by deadcoder0904** [drizzle-team/drizzle-kit-mirror#318]
I have been trying to get Drizzle working with Docker but no luck.

Every other framework has solutions for it but Drizzle lacks them.

I think what Drizzle Kit needs is a solution provided in these 2 blogs:

1. https://notiz.dev/blog/dockerizing-nestjs-with-prisma-and-postgresql
2. https://notiz.dev/blog/prisma-migrate-deploy-with-docker

The example is Prisma with Nestjs but it probably would work with Drizzle & Next.js.

I've been trying for a week to get Docker running on my simple SQLite + Next.js project but so far have been unsuccessful.

Part of the reason is Drizzle doesn't provide direct migrate command but instead wants me to rely on `tsx` which again breaks the build near the end as Dockerfile can't find `tsx` at the end.

Smallest Reproduction -> https://github.com/deadcoder0904/easypanel-nextjs-sqlite

This project works well in Development & would definitely work well in Production if I can get the migrate command.

Currently, I can think of only 1 solution:

1. Use bun.sh (as a `tsx` replacement) but it won't be available on Windows until 1 or 2 weeks anyways.

If there's any other solutions that anyone got Drizzle Migrations working with SQLite on a Next.js app, I'd love to know? I've found a couple of projects on Github but they do it in a very complicated manner.

I think the reason is because Drizzle Migrate doesn't exist as a command.

Here's how tsx fails:

```ts
> easypanel-nextjs-sqlite@0.1.0 start
> npm run db:migrate:prod && next start


> easypanel-nextjs-sqlite@0.1.0 db:migrate:prod
> node --import tsx --env-file .env.production ./scripts/drizzle-migrate.ts

node:internal/modules/esm/resolve:853
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'tsx' imported from /app/
    at packageResolve (node:internal/modules/esm/resolve:853:9)
    at moduleResolve (node:internal/modules/esm/resolve:910:20)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:328:34)
    at loadESM (node:internal/process/esm_loader:23:33)
    at runMainESM (node:internal/modules/run_main:98:21)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:131:5) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.11.1
```

This is inside `Dockerfile` otherwise I would've installed `tsx` locally. I've also installed in dependency instead of devDependency.

**Comment by L-Mario564** [comment]
A `migrate` command is now available in Kit: https://orm.drizzle.team/docs/drizzle-kit-migrate.
