### ISSUE TITLE
Drizzle Studio not showing anything

### ISSUE THREAD

**Issue by dewdadim** [drizzle-team/drizzle-kit-mirror#326]
I run test project to view and play around with drizzle studio. For the first time, it did show all the UI and the data just like normal... But once I try to change the table view by untick the id column of my table, it is not working after the page reloaded. It did not show up anything. I have also tried empty cache and hard reload, but it is still not showing anything. 

I wonder if there is any way to fix this? Thank you

![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/118960850/bcf66313-8afd-4337-b5c1-9a028b4e3971)

**Comment by amit13k** [comment]
I ran into the same problem when i accidently deselected all columns. As a workaround, I cleared the local storage entries for https://local.drizzle.studio/ to fix the issue.
