### ISSUE TITLE
Drizzle-kit introspect generates invalid schema.ts for MySQL column names starting with a number

### ISSUE THREAD

**Issue by amit13k** [drizzle-team/drizzle-kit-mirror#327]
MySQL introspection generates an invalid schema.ts when column names start with a number. MySQL permits column names to begin with a number, but drizzle-kit produces a schema.ts with object property names that start with a number, which JavaScript does not allow.

I understand that it may not be best practice to name columns starting with numbers but it would be beneficial if drizzle-kit could handle this edge case more robustly.

**Comment by L-Mario564** [comment]
This should be fixed in latest.
