### ISSUE TITLE
DEFAULT now() with a time zone creates an invalid schema

### ISSUE THREAD

**Issue by tmcw** [drizzle-team/drizzle-kit-mirror#33]
We have a table like this:

![CleanShot 2023-04-10 at 15 29 47@2x](https://user-images.githubusercontent.com/32314/230981491-7f7dfcff-135b-4d83-b26f-4c1e203dcb8b.png)

And it generates a schema like this:

```ts
export const timeoutLocks = pgTable("timeout_locks", {
	acquiredAt: timestamp("acquiredAt", { withTimezone: true, mode: 'string' })
        .default((now() AT TIME ZONE 'utc'::text)),
	id: uuid("id").notNull(),
},
(table) => {
	return {
		idKey: uniqueIndex("timeout_locks_id_key").on(table.id),
	}
});
```

With the line

```
        .default((now() AT TIME ZONE 'utc'::text)),
```

Being an issue - this is invalid JavaScript. Seems like there's special handling of default: now(), while other defaults get expressions with the sql helper, and this is stuck in the middle.

**Comment by JustMrMendez** [comment]
having a similar problem
```ts
export const account = pgTable("account", {
	id: text("id").default(nextval('users_id_seq'::regclass)).primaryKey().notNull(),
	...
	requestDate: date("request_date").default(CURRENT_DATE).notNull(),
```

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3245.
