### ISSUE TITLE
feature request: command and api to make a snapshot of schema

### ISSUE THREAD

**Issue by terion-name** [drizzle-team/drizzle-kit-mirror#330]
For migrations drizzle uses snapshots based on provided schema for further diffing and migration generation

Snapshots as intermediate DL can be useful for additional tools (like prisma's model objects). Having a snapshot one can build a database diagram to visually inspect db design in progress, can make some additional types/crud/whatever code generators, etc

This already can be done for already migrated stuff, but for WIP – no. So I think it would be useful to have a cli command and an API to get only the snapshot of current schema, without writing it on disk and generating the migrations

**Comment by L-Mario564** [comment]
Drizzle Kit now exposes its api via `drizzle-kit/api`. It's currently undocumented, but you can find the source code here: https://github.com/drizzle-team/drizzle-orm/tree/main/drizzle-kit.
