### ISSUE TITLE
[BUG] Error processing absolute path

### ISSUE THREAD

**Issue by ElkostVN** [drizzle-team/drizzle-kit-mirror#331]
**What version of `drizzle-orm` are you using?** - `0.30.1`
**What version of `drizzle-kit` are you using?** - `0.20.14`

**Environment & Setup**:
MacOS Sonoma 14.2.1

**Describe the Bug:**
When using the absolute path in the `drizzle.config.ts` migration generator throws an error if there is a `snapshot.json` in meta.
Error: `Error: ENOENT: no such file or directory, open './/Users/User/<project>/<service>/src/services/database/migrations/meta/0000_snapshot.json'`

The error occurs in the file `utils.js` inside the `validateWithReport' function. 

Line:
const raw = JSON.parse((0, import_fs4.readFileSync)(`./${it}`).toString());

**Expected behavior:**
For absolute paths, the path should be passed unmodified to the file-reading function.

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/3217.
