### ISSUE TITLE
MySQL migration produce statements in the wrong order

### ISSUE THREAD

**Issue by valentin0h** [drizzle-team/drizzle-kit-mirror#334]
Having a very similar issue to https://github.com/drizzle-team/drizzle-kit-mirror/issues/45

The following code change
```typescript
mysqlTable(
     {
         id: serial('id').primaryKey(),

+        publicId: varchar('public_id', { length: 100 }).unique().notNull(),
+
         otherId: varchar('other_id', { length: 100 }).notNull(),

```

generates this migration file

```sql
ALTER TABLE `content_references` ADD CONSTRAINT `content_references_public_id_unique` UNIQUE(`public_id`);--> statement-breakpoint
ALTER TABLE `content_references` ADD `public_id` varchar(100) NOT NULL;%    
```

Env:

drizzle-kit 0.20.14
drizzle-orm 0.29.4
MySQL (PlanetScale)

**Comment by amit13k** [comment]
I am facing the same issue. The statement for the unique constraint is generated before the column creation statement in the migration file.

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/3329.
