### ISSUE TITLE
Drizzle Kit config option as unknown

### ISSUE THREAD

**Issue by nvegater** [drizzle-team/drizzle-kit-mirror#336]
This doesn't work:

```
pnpm drizzle-kit --config=./dbconfig/preview.config.json generate:pg
error: unknown option '--config=./dbconfig/preview.config.json'
```

BUT when using dotenv, it works but it ignores the config option completely, uses default:

```
pnpm dotenv drizzle-kit --config=./dbconfig/preview.config.json generate:pg
drizzle-kit: v0.20.14
drizzle-orm: v0.29.4

No config path provided, using default 'drizzle.config.ts'
Reading config file '/Users/nterraza/js-dev/gridlink/drizzle.config.ts'
```

```
    "drizzle-kit": "^0.20.14",
    "drizzle-orm": "^0.29.4",
```

Having different configs is important to have different DB's for Testing and Production. I have a workaround where I edit the drizzle config based on env variables but its less maintainable like that. 

Thanks for the cool library!

**Comment by asashay** [comment]
Doesn't work for me as well. I have hundreds of DBs (SQLite) with the same schema and this is a blocker for me

**Comment by asashay** [comment]
I had the same issue, for me worked `pnpm drizzle-kit push:sqlite --config=./path-to-config.ts`. 

Basically `config` is an option for commands and not `drizzle-kit` itself
