### ISSUE TITLE
Drizzle studio has my old schema for its query "Drizzle Runner" ?

### ISSUE THREAD

**Issue by dBianchii** [drizzle-team/drizzle-kit-mirror#337]
For some reason, when I launch Drizzle studio, it is displaying a schema that no longer exists anywhere on my code.
I recently renamed all of my tables to uppercase for example, and changed multiple column types multiple times.

What drizzle studio sees:
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/17372417/59297a22-87d0-4d0d-878f-bc131f42544f)

My real schema
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/17372417/f5b695a6-653d-4e3d-a527-c53236be3926)

I have tried completely cleaning all of my node_modules and cache files. It's very strange because this schema doesn't exist on my setup anymore. What's going on?

![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/17372417/13cec81f-94da-418e-92bc-feec2dbebaaa)
Running either of these ^ doesn't work.

**Comment by stefanosandes** [comment]
Same problem here. In my case, it is showing old columns that I renamed.

**Comment by stefanosandes** [comment]
Hey @RomanNabukhotnyi, thanks for the response 🙏, you are completely right. In my case, the problem was that I renamed the schema object, but not the mapping name. I think an option to rely on the property name as the column name with case transformation options will be very useful.
