### ISSUE TITLE
`push:sqlite` - dropping indexed column triggers move data statements

### ISSUE THREAD

**Issue by mattfysh** [drizzle-team/drizzle-kit-mirror#339]
Given the following `schema.ts`

```ts
export const t = sqliteTable(
  't',
  {
    c: text('c'),
  },
  t => ({
    idx: index('idx').on(t.c),
  })
)
```

If you were to update the name of the column to `'c2'` then run `push:sqlite --verbose` you'll see these statements are executed:

```sql
DROP INDEX IF EXISTS `idx`;
ALTER TABLE t ADD `c2` text;
CREATE INDEX `idx` ON `t` (`c2`);
ALTER TABLE `t` RENAME TO `__old_push_t`;
CREATE TABLE `t` (
	`c2` text
);

DROP TABLE `__old_push_t`;
CREATE INDEX `idx` ON `t` (`c2`);
```

The `moveDataStatements()` function does not need to be triggered in this scenario. This is not a problem for `generate:sqlite` which produces the first 3 statements followed by a single `ALTER TABLE t DROP COLUMN c`

By looking into the drizzle-kit source code, it appears to be triggered by this check:

```ts
if (columnIsPk || columnIsPartOfPk || columnIsPartOfIndex || columnIsPartOfFk) {
  tablesContext[newTableName] = [
    ..._moveDataStatements(statement.tableName, json2, true)
  ];
```

The only truthy value in the condition is `columnIsPartOfIndex` which doesn't sound correct - because the index it's referring to is dropped in the very first statement of the set.

**Comment by L-Mario564** [comment]
Migrations for SQLite have been enhanced since this issue was created. If you encounter any issues with it, feel free to report it over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues.
