### ISSUE TITLE
`migrate` silently fails on migration error

### ISSUE THREAD

**Issue by bddvlpr** [drizzle-team/drizzle-kit-mirror#341]
When using the automatic migration runner, in my case the vercel-postgres one, if for some reason the generated migrations fail nothing will be outputted or returned. The output of the migrate function should be checked for thrown errors or at least be returned so it can be handled individually by developers.
```js
import { readMigrationFiles } from "../migrator.js";
async function migrate(db, config) {
  const migrations = readMigrationFiles(config);
  await db.dialect.migrate(migrations, db.session, config); // <---
}
export {
  migrate
};
//# sourceMappingURL=migrator.js.map
```

**Comment by L-Mario564** [comment]
We'll keep track of this over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3214.
