### ISSUE TITLE
Drizzle Studio Sidebar doesn't sync number count in the sidebar when refreshed

### ISSUE THREAD

**Issue by deadcoder0904** [drizzle-team/drizzle-kit-mirror#346]
If my sidebar user table has 1 row, it shows has `user (1)` but if i add it & refresh it, then it gets updated only in the center (right side), not sidebar (left side)

I think if you use `react-query`, this fixes itself automatically assuming you are using React for Drizzle Studio.

**Comment by L-Mario564** [comment]
This should be fixed in newer versions of Studio.
