### ISSUE TITLE
When you try to create a record in studio, and it fails, there is a flash of ui (I assume an error message) and the state of the partial record is lost. 

### ISSUE THREAD

**Issue by swalker326** [drizzle-team/drizzle-kit-mirror#348]
As the title says, if I try to insert a record and don't put all the required fields/incorrect types. I see a flash of the error message and then all my fields are wiped away. 

I think ideally, I would see the whole error message and the incorrect inputs with the values I typed would still be there so I could edit/retry. 

_As a side note, the gif also shows a slightly annoying bug, when I type a value into a field and press enter the value just vanishes._

![aa812a44-40b1-4a2f-8a33-403c5cf9c985](https://github.com/drizzle-team/drizzle-kit-mirror/assets/8460808/8496f574-24af-4af9-ab4a-8602f62572d3)

**Comment by L-Mario564** [comment]
This should fixed in newer versions of Studio.
