### ISSUE TITLE
Support for PostgreSQL PostGIS with DB push

### ISSUE THREAD

**Issue by nrdobie** [drizzle-team/drizzle-kit-mirror#350]
When attempting to use the PostgreSQL PostGIS `geometry` data type, `drizzle-kit` will currently quote it and break the ability to use DB push.

This is the custom type I am trying to use:

```typescript
import { customType } from "drizzle-orm/pg-core";

export type Point = {
  longitude: number;
  latitude: number;
};

export const point = customType<{
  data: Point;
  driverData: string;
}>({
  dataType() {
    return "geometry(point, 4326)";
  },
  toDriver(value: Point): string {
    return `SRID=4326;POINT(${value.longitude} ${value.latitude})`;
  },
  fromDriver(value: string): Point {
    const matches = value.match(
      /POINT\((?<longitude>[\d.-]+) (?<latitude>[\d.-]+)\)/,
    );

    if (!matches) {
      throw new Error("Invalid point format");
    }

    const { longitude, latitude } = matches.groups as {
      longitude: string;
      latitude: string;
    };

    return {
      longitude: parseFloat(longitude),
      latitude: parseFloat(latitude),
    };
  },
});
```

This is the generated SQL:

```sql
CREATE TABLE IF NOT EXISTS "location_test" (
	"id" varchar(24) PRIMARY KEY NOT NULL,
	"name" varchar(256) NOT NULL,
	"location" "geometry(point, 4326)" NOT NULL
);
```

The issue comes specifically from this line in the Drizzle Kit code:

```typescript
const type = isPgNativeType(column7.type) ? column7.type : `"${column7.type}"`;
```

Either extend `isPgNativeType` to include geometry as a native type or add support for using the `sql` or `sql.raw` as part of the `dataType` return.

```typescript
export const point = customType<{
  data: Point;
  driverData: string;
}>({
  dataType() {
    return sql.raw`geometry(point, 4326)`;
  },
  // ...
});
```

This would make using drizzle with geospatial data usable.

**Comment by imoshimuir** [comment]
I'm also experiencing this issue e.g the generate SQL looks like:
`CREATE TABLE IF NOT EXISTS "my_table" (
	"areas" "geometry(Polygon,4326)"
)
with geometry in quotations

**Comment by Schmavery** [comment]
It looks like drizzle-kit 0.22 has added `"geometry("` to the list of `pgNativeTypes` string prefixes.
This doesn't let you use "geometry" on its own as a type, but maybe there's a way to work around that on the sql side?

**Comment by L-Mario564** [comment]
Postgis extension is now officially supported in both ORM and Kit.
