### ISSUE TITLE
`d1` driver setting gives: Either "turso", "libsql", "better-sqlite" are available options for "--driver"

### ISSUE THREAD

**Issue by marceloverdijk** [drizzle-team/drizzle-kit-mirror#351]
Using `"drizzle-kit": "^0.20.14"`

and the following config file:

```
import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  schema: './src/model/schema.ts',
  out: './drizzle',
  driver: 'd1',
  dbCredentials: {
    wranglerConfigPath: 'wrangler.toml',
    dbName: 'f1db',
  },
});
```

and running the following npm script:
```
"generate-drizzle-schema": "drizzle-kit introspect:sqlite --config=drizzle.codegen.ts",
```

givers:

> Either "turso", "libsql", "better-sqlite" are available options for "--driver"

It seems the `d1` driver setting is not recognised as valid setting, although documented here:
https://orm.drizzle.team/kit-docs/config-reference#driver

**Comment by marceloverdijk** [comment]
I've created [this](https://github.com/marceloverdijk/graphql-codegen-mapper) small repo, reproducing the issue.

**Comment by L-Mario564** [comment]
The behavior of the `driver` param has changed since this was created. Refer to the docs on how to specify your desired driver.
