### ISSUE TITLE
[Question] Where is the source code?

### ISSUE THREAD

**Issue by febeling** [drizzle-team/drizzle-kit-mirror#354]
The README states this repo is a mirror for docs and issues, which probably means it doesn't contain code, and it doesn't afaict. But I don't find the code repository. Could someone point in the right direction to where it's hosted?

**Comment by deriegle** [comment]
`drizzle-kit` is currently closed source so it is in a private repository.

**Comment by febeling** [comment]
@deriegle thanks for your answer. Confusing they choose to put "MIT license" on the repo and the npm package as well. And the npm package obviously also contains the code ([link](https://www.npmjs.com/package/drizzle-kit?activeTab=code)).

Maybe it's more about things not being polished enough to show than keeping it under wraps? Just speculating.

**Comment by castarco** [comment]
I think these 2 details should be clearly stated in the README file.

**Comment by AndriiSherman** [comment]
> I think these 2 details should be clearly stated in the README file.
> 
> **EDIT:** According to #50 , the Drizzle team intended to open source `drizzle-kit` at some point. Sadly, it seems that at least part (if not all) of the Drizzle team is in Ukraine, which could account for the huge delay in doing so.

How is it related?
