### ISSUE TITLE
MySQL DrizzleKit generating failing ALTER TABLE statements in migrations that doesn't include schema name.

### ISSUE THREAD

**Issue by GustavLjungberg** [drizzle-team/drizzle-kit-mirror#357]
Drizzle-kit generates failing migrations on MySQL databases that includes schemas (or databases as mysql calls them) for separating tables.

After looking into the code a bit it seems that this affects these types of statements:
- DROP TABLE
- ALTER TABLE ... RENAME COLUMN
- ALTER TABLE ... DROP COLUMN
- ALTER TABLE ... ADD COLUMN
- ALTER TABLE ... ADD PRIMARY KEY
- ALTER TABLE ... DROP PRIMARY KEY
- ALTER TABLE ... ADD CONSTRAINT
- CREATE INDEX ON ...

# Steps to reproduce:

## 1
Make a table schema that includes a mysqlSchema like this for example:
```typescript
const { mysqlSchema, int } = require("drizzle-orm/mysql-core");

const schema = mysqlSchema("test");

const table = schema.table("table", {
  id: int("Id").notNull(),
});

module.exports = {
  table,
};
```
## 2
Run `drizzle-kit generate:mysql` to make an intial migration, which generates correctly including the schema name. Included here for completeness:
```sql
CREATE TABLE `test`.`table` (
	`Id` int NOT NULL
);
```

### 3
Edit the table in any way, like for example adding a column:
```diff
const { mysqlSchema, int } = require("drizzle-orm/mysql-core");

const schema = mysqlSchema("test");

const table = schema.table("table", {
  id: int("Id").notNull(),
+ foo: int("Foo").notNull(),
});

module.exports = {
  table,
};
```

## 4
Run `drizzle-kit generate:mysql` again 

# Expected result
The generated migration should contain a statement including the schema name `test` when specifying the table like this
```sql
ALTER TABLE `test`.`table` ADD `Foo` int NOT NULL;
```

# Actual result
The migration doesn't include the schema name which causes the migration to fail
```sql
ALTER TABLE `table` ADD `Foo` int NOT NULL;
```

# Versions
drizzle-kit: v0.20.14
drizzle-orm: v0.30.7
mysql2: 3.9.3

**Comment by L-Mario564** [comment]
Multiple schemas are no handled in MySQL.
