### ISSUE TITLE
Runing migrations down

### ISSUE THREAD

**Issue by JeromeBu** [drizzle-team/drizzle-kit-mirror#36]
I am wondering if there is a way to generate and run migrations down.

I see 2 common use cases :
- rolling back when something unexpected happens when deploying
- when switching between 2 branches, one might need to go back to a previous migration state

I see there is a `drop` possibility, but it won't help if the migration was actually ran, as the database has no way to go back to the wanted state.

Is it something that exists or that is in the road map ?

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/2352 over on the main repo.
