### ISSUE TITLE
Enums broken when instrospecting with schemaFilter

### ISSUE THREAD

**Issue by ViggoV** [drizzle-team/drizzle-kit-mirror#361]
I have been having some issues when instrospecting a postgres schema with enum types. The `PgEnums` are generated in the Drizzle schema, but the columns that use them get an `unknown()` type. It looks like this

```js
export const colorEnum = pgEnum('color_enum', ['red','green','blue'])

export const myDbSchema = pgSchema('my_db_schema')

export const sillyHat = myDbSchema.pgTable('silly hat', {
  id: serial('id').primaryKey(),
  // TODO: failed to parse database type 'fraud_dev.variable_type'
  color: unknown('hat')
})
```

Based on the inserted comment I believe the issue is that drizzle-kit is trying to access the enum on myDbSchema, but the actual enum is defined outside it, on the database itself.

**Comment by ldurazo** [comment]
Similar if not the same issue I'm running into, is that `colorEnum` in my case is part of `myDbSchema` but introspected as if part of the default (public) schema.

**Comment by L-Mario564** [comment]
This should be fixed in latest. If you still encounter this bug, feel free to open a new issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues.
