### ISSUE TITLE
Dashboard could not be seen with version below 0.20.15

### ISSUE THREAD

**Issue by stvncode** [drizzle-team/drizzle-kit-mirror#364]
Following threads on your discord, it looks that everybody couldn't access the dashboard. After looking at the repo, i saw that you did an update (0.20.15) who broke studio. This is just to let you know that.

**Comment by stvncode** [comment]
For anyone who has the issue, just upgrade your version : ```"drizzle-kit": "^0.20.15"```

**Comment by AndriiSherman** [comment]
Local studio will tell you about it. We need to drop the cache, so everyone will see the error

**Comment by sifengjing** [comment]
> Local studio will tell you about it. We need to drop the cache, so everyone will see the error

How to delete cache
