### ISSUE TITLE
Timestamp values show as `null` in Drizzle Studio

### ISSUE THREAD

**Issue by hmarr** [drizzle-team/drizzle-kit-mirror#365]
As of a recent release, postgres `timestamp` values are showing up as `null` in Drizzle Studio. If I select the cell, I see `Invalid Date` instead. I think it was working within the last week or so, so I suspect it's a recent regression.

<hr>

Here's what I'm seeing in Drizzle Studio:

<img width="351" alt="image" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/110275/980aa83d-b690-49df-ac09-14ce2e42eab4">

<hr>

And if I query the table directly in a psql console:

<img width="334" alt="image" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/110275/0b4bd578-1efd-4d44-9f5d-c46bc0eac639">

**Comment by RomanNabukhotnyi** [comment]
@hmarr Hey! This should work now, please try it

**Comment by hmarr** [comment]
Seems to be fixed, thanks for the super quick response! 🙌
