### ISSUE TITLE
sqlite alter column should list changes

### ISSUE THREAD

**Issue by kelbyfaessler** [drizzle-team/drizzle-kit-mirror#376]
When you attempt to change the column type in a sqlite schema, then generate a migration file, this is the result:

```
/*
 SQLite does not support "Changing existing column type" out of the box, we do not generate automatic migration for that, so it has to be done manually
 Please refer to: https://www.techonthenet.com/sqlite/tables/alter_table.php
                  https://www.sqlite.org/lang_altertable.html
                  https://stackoverflow.com/questions/2083543/modify-a-columns-type-in-sqlite3

 Due to that we don't generate migration automatically and it has to be done manually
*/
```

That's fine, I'd prefer if you generated the SQL for me but I guess I can do it manually.

But it'd be nice if the comment included the changes that must be completed manually. For example, `change column <xyz> from type <x> to type <y>`

**Comment by L-Mario564** [comment]
SQLite doesn't generate these type of comments in newer versions of Kit. If you encounter any bugs related to the new behavior, feel free to report it on the main repo: https://github.com/drizzle-team/drizzle-orm/issues.
