### ISSUE TITLE
two bug of drizzle-kit introspect:mysql

### ISSUE THREAD

**Issue by hdj258** [drizzle-team/drizzle-kit-mirror#385]
import { mysqlTable, mysqlSchema, AnyMySqlColumn, unique, varchar, text, tinyint, index, decimal, datetime, int, longtext, foreignKey, double, tinytext, char, mediumtext, date, mysqlEnum } from "drizzle-orm/mysql-core"
import { sql } from "drizzle-orm"

export const allLocator = mysqlTable("all_locator", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
},
(table) => {
	return {
		locator#locator2: index("locator#locator_2").on(table.locator, table.materialId, table.tenantId, table.deleteFlag),
	}
});

1, no import bigint
2, locator#locator2 includes Special symbols, so "locator#locator2"

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/2988.
