### ISSUE TITLE
Drizzle Integration with Bun: async_hooks.createHook not supported and Missing Configuration File Error

### ISSUE THREAD

**Issue by Arunpaneru** [drizzle-team/drizzle-kit-mirror#394]
This issue reports two problems encountered when attempting to integrate Drizzle (versions drizzle-kit v0.20.18 and drizzle-orm v0.30.10) with the Bun JavaScript runtime:

## Bun Hook Warning:
Bun generates a warning message stating async_hooks.createHook is not implemented in Bun. This indicates that Drizzle might be relying on the async_hooks module for asynchronous I/O monitoring, which Bun doesn't currently support.
Missing Configuration File: Drizzle fails to find the default configuration file drizzle.config.json. The error message "Failed to find Response internal state key" might be related to this.
Expected Behavior:

Drizzle should run seamlessly within the Bun environment without warnings or errors.
If Drizzle cannot leverage async_hooks in Bun, it should fall back on alternative methods or provide a way to disable this functionality.
The default configuration file drizzle.config.json should be located and used as expected.
Additional Information:

Bun Version: (Please specify the Bun version you're using)
Drizzle Usage: (Briefly describe how you're using Drizzle in your Bun project)
Steps to Reproduce:

## Create a Bun project (if applicable).
Install Drizzle dependencies using bun install drizzle-kit drizzle-orm.
Attempt to run your Drizzle application using Bun's script runner (e.g., bun run generate).
Possible Solutions (to be explored):

### Investigate Drizzle's compatibility with Bun.
Explore alternative approaches for asynchronous I/O monitoring in Bun.
Create the missing drizzle.config.json file (if necessary).
Consider using Drizzle in a Node.js environment if Bun compatibility is a challenge.
We appreciate any insights or suggestions the community might have to resolve this issue and improve Drizzle's integration with Bun.

**Comment by phoenisx** [comment]
I guess the same is true for Deno as well.
I am getting the following error when trying to start drizzle-kit studio using `deno`:

```
Failed to find Response internal state key
...
Drizzle Studio is up and running on https://local.drizzle.studio
Terminating Deno.serve loop due to unexpected error TypeError: Cannot read properties of undefined (reading 'status')
```

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/2239.
