### ISSUE TITLE
My Error Code "There is not enough information to infer relation "__public__.postTable.likes""

### ISSUE THREAD

**Issue by novinbooster** [drizzle-team/drizzle-kit-mirror#396]
`
import { relations } from "drizzle-orm"
import {
	pgTable,
	serial,
	text,
	timestamp,
	unique,
	varchar,
} from "drizzle-orm/pg-core"

const userTable = pgTable("users", {
	id: text("id").primaryKey(),
	name: text("name").notNull(),
	email: text("email").unique().notNull(),
	image: varchar("image").notNull(),
	bio: text("bio").default("").notNull(),
	website: varchar("website").default("").notNull(),
	username: varchar("username").unique().notNull(),
})

const postTable = pgTable("posts", {
	id: serial("id").primaryKey(),
	content: text("content").notNull(),
	createdAt: timestamp("created_at").defaultNow().notNull(),
	userId: text("user_id")
		.notNull()
		.references(() => userTable.id),
})

const likeTable = pgTable(
	"likes",
	{
		userId: text("user_id")
			.notNull()
			.references(() => userTable.id),
		postId: serial("post_id")
			.notNull()
			.references(() => postTable.id),
		createdAt: timestamp("created_at").defaultNow().notNull(),
	},
	(table) => {
		return {
			unq: unique().on(table.userId, table.postId),
		}
	},
)

const usersRelations = relations(userTable, ({ many }) => ({
	posts: many(postTable),
	likes: many(likeTable),
}))

const postsRelations = relations(postTable, ({ one, many }) => ({
	user: one(userTable, {
		fields: [postTable.userId],
		references: [userTable.id],
	}),
	likes: many(likeTable),
}))

type Post = typeof postTable.$inferSelect & {
	user: User
}
type User = typeof userTable.$inferSelect & {
	posts: Post[]
}

export { likeTable, postTable, postsRelations, userTable, usersRelations }
export type { Post, User }

`

**Comment by absolutetsonga** [comment]
Faced the same issue, turns out they're strict on defining the relationName on both sides as [mentioned in here](https://www.answeroverflow.com/m/1180072254214766632)

Ensuring it's defined on both sides solved my issue
