### ISSUE TITLE
Change the schema creation SQL in PostgreSQL

### ISSUE THREAD

**Issue by syhily** [drizzle-team/drizzle-kit-mirror#398]
Currently the generated migration may contains a schema SQL if I use `pgSchema`.

For example, `export const schema = pgSchema('duoshuo');` will generate `CREATE SCHEMA "duoshuo";` in the migration file.

I think we should change it to `CREATE SCHEMA IF NOT EXISTS "duoshuo";`.

**Comment by L-Mario564** [comment]
Statements like `if not exists` are going to be removed from entities like tables that already have it, so we won't add this.
