### ISSUE TITLE
array fields end up as "undefined" in the schema

### ISSUE THREAD

**Issue by capaj** [drizzle-team/drizzle-kit-mirror#4]
I have a table like this:

```sql
CREATE TABLE "MyTable" (
    "photos" TEXT[],
);
```

ideally 
 - the generator should skip fields which it cannot map into a concrete type and emit a warning
 - the generator should ideally support array fields

**Comment by AndriiSherman** [comment]
Fixed in [0.17.0](https://github.com/drizzle-team/drizzle-kit-mirror/releases/tag/v0.17.0)
