### ISSUE TITLE
[BUG] A number value is specified as the default for a column of type char

### ISSUE THREAD

**Issue by Karibash** [drizzle-team/drizzle-kit-mirror#404]
### What version of `drizzle-orm` are you using?

0.30.10

### What version of `drizzle-kit` are you using?

0.21.0

### What type of `database` are you using?

MySQL

### Describe the Bug

When the default value of a column of type varchar is a numeric string, the default function is passed a numeric value instead of a string when the introspect command is used to generate the schema.

This is caused by casting a string to a number without checking whether the column is of type char.

```ts
const newColumn = {
  default: columnDefault === null ? void 0 : /^-?[\d.]+(?:e-?\d+)?$/.test(columnDefault) && !columnType.startsWith("decimal") ? Number(columnDefault) : isDefaultAnExpression ? clearDefaults(columnDefault, collation) : `'${columnDefault}'`,
  autoincrement: isAutoincrement,
  name: columnName,
  type: changedType,
  primaryKey: false,
  notNull: !isNullable,
  onUpdate
};
```

### Expected behavior

If the column is a char type, the default is also specified as a string.

### Patch

The following patch can be applied as a workaround until this issue is resolved.

```diff
diff --git a/bin.cjs b/bin.cjs
index fef2511d2e2d69c877fc925c281d88aa828f150f..c0ecbb07b62c35b08b8ddf709a7b0a7b67e13aa7 100755
--- a/bin.cjs
+++ b/bin.cjs
@@ -15246,7 +15246,7 @@ We have encountered a collision between the index name on columns ${source_defau
           onUpdate = true;
         }
         const newColumn = {
-          default: columnDefault === null ? void 0 : /^-?[\d.]+(?:e-?\d+)?$/.test(columnDefault) && !columnType.startsWith("decimal") ? Number(columnDefault) : isDefaultAnExpression ? clearDefaults(columnDefault, collation) : `'${columnDefault}'`,
+          default: columnDefault === null ? void 0 : /^-?[\d.]+(?:e-?\d+)?$/.test(columnDefault) && !['decimal', 'char', 'varchar'].some(type => columnType.startsWith(type)) ? Number(columnDefault) : isDefaultAnExpression ? clearDefaults(columnDefault, collation) : `'${columnDefault}'`,
           autoincrement: isAutoincrement,
           name: columnName,
           type: changedType,
```

**Comment by Karibash** [comment]
@AndriiSherman 
I understand that you are busy, but I would appreciate it if you could take a look at this.
If the source was public, I could create a pull request myself...
I would also appreciate it if you could take a look at the following issues as well:
#403 #402

Thank you.

**Comment by AndriiSherman** [comment]
Should be fixed in `drizzle-kit0.24.0`
Please check [release notes](https://github.com/drizzle-team/drizzle-orm/releases/tag/drizzle-kit%400.24.0) before updating
