### ISSUE TITLE
[Bug] TypeError: Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by sohhamm** [drizzle-team/drizzle-kit-mirror#408]
### What version of `drizzle-orm` are you using?
-  "drizzle-kit": "^0.21.1"

### Describe the Bug
I'm using Supabase as my managed PostgreSQL service which is my source of truth, therefore I'm only using the introspect feature of drizzle-kit, this used to work fine in the version 0.20.x, now I'm getting the error

<img width="962" alt="Screenshot 2024-05-14 at 6 48 58 PM" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/54359257/dca0a32a-04b6-4322-b853-19897c1ff064">

### Expected behavior
Ideally work seamlessly as the previous version

### Environment & setup
 
drizzle.config.ts

`ts
import 'dotenv/config'
import {defineConfig} from 'drizzle-kit'

if (!process.env.DATABASE_URL) {
  console.log('🔴 Cannot find database url')
}

export default defineConfig({
  schema: './migrations/schema.ts',
  out: './migrations',
  dbCredentials: {
    url: process.env.DATABASE_URL,
  },
  verbose: true,
  strict: true,
  dialect: 'postgresql',
})`

**Comment by wong2** [comment]
Same, any news?

**Comment by wong2** [comment]
This works for me
https://github.com/drizzle-team/drizzle-orm/issues/2338#issuecomment-2117496180

**Comment by L-Mario564** [comment]
This should be fixed in latest as Drizzle now fully aims to support Supabase.
