### ISSUE TITLE
PostgreSQL - cannot create index with `using`

### ISSUE THREAD

**Issue by knarfchan** [drizzle-team/drizzle-kit-mirror#41]
Hi, I'm trying to create a GIN index in Postgres on a table like this

```
CREATE INDEX example_index ON example_table USING gin ((data->'path'->'to'->'field') jsonb_path_ops);
```

In this case I don't need to specify any columns, but drizzle's index builder doesn't have a way to specify a table without any columns. It also seems like both the `where` and `using` methods in the index builder do nothing. Passing sql expressions into them does not result in any changes to the generated index.

Using
"drizzle-kit": "^0.17.6",
"drizzle-orm": "^0.25.2",

**Comment by Siris01** [comment]
Facing the same issue with btree indexes

**Comment by TangoYankee** [comment]
> It also seems like both the where and using methods in the index builder do nothing.

I think this behavior is expected as of drizzle-kit 0.20.7. From the [indexes docs](https://orm.drizzle.team/docs/indexes-constraints#indexes)
> As of now drizzle-kit only supports index name and on() param.
