### ISSUE TITLE
[BUG] generate postgresql not detecting removed NOT NULL constraint

### ISSUE THREAD

**Issue by alanhamlett** [drizzle-team/drizzle-kit-mirror#412]
I changed the schema to remove `.notNull()` from 2 columns on a table (`varchar` and `integer`) but no changes are detected.

Even adding `.notNull()` to the columns in my schema then running `drizzle-kit generate` detects no changes. It's like null constraints are now skipped when generating migrations. It was working in the previous version of drizzle-kit, broke after upgrading drizzle-kit to `v0.21.2`.

**Comment by davidgomes** [comment]
I can confirm that I have just reproduced this on 0.21.2.

**Comment by cybercoder-naj** [comment]
I have reproduced this in 0.22.8.

**Comment by L-Mario564** [comment]
This should be fixed in the latest version of Kit. If you still encounter this bug after upgrading, feel free to report it on the main repo: https://github.com/drizzle-team/drizzle-orm/issues.
