### ISSUE TITLE
drizzle-kit migrate hangs with 0.21.3 (postgres)

### ISSUE THREAD

**Issue by mdurling** [drizzle-team/drizzle-kit-mirror#426]
When upgrading to `drizzle-kit@0.21.3`, the `drizzle-kit migrate` command hangs indefinitely at `[⡿] applying migrations...`

Migrations are applied successfully if I downgrade back to `drizzle-kit@0.21.2`

**Comment by AlexBlokh** [comment]
fixed in `0.21.4`
