### ISSUE TITLE
Corrupted schema data generated by `introspect`

### ISSUE THREAD

**Issue by serhii-kucherenko** [drizzle-team/drizzle-kit-mirror#427]
I generated schema from the existing supabase and got a lot of unknown functions that I assume should be different or at least auto-imported from zod (for example).
It's a HUGE blocker to proceed with the drizzle further for my project.
Let me know if you can help me.
Thanks.

### Schreenshots
1. Table from supabase schema: "auth"
2. Table from supabase schema: "public"

------

<img width="929" alt="image" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/21200035/19e9521e-0877-4f18-bfa8-8c453a12c996">

<img width="1061" alt="image" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/21200035/608891fd-3e25-417f-b255-5a85c6119d35">

### Dependencies

```
"drizzle-kit": "0.21.3",
"drizzle-orm": "0.30.10",
"drizzle-zod": "0.5.1",
"ts-node": "10.9.2",
"typescript": "5.4.5"
```

**Comment by AlexBlokh** [comment]
can you please share a pg dump without data?

**Comment by PawelDmochowskiMeetingPackage** [comment]
Providing more context because this is not supabase specific.
In my case it's PostgreSQL.
A simple repro:

Those DDL statements
```
CREATE SEQUENCE IF NOT EXISTS public.test_table_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

CREATE TABLE test_table
(
    id bigint NOT NULL DEFAULT nextval('test_table_id_seq'::regclass),
    case_insensitive_name citext,
    price money
);
```
are introspected to
```
export const testTable = pgTable("test_table", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint("id", { mode: "number" }).default(nextval('test_table_id_seq'::regclass)).notNull(),
	// TODO: failed to parse database type 'citext'
	caseInsensitiveName: unknown("case_insensitive_name"),
	// TODO: failed to parse database type 'money'
	price: unknown("price"),
});
```
It's clear that default value for `id` column should be sql-quoted and `citext` and `money` types are "unknown".

`citext` is from extension so that's kind of understandable.
`money` though is a built-in type for PostgreSQL.

My env:
```
"drizzle-kit": "0.22.1",
"drizzle-orm": "0.31.0",
"ts-node": "10.9.2",
"typescript": "5.4.5"
```

**Comment by tehnorm** [comment]
Looks like this might be the same issue https://github.com/drizzle-team/drizzle-kit-mirror/issues/441 `nextval` is not getting wrapped correctly with `sql`

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-kit-mirror/issues/441.
