### ISSUE TITLE
Unable to run sqlite migrations local.

### ISSUE THREAD

**Issue by tobiasfoerg** [drizzle-team/drizzle-kit-mirror#432]
Hi,
i am not able to run local sqlite migrations.
I allways receive the following error:
```console
~/xxxxx> pnpm drizzle-kit migrate                                                                                                                        
drizzle-kit: v0.21.4
drizzle-orm: v0.30.10

No config path provided, using default path
Reading config file '/home/xxxxx/drizzle.config.ts'
 Invalid input  Either "turso", "libsql", "better-sqlite" are available options for "--driver"
```

My config is:
```ts
// drizzle.config.ts
import { defineConfig } from "drizzle-kit";
import { globSync } from "fast-glob";

const path = globSync(".wrangler/state/v3/d1/**/*.sqlite");

export default defineConfig({
	schema: "./app/db.server/schema.ts",
	out: "./migrations",
	dialect: "sqlite",
	strict: true,
	migrations: {
		table: "__schema_migrations",
	},
	dbCredentials: {
		url: path[0],
	},
});
```
and i have `"@libsql/client": "^0.6.0",` as dev dependency.

**Comment by raiyansarker** [comment]
I am having this issue,

<img width="490" alt="Screenshot 2024-05-24 at 3 19 13 AM" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/38852396/41df2bd1-da3c-4332-883a-19c0c3206949">

this is my config,
<img width="352" alt="Screenshot 2024-05-24 at 3 19 37 AM" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/38852396/773a64c1-d5d5-474e-9eea-3fe743236c83">
