### ISSUE TITLE
`drizzle-kit generate` doesn't detect changes to columns when table has been renamed

### ISSUE THREAD

**Issue by niklashigi** [drizzle-team/drizzle-kit-mirror#446]
I just did a rather large migration where I renamed one of the core concepts in my application. This resulted in multiple tables (e.g., `houses` became `buildings`) and a few properties on those tables (e.g., `house_id` became `building_id`) being renamed.

After running `drizzle-kit generate`, I was asked which tables to drop/rename, and I selected all the relevant tables there. Then, the migration was generated, and I thought I was done.

That's when I realized that the columns in those tables hadn't been touched. The snapshot had been updated and now included the names of the renamed columns but the `.sql` file didn't contain any statements to modify them.

### Expected behavior

`generate` first asks about the renamed tables and then does another diffing pass and asks about the renamed columns in those tables. The resulting migration updates both the table and the column names and the snapshots is updated as expected.

**Alternatively** (this could be a temporary fix): The resulting migration only updates the table names but the snapshot also reflects that (i.e., the old column names are retained). This would allow running `generate` again to then update the column names as part of a second migration.

### Actual behavior

`generate` only asks about the renamed tables. The resulting migration only updates the table names and the snapshot is brought into an incorrect out-of-sync state (which means that a second `generate` pass couldn't fix the drift).

### Version

I used version `0.21.2` of `drizzle-kit`.

**Comment by L-Mario564** [comment]
This should be fixed in latest.
