### ISSUE TITLE
[BUG]: Generates using clause without quoting the column name

### ISSUE THREAD

**Issue by Vorelli** [drizzle-team/drizzle-kit-mirror#448]
Config:
`{
  dialect: 'postgresql',
  schema: './schema/**/*.ts',
  out: '../drizzle',
}`
Original:
`CREATE INDEX IF NOT EXISTS "applicationsDateAppliedIdx" ON "applications" USING btree (dateApplied);`
Expected:
`CREATE INDEX IF NOT EXISTS "applicationsDateAppliedIdx" ON "applications" USING btree ("dateApplied");`

**Comment by knurzl** [comment]
Having exactly the same problem. Using the newest version 0.22.1.
Also the debug messages could be a lot better. Took me a few hours to find the problem.

**Comment by Vorelli** [comment]
Looks like this is fixed, at least on 0.22.7!!!
