### ISSUE TITLE
[Improvement: STUDIO] Show warning when ``pg`` dependency is not installed

### ISSUE THREAD

**Issue by dotarjun** [drizzle-team/drizzle-kit-mirror#449]
There are multiple issues regarding this which can easily be dealt with by having that warning shown in the console. 

Case in point: 
https://discord.com/channels/1043890932593987624/1247244064567590914
https://discord.com/channels/1043890932593987624/1246938578399924225
https://discord.com/channels/1043890932593987624/1244930484912521287

**Comment by L-Mario564** [comment]
This has been improved upon in newer versions of Kit.
