### ISSUE TITLE
[BUG]: Push is comparing schema objects against Supabase's schemas. 

### ISSUE THREAD

**Issue by stefanosandes** [drizzle-team/drizzle-kit-mirror#451]
### What version of `drizzle-orm` are you using?

0.30.10

### What version of `drizzle-kit` are you using?

0.21.1

### Describe the Bug

When I run `drizzle-kit push` in an empty Supabase database, it is comparing my schema with Supabase's own schemas.

![image](https://github.com/drizzle-team/drizzle-orm/assets/6722075/bec17d26-cf06-4b44-92f4-41e054761c43)

I tried to specify schemaFilter in drizzle.config.ts, but dont worked.

### Expected behavior

Drizzle should not consider about other schemas than the main schema, unless it is specified.

### Environment & setup

```
OS: macOS 14.4.1  arm64
Node: v20.12.1
```

This issue was originally opened on the drizzle-orm repo. https://github.com/drizzle-team/drizzle-orm/issues/2312

**Comment by L-Mario564** [comment]
This should be fixed in latest.
