### ISSUE TITLE
when running drizzle studio SQL runner, keep getting "column does not exist" error

### ISSUE THREAD

**Issue by holahoon** [drizzle-team/drizzle-kit-mirror#467]
drizzle: ^0.31.2
dirzzle-kit: ^0.22.7

Every time I run the SQL runner, or even the Drizzle runner and add a `WHERE` clause, it keeps throwing `Column "__" does not exist".

Here's a sample schema:
```typescript
// state.schema.ts
import { relations } from 'drizzle-orm'
import { pgTable, varchar } from 'drizzle-orm/pg-core'
import { church } from './church.schema'

export const state = pgTable('state', {
  code: varchar('code', { length: 2 }).notNull().primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
})

export const stateRelations = relations(state, ({ many }) => ({
  churches: many(church),
}))

export type State = typeof state.$inferSelect
export type NewState = typeof state.$inferInsert
```

And the drizzle configuration file: (I have a `index.ts` file that exports all of the schema files within the directory)
```typescript
// drizzle.config.ts
import { defineConfig } from 'drizzle-kit'
import { env } from '@/lib/env'

export default defineConfig({
  schema: './src/lib/db/schema/index.ts',
  dialect: 'postgresql',
  migrations: {
    table: 'migrations',
    schema: 'public',
  },
  dbCredentials: {
    url: env.DATABASE_URL,
  },
  out: './drizzle',
})
```

Here's the SQL runner:
```
SELECT
  *
FROM
  "state";
```
This runs perfectly fine and returns a list of all the states in the `state` table.
But, if I add the `WHERE` clause,
```
SELECT
  *
FROM
  "state"
WHERE
  code = "AZ";
```
I get the pretty `column "AZ" does not exist` error.
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/42850638/6b52699e-e0ed-41e6-a7e9-2c059a052f4d)
But the column does exist, and there's no "AZ" column??
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/42850638/d68547a2-bb1c-48f1-b792-46b707dae075)

Am I missing something??

**Comment by L-Mario564** [comment]
There's a small syntax error in your query.

```
SELECT
  *
FROM
  "state"
WHERE
  code = 'AZ'
```

The above is the fixed version. Double quotes are reserved for entity names (tables, columns, enums, etc.) while single quotes are for string values.
