### ISSUE TITLE
Feature request: heplful error messages

### ISSUE THREAD

**Issue by titong0** [drizzle-team/drizzle-kit-mirror#469]
Currently, when developing in sqlite and trying to add a foreign key, drizzle will generate a migration file with a comment explaining it is not possible and delegating the job to the developer. These messages are often not clear enough in the sense that they don't tell you anything about the part that is causing this. It would be great if the comment included something like "(adding foreign key on column X on table Y". Thanks!

**Comment by L-Mario564** [comment]
These messages are no longer present in latest and are automatically handled.
