### ISSUE TITLE
Open sourcing drizzle-kit

### ISSUE THREAD

**Issue by pkarolyi** [drizzle-team/drizzle-kit-mirror#474]
Dear Drizzle team,

In this issue[1] you mention that the open-sourcing of drizzle-kit will happen "very soon", and the public roadmap[2] gives a target date of 2023-12-20. Can you give an estimate of when you think this will happen?

I understand that the repository needs to be cleaned up before opening it to the public, but I think that having a core part of your project closed source undermines confidence in the long-term viability of the project. I fear that you will start monetising drizzle-kit, which makes us reluctant to use it for critical projects.

Thanks!

[1]: https://github.com/drizzle-team/drizzle-orm/issues/580
[2]: https://github.com/orgs/drizzle-team/projects/1/views/1?filterQuery=open&pane=issue&itemId=44462224

**Comment by Aeolun** [comment]
I'm more annoyed by the fact that I can use it, but can't figure out how it works now that I have an issue. It's incredibly weird to find this code closed when I started searching for it.

**Comment by lagnat** [comment]
@AndriiSherman Any update?

**Comment by septatrix** [comment]
Drizzle-kit was introduced to the monorepo with https://github.com/drizzle-team/drizzle-orm/pull/2711

I guess all issues from this repo should be transferred over to the main repo...?

**Comment by L-Mario564** [comment]
Kit is now open-source: https://github.com/drizzle-team/drizzle-orm/tree/main/drizzle-kit.
