### ISSUE TITLE
`drizzle-kit generate` should not add random words to migration filename.

### ISSUE THREAD

**Issue by gburtini** [drizzle-team/drizzle-kit-mirror#483]
When you generate a migration, three files are modified:

1. a new SQL file, called `{ID}_{two or three random words}.sql`, which describes the transformations to synchronize the database with the current state of the schema.
2. a snapshot file, called `meta/{ID}_snapshot.json`
3. and the journal file, listing off the migrations in order.

When two developers in separate branches create migrations simultaneously, files (2) and (3) will correctly result in conflicts, **but file (1) will not**. This means simple patterns like `merge --theirs && regenerate` leave behind an additional file ([here is an example script](https://gist.github.com/gburtini/7e34842c567dd80ee834de74e7b79edd) to do that that may be instructive for someone who wants to do this on their team).

The random word pattern used in many other ORMs makes sense, because migrations are not monotonically incrementing IDs. With Drizzle, two migrations created simultaneously share an ID and may reference the wrong snapshot, so they necessarily _must_ be manually resolved.

Obviously I would invite other solutions for dealing with conflicts. Merge queues, timestamp-as-ID or a smart resolve tool may be a better solution.

**Comment by hprathap** [comment]
+1 for this

**Comment by lukemorales** [comment]
I got into a discussing about this today with my team. Would be really nice to have some visibility from the drizzle team

**Comment by misium** [comment]
In case it helps -- and something I also missed at first -- you can change the non-{ID} segment of the name with the [`name:` parameter in config](https://orm.drizzle.team/kit-docs/commands) (or in the CLI at runtime)

**Comment by gburtini** [comment]
Thanks @misium, I missed that as well. Just changed my generate command to have `--name "migration"` so these conflicts occur as I expect. 

I still think there's no case for the random words, but that solution gets me around the core issue.

**Comment by L-Mario564** [comment]
Better handling of migration conflicts will be implemented and documented soon. I'll be closing this issue as we're already tracking similar ones over on the main Drizzle ORM repo.
