### ISSUE TITLE
[Enhancement] Log where studio running

### ISSUE THREAD

**Issue by kravetsone** [drizzle-team/drizzle-kit-mirror#487]
It would be better if `drizzle-kit` studio log in the console `http://localhost:PORT` because, for example, VS Code, provided remote development, automatically sees this and opens port forwarding

**Comment by L-Mario564** [comment]
I'll be closing this issue. I'm migrating issues from this repo to the main one, and seeing as there is already a PR for this I won't rewrite this to the main repo.
