### ISSUE TITLE
Unknown option when trying to use `--name` when generating migrations file

### ISSUE THREAD

**Issue by dbeaudway** [drizzle-team/drizzle-kit-mirror#489]
Hello, I'm trying to create a named migration file by passing the `--name` argument like so:
```
drizzle-kit generate:pg --name init_db
```

[This is exactly as shown in the website documentation here](https://orm.drizzle.team/kit-docs/commands#generate-migrations).

However, I receive the following error:
```
error: unknown option '--name'
```

Additionally, `drizzle-kit generate:pg --help` does not list `--name` as an option.

Is the documentation incorrect?

**Comment by L-Mario564** [comment]
You may need to update Kit and ORM. This shouldn't be an issue in newer versions of Drizzle.
