### ISSUE TITLE
`drizzle-kit introspect` fails with error `movedTables is not iterable`

### ISSUE THREAD

**Issue by nickreynolds** [drizzle-team/drizzle-kit-mirror#493]
Using version `0.23.0` gives me this error, downgrading to `0.21.4` (with `drizzle-orm@0.29.3`) works correctly.

note: 

my DB has a table with a hyphen in the name, although I tried renaming the table but it still failed on `0.23.0`. It works correctly with `0.21.4` although the schema.ts generated has a syntax error (hyphen in exported const name) that I had to fix manually.

**Comment by asolya** [comment]
same here as well

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/2618 over on the main repo.
