### ISSUE TITLE
`drizzle-kit generate` fails with `"undefined" is not valid JSON`

### ISSUE THREAD

**Issue by nickreynolds** [drizzle-team/drizzle-kit-mirror#494]
I have a schema file that was generated by introspecting an existing postgres DB. The schema file contains:

```
export const identifier = pgTable(
	"identifier",
	{
		did: varchar("did").primaryKey().notNull(),
		provider: varchar("provider"),
		alias: varchar("alias"),
		saveDate: timestamp("saveDate", { mode: "date" }).notNull(),
		updateDate: timestamp("updateDate", { mode: "date" }).notNull(),
		controllerKeyId: varchar("controllerKeyId"),
	},
	(table) => {
		return {
			IDX_6098cca69c838d91e55ef32fe1: uniqueIndex(
				"IDX_6098cca69c838d91e55ef32fe1",
			).on(table.provider, table.alias),
		};
	},
);
```

But when I run `pnpm drizzle-kit generate`, I get an error of:

```
SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
```

If I remove the index, it generates the migration, but I need the index

**Comment by krishanmarco** [comment]
For me this was related to having a different global version of `drizzle-kit` installed than the one used in my package.
Check the version of `which drizzle-kit`

**Comment by L-Mario564** [comment]
We'll continue tracking this issue over here: https://github.com/drizzle-team/drizzle-orm/issues/3255.
