### ISSUE TITLE
partition table shcema using drizzle introspect 

### ISSUE THREAD

**Issue by Sourabh-jana** [drizzle-team/drizzle-kit-mirror#505]
I just used introspect to pull up a bench.

The partitions came as separate tables... this is really bad.

tb_example_1
tb_example_2
tb_example_3
tb_example_4

how to have only the master table schema without its partition tables as these are logical partitioning in postgresql

this is perfectly done in prisma but drizzle still not smart enough to do this

![image](https://github.com/user-attachments/assets/62dc3a54-6d4a-4e76-87cf-e637932d24ce)

**Comment by L-Mario564** [comment]
Closed in favor of https://github.com/drizzle-team/drizzle-orm/issues/2854.
