### ISSUE TITLE
bit type goes to postgresql as a string

### ISSUE THREAD

**Issue by PureSci** [drizzle-team/drizzle-kit-mirror#509]
When drizzle-kit generate is ran on the following code, the sql code it creates has the bit type as a string that it gives an error.
```ts
export const users = pgTable(
  "user",
  {
    id: bigint("id", { mode: "bigint" }).primaryKey(),
    test: bit("test", { dimensions: 10 }),
  }
);
```
->
```sql
CREATE TABLE IF NOT EXISTS "user" (
             "id" bigint PRIMARY KEY NOT NULL,
            "test" "bit(10)",
);
```
`ERROR:  type "bit(10)" does not exist at character ***`

**Comment by L-Mario564** [comment]
We'll continue to track this issue over here: https://github.com/drizzle-team/drizzle-orm/issues/3254.
