### ISSUE TITLE
Enum array column

### ISSUE THREAD

**Issue by nehalist** [drizzle-team/drizzle-kit-mirror#511]
My schema:

```typescript
  // ...
  modules: productModuleEnum("productModule")
    .array()
    .notNull()
    .default(sql`ARRAY[]::productModule[]`),
  // ...
```

My enum:
```
export const productModuleEnum = pgEnum("productModule", [
  ProductModule.Specifications,
]);
```

When I run `drizzle-kit push` I get:

```
PostgresError: type "productmodule[]" does not exist
```

What's weird about the error is that `productmodule` is lowercased - while I have not a single lowercased `productModule` in my project.

@rphlmr was kind enough trying to help and even provided a drizzle.run playground: https://drizzle.run/n5dbm1kdp1bbub4ulnaqhi5w

Here's some additional info: https://discord.com/channels/1043890932593987624/1263155798968893562

**Comment by L-Mario564** [comment]
This should be fixed in latest. If you're still facing this issue after upgrading, please open a new issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues.
