### ISSUE TITLE
The studio is not loading at all

### ISSUE THREAD

**Issue by j4zzz** [drizzle-team/drizzle-kit-mirror#520]
# the studio is not opening

I mean the link is working but the studio when it loads it's just a white screen.
I am using the **__t3__** stack ( `npm run db:studio` )

**Comment by knowmance** [comment]
same here. but I also cannot push or do other db operations. On terminal I am seeing ETIMEDOUT. I have filed this as well https://github.com/drizzle-team/drizzle-kit-mirror/issues/506
