### ISSUE TITLE
drizzle-kit migrate fails with PostgresError: cannot ALTER TABLE "tablename" because it has pending trigger events

### ISSUE THREAD

**Issue by jwatte** [drizzle-team/drizzle-kit-mirror#525]
If I have one schema that creates some table, and another later schema that alters the table, trying to drizzle-kit migrate will fail with the error:
PostgresError: cannot ALTER TABLE "tablename" because it has pending trigger events

This is a common problem for tooling that doesn't commit each schema file separately, so I would assume drizzle-kit has this problem too, although the source is apparently not available to read?

**Comment by L-Mario564** [comment]
We'll continue tracking this issue here: https://github.com/drizzle-team/drizzle-orm/issues/3249.
