### ISSUE TITLE
drizzle-kit fails to order postgresql index and constraint columns when fetching the database's current state

### ISSUE THREAD

**Issue by ihameed** [drizzle-team/drizzle-kit-mirror#526]
When using `drizzle-kit push`, drizzle-kit will sometimes retrieve index and constraint columns from the database in the wrong order, relative to the index/constraint column order specified in the associated drizzle-orm `pgTable` table definition. This happens because drizzle-kit doesn't use an `order by` clause to explicitly specify an ordering for the data retrieved from `pg_catalog` or `information_schema` inside `fromDatabase2`. This wrong order will then cause drizzle-kit to attempt to drop and recreate these indices or constraints needlessly; this causes `drizzle-kit push` run twice in a row on the same postgresql instance to fail during the second run.

The originating typescript source code to drizzle-kit doesn't seem to be publicly available. Here's a patch, that fixes this for me, against bin.cjs from the v0.23.0 npm release of drizzle-kit: https://gist.github.com/ihameed/4f94abfe719fedf0a456a18bb706fbd7

**Comment by L-Mario564** [comment]
We'll continue tracking this issue here: https://github.com/drizzle-team/drizzle-orm/issues/3274.
