### ISSUE TITLE
[BUG]: Declaration files for drizzle-kit?

### ISSUE THREAD

**Issue by michealroberts** [drizzle-team/drizzle-kit-mirror#53]
I'm attempting to use drizzle.config.ts for some migrations, but the `Config` type imported from this library is not available as the type declarations aren't being shipped with this package.

<img width="479" alt="Screenshot 2023-05-17 at 16 48 51" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/84131395/9587ac1f-44de-4466-9fe0-e70fe2e4f9dc">

Not quite sure what is going on here ?

**Comment by AndriiSherman** [comment]
What version of `drizzle-kit` are you using?

**Comment by michealroberts** [comment]
@AndriiSherman : 

```
"devDependencies": {
    "drizzle-kit": "^0.17.6"
}
```

**Comment by AndriiSherman** [comment]
`0.17.6` doesn't have support for `.ts` file. It's currently available on internal release (it will be in latest soon)

https://github.com/drizzle-team/drizzle-orm/blob/db-push-docs/docs/db-push.preview.md

**Comment by michealroberts** [comment]
Ok @AndriiSherman fair. Please let me know when this will be available! Would love to use it.
