### ISSUE TITLE
[BUG]: Question marks break queries in drizzle studio extension

### ISSUE THREAD

**Issue by ivstiv** [drizzle-team/drizzle-kit-mirror#531]
I noticed that while using the drizzle studio chrome extension some of my JSON columns when updated don't get saved. Upon further inspection I found out that if I add a question mark or if there is already a question mark in a json column, the query that gets sent to the server is completely broken.

Here is a basic example of a request where I am trying to save this json column:
```json
{
  "name": "test ?"
}
```

The payload that gets sent to planetscale looks like this:
```sql
"update `OrganisationGroup` set `jsonData` = '{\"name\":\"test '00b27ff0-af51-494a-bcc6-a26ec69f3f13'\"}' where `id` = ?"
```
 and the response I get back of course is:
 ```json
 {
    "session": {
        "signature": "0yjN4fIoLt6au4HvNP1QhwXg0BEIez9JDq5Rmfq/nYU=",
        "vitessSession": {
            "autocommit": true,
            "options": {
                "includedFields": "ALL",
                "clientFoundRows": true
            },
            "rowCount": "-1",
            "DDLStrategy": "direct",
            "SessionUUID": "c1lVKKQiTNtpdzFret4EMg",
            "enableSystemSettings": true
        }
    },
    "error": {
        "message": "syntax error at position 69 near '00b27ff0'",
        "code": "UNKNOWN"
    },
    "timing": 0.002650886
}
 ```
 
 
 I think it is pretty obvious what is happening here. The query builder thinks that the question mark in the json string is an input parameter for preparation and replaces it with what was supposed to be the ID of the resource to update.

**Comment by L-Mario564** [comment]
We'll keep track of this issue over here: https://github.com/drizzle-team/drizzle-orm/issues/3266.
