### ISSUE TITLE
Error: permission denied for table partner_users

### ISSUE THREAD

**Issue by eldevyas** [drizzle-team/drizzle-kit-mirror#532]
I'm encountering an error when trying to run Drizzle Studio on my machine. I already have Supabase Studio running locally, and it shows the database without any permission errors. The same goes for pgAdmin 4 - I can connect to the database without any permission errors.

```
Error: permission denied for table partner_users
    at $ (https://local.drizzle.studio/index.js:12885:10688)
    at async https://local.drizzle.studio/index.js:12885:4634
    at async Promise.all (index 1)
    at async Object.c [as tables] (https://local.drizzle.studio/index.js:12610:7475)
    at async https://local.drizzle.studio/index.js:12885:362
    at async Object.setQueryEngine (https://local.drizzle.studio/index.js:66:133013)
```

More context in the Drizzle Studio Bug Report:
[Bug Report.zip](https://github.com/user-attachments/files/16514868/Bug.Report.zip)

**Comment by LRboyz** [comment]
me too

**Comment by L-Mario564** [comment]
We'll track this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3246.
