### ISSUE TITLE
Error: Region is missing - Unable to use aws-data-api wuth drizzle-kit

### ISSUE THREAD

**Issue by poorya-smile** [drizzle-team/drizzle-kit-mirror#535]
I'm unable to use any of the drizzle commands when using the aws data api as the driver. The error is the same for all commands which is that it cannot find the region and there's no way to specify the region in the drizzle config file. The database connection in the ORM is working thanks to the region specification in the RDSClient.

[Bug Report.zip](https://github.com/user-attachments/files/16551777/Bug.Report.zip)

**Comment by sarthakroy107** [comment]
Facing same issue. Have you found the fix?

**Comment by poorya-smile** [comment]
The only workaround I was able to find was to set the region in the environment, so for example `drizzle-kit studio` becomes `AWS_REGION='your-region' drizzle-kit studio`.

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3253.

**Comment by ekaya97** [comment]
> The only workaround I was able to find was to set the region in the environment, so for example `drizzle-kit studio` becomes `AWS_REGION='your-region' drizzle-kit studio`.

What do you mean exactly? run the cli command including AWS_REGION='your-region' ?
