### ISSUE TITLE
[BUG]: "unix_timestamp is not defined" in Studio

### ISSUE THREAD

**Issue by Kamahl19** [drizzle-team/drizzle-kit-mirror#537]
I have a schema field `createdAt: int('created_at').notNull().default(sql`(unix_timestamp())`)` however when I want to use Drizzle runner in Studio it gives me an error
```
{
  "status": "error",
  "error": "unix_timestamp is not defined"
}
```
When I view schema in the Drizzle runner, the field looks like this:
```
createdAt: int("created_at").default(unix_timestamp()).notNull(),
```
As you can see, the sql`` is striped away and it consideres `unix_timestamp` to be a javascript function which is obviously undefined.

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3237.
