### ISSUE TITLE
SQLite current_timestamp insert is bugged in the studio

### ISSUE THREAD

**Issue by Igonato** [drizzle-team/drizzle-kit-mirror#540]
Schema ([docs](https://orm.drizzle.team/learn/guides/timestamp-default-value#sqlite)):

```ts
import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const posts = sqliteTable("post", {
    id: integer("id", { mode: "number" }).primaryKey({ autoIncrement: true }),
    title: text("title", { length: 256 }).notNull(),
    content: text("content").notNull(),
    createdAt: text("created_at")
        .notNull()
        .default(sql`(current_timestamp)`),
});

```

Studio:

![image](https://github.com/user-attachments/assets/3859747e-85c5-44d8-b5db-9f4f78452af4)

Result:

![image](https://github.com/user-attachments/assets/b74d8bff-6717-44bc-91ea-6970170d8e89)

From the code works fine:

![image](https://github.com/user-attachments/assets/1f9b156f-a18c-48fb-961e-da225014bc46)

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3259.
