### ISSUE TITLE
studio not querying bools correctly

### ISSUE THREAD

**Issue by Ribeiro-Tiago** [drizzle-team/drizzle-kit-mirror#541]
I have the following schema 
```typescript

export const users = pgTable(
  "users",
  {
    id: uuid("id").primaryKey().unique().notNull().defaultRandom(),
    email: text("email").unique().notNull(),
    password: text("password").notNull(),

    createdAt: timestamp("created_at").defaultNow(),
    verified: boolean("verified").default(false),
    type: text("type").$type<UserType>().default("user"),

    name: text("name"),
    gender: varchar("gender", { length: 15 }).$type<UserGender>().default("prefer_not_say"),
    birthday: date("birthday"),
    token: varchar("token", { length: 128 }),
    bio: text("bio"),
    interests: text("locations").array().$type<string[]>(),
    hobbies: text("hobbies").array().$type<string[]>(),
    city: varchar("city", { length: 256 }),
    picUrl: text("pic_url"),
    picThumbnailUrl: text("pic_thumbnail_url"),
  },
  (users) => ({
    idIdx: uniqueIndex("user_id_idx").on(users.id),
    emailIdx: uniqueIndex("user_email_idx").on(users.email),
    interestsIdx: index("user_interests_idx").on(users.interests),
    hobbiesIdx: index("user_hobbies_idx").on(users.hobbies),
  }),
);
```

I have these 5 items 

![Screenshot 2024-08-12 at 22 38 06](https://github.com/user-attachments/assets/57b97801-e042-48f8-971f-a2ecff05df38)

and when i try to query the verified field in the studio i get wrong results whether i do `verified equals true` or `false` i only get this one item 

![Screenshot 2024-08-12 at 22 37 25](https://github.com/user-attachments/assets/263c081a-2f91-423d-97f8-49471b6ac791)

and if I open in sql with the `Open in SQL` button, i can see that the value is being converted to string 

![Screenshot 2024-08-12 at 22 40 14](https://github.com/user-attachments/assets/f5da3f4e-5442-44ec-9187-e0d5822ca84e)

if i remove the quotes from the sql code, it works as expected

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3228.
