### ISSUE TITLE
Bug report: "Error: The result contains the unsupported data type "CHAR"."

### ISSUE THREAD

**Issue by magicspon** [drizzle-team/drizzle-kit-mirror#542]
When opening the studio I'm seeing the following error
![PixelSnap 2024-08-13 at 16 25 36](https://github.com/user-attachments/assets/b391fa63-836e-45ee-8e0a-651576b65eac)

Bug report attached: 

[bug-report.zip](https://github.com/user-attachments/files/16601811/bug-report.zip)

The error mentions `CHAR`, i'm not using `CHAR` anywhere in my schema.  unless `varchar` counts.  I've tried clearing local storage to no avail. 

```json
"drizzle-kit": "0.22.1",
"drizzle-orm": "^0.33.0",
"drizzle-zod": "^0.5.1",
```
Cheers

**Comment by jameslange** [comment]
I'm having the same issue.

```
"drizzle-kit": "0.24.0",
"drizzle-orm": "^0.33.0",
```

**Comment by LukasMurdock** [comment]
Specifically, this query for table constraints seems to be the cause

```sql
SELECT
            con.contype AS constraint_type,
            nsp.nspname AS constraint_schema,
            con.conname AS constraint_name,
            rel.relname AS table_name,
            att.attname AS column_name,
            fnsp.nspname AS foreign_table_schema,
            frel.relname AS foreign_table_name,
            fatt.attname AS foreign_column_name,
            CASE con.confupdtype
              WHEN 'a' THEN 'NO ACTION'
              WHEN 'r' THEN 'RESTRICT'
              WHEN 'n' THEN 'SET NULL'
              WHEN 'c' THEN 'CASCADE'
              WHEN 'd' THEN 'SET DEFAULT'
            END AS update_rule,
            CASE con.confdeltype
              WHEN 'a' THEN 'NO ACTION'
              WHEN 'r' THEN 'RESTRICT'
              WHEN 'n' THEN 'SET NULL'
              WHEN 'c' THEN 'CASCADE'
              WHEN 'd' THEN 'SET DEFAULT'
            END AS delete_rule
          FROM
            pg_catalog.pg_constraint con
            JOIN pg_catalog.pg_class rel ON rel.oid = con.conrelid
            JOIN pg_catalog.pg_namespace nsp ON nsp.oid = con.connamespace
            LEFT JOIN pg_catalog.pg_attribute att ON att.attnum = ANY (con.conkey)
              AND att.attrelid = con.conrelid
            LEFT JOIN pg_catalog.pg_class frel ON frel.oid = con.confrelid
            LEFT JOIN pg_catalog.pg_namespace fnsp ON fnsp.oid = frel.relnamespace
            LEFT JOIN pg_catalog.pgattribute fatt ON fatt.attnum = ANY (con.confkey)
              AND fatt.attrelid = con.confrelid
          WHERE
            nsp.nspname NOT LIKE 'pg%'
            AND nsp.nspname != 'information_schema'
            AND con.contype IN ('p', 'f', 'u');
```

Cause changing it to this fixes studio:

```sql
SELECT
    CAST(con.contype AS VARCHAR) AS constraint_type,
    CAST(nsp.nspname AS VARCHAR) AS constraint_schema,
    CAST(con.conname AS VARCHAR) AS constraint_name,
    CAST(rel.relname AS VARCHAR) AS table_name,
    CAST(att.attname AS VARCHAR) AS column_name,
    CAST(fnsp.nspname AS VARCHAR) AS foreign_table_schema,
    CAST(frel.relname AS VARCHAR) AS foreign_table_name,
    CAST(fatt.attname AS VARCHAR) AS foreign_column_name,
    CAST(CASE con.confupdtype
      WHEN 'a' THEN 'NO ACTION'
      WHEN 'r' THEN 'RESTRICT'
      WHEN 'n' THEN 'SET NULL'
      WHEN 'c' THEN 'CASCADE'
      WHEN 'd' THEN 'SET DEFAULT'
    END AS VARCHAR) AS update_rule,
    CAST(CASE con.confdeltype
      WHEN 'a' THEN 'NO ACTION'
      WHEN 'r' THEN 'RESTRICT'
      WHEN 'n' THEN 'SET NULL'
      WHEN 'c' THEN 'CASCADE'
      WHEN 'd' THEN 'SET DEFAULT'
    END AS VARCHAR) AS delete_rule
  FROM
    pg_catalog.pg_constraint con
    JOIN pg_catalog.pg_class rel ON rel.oid = con.conrelid
    JOIN pg_catalog.pg_namespace nsp ON nsp.oid = con.connamespace
    LEFT JOIN pg_catalog.pg_attribute att ON att.attnum = ANY (con.conkey)
      AND att.attrelid = con.conrelid
    LEFT JOIN pg_catalog.pg_class frel ON frel.oid = con.confrelid
    LEFT JOIN pg_catalog.pg_namespace fnsp ON fnsp.oid = frel.relnamespace
    LEFT JOIN pg_catalog.pg_attribute fatt ON fatt.attnum = ANY (con.confkey)
      AND fatt.attrelid = con.confrelid
  WHERE
    nsp.nspname NOT LIKE 'pg_%'
    AND nsp.nspname != 'information_schema'
    AND con.contype IN ('p', 'f', 'u');
```

**Comment by eshrager** [comment]
same issue

**Comment by pouryaof** [comment]
+1

**Comment by nachoonward** [comment]
+1

**Comment by fs2-tensixty** [comment]
+1

**Comment by KyloJorgensen** [comment]
+1

**Comment by larryonward** [comment]
plugged this line in `node_modules/drizzle-kit/bin.cjs` while we're waiting for resolution
```
          const proxy = async (params) => {
            params.sql = params.sql.replace('con.contype AS constraint_type', 'cast(con.contype AS VARCHAR) AS constraint_type');
```

**Comment by eshrager** [comment]
where does this go in the bin.cjs file?

**Comment by KyloJorgensen** [comment]
I did a find and replace on all 7 places where

```
const proxy = async (params) => {
```

and it started working for me

**Comment by eshrager** [comment]
not working for me, i must be doing something wrong.

**Comment by LukasMurdock** [comment]
Hot fix as described above for macOS sed, with a find and replace in `node_modules/drizzle-kit/bin.cjs`

```sh
sed -i '' 's/const proxy = async (params) => {/const proxy = async (params) => {\n  params.sql = params.sql.replace('\''con.contype AS constraint_type'\'', '\''cast(con.contype AS VARCHAR) AS constraint_type'\'');/g' node_modules/drizzle-kit/bin.cjs
```

**Comment by eshrager** [comment]
worked. huge thanks!

**Comment by tclain-pillar** [comment]
Broken for us too #547

**Comment by adamszeptycki** [comment]
Same here

**Comment by RomanNabukhotnyi** [comment]
Hey everyone! This should be fixed, try it.

**Comment by magicspon** [comment]
This seems to be fixed now.

**Comment by eshrager** [comment]
i think this bug has resurfaced. i updated to the latest drizzle orm and drizzle kit and i'm having this problem again when i try to load studio...UnsupportedResultException: The result contains the unsupported data type "CHAR".
    at de_UnsupportedResultExceptionRes (/Users/edshrager/Projects/assistant/node_modules/@aws-sdk/client-rds-data/dist-cjs/index.js:1015:21)
    at de_CommandError (/Users/edshrager/Projects/assistant/node_modules/@aws-sdk/client-rds-data/dist-cjs/index.js:820:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/edshrager/Projects/assistant/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /Users/edshrager/Projects/assistant/node_modules/drizzle-kit/bin.cjs:53989:22
    at async /Users/edshrager/Projects/assistant/node_modules/drizzle-kit/bin.cjs:53747:42
    at async /Users/edshrager/Projects/assistant/node_modules/drizzle-kit/bin.cjs:47559:26
    at AwsDataApiPreparedQuery.values (/Users/edshrager/Projects/assistant/node_modules/src/aws-data-api/pg/session.ts:111:18)
    at AwsDataApiPreparedQuery.execute (/Users/edshrager/Projects/assistant/node_modules/src/aws-data-api/pg/session.ts:61:18)
    at async proxy (/Users/edshrager/Projects/assistant/node_modules/drizzle-kit/bin.cjs:65268:28) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'feaf81c8-2856-4970-bf98-7851e83188e0',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}

**Comment by ekaya97** [comment]
+1
