### ISSUE TITLE
Can't open Drizzle studio anymore

### ISSUE THREAD

**Issue by cschoreisz-pillar** [drizzle-team/drizzle-kit-mirror#547]
Since the beginning of this week I haven't been able to use Drizzle studio

package.json
    "drizzle-kit": "^0.22.8",
    "drizzle-orm": "^0.31.4",

**Comment by tclain-pillar** [comment]
+1 

Bug report is attached.

We use rds data API

<img width="931" alt="image" src="https://github.com/user-attachments/assets/819c6290-5cb7-44d2-a848-dce5d0b17294">


[bug-report.zip](https://github.com/user-attachments/files/16630790/bug-report.zip)

**Comment by RomanNabukhotnyi** [comment]
Hey! This should be fixed, try it.
