### ISSUE TITLE
Unexpected error happened 😕

### ISSUE THREAD

**Issue by dev-frog** [drizzle-team/drizzle-kit-mirror#548]
Error: connect ECONNREFUSED ::1:5432
    at ie (https://local.drizzle.studio/index.js:13147:10689)
    at async https://local.drizzle.studio/index.js:13147:10834
    at async Promise.all (index 0)
    at async rni (https://local.drizzle.studio/index.js:12972:1418)
    at async tAl (https://local.drizzle.studio/index.js:13147:10815)
    
    
    {
  "drizzle-playground": {
    "state": {
      "editorHight": 300,
      "currentFile": "sql",
      "drizzleValue": null,
      "sqlValue": null,
      "showRecordsAsJson": false,
      "drizzleResult": "{\"json\":null}",
      "sqlResult": "{\"json\":null}"
    },
    "version": 0
  },
  "drizzle-version": "2.0.1",
  "drizzle-global": {
    "state": {
      "showCounts": true,
      "flatSchemas": false
    },
    "version": 0
  },
  "drizzle-custom-theme-ids": []
}

**Comment by L-Mario564** [comment]
This seems to be an issue with the DB URL or credentials inputted in the Drizzle config file. Please verify that the credentials to connect to the DB are correct.
