### ISSUE TITLE
Raw sql`` function calls get incorrectly changed

### ISSUE THREAD

**Issue by FadhiliNjagi** [drizzle-team/drizzle-kit-mirror#549]
I am using `nanoid` in PostgreSQL. I have included it as an SQL function or stored procedure.

My original `schema.ts`:
```ts
export const user = pgTable('_user', {
  id: char('id', { length: 21 }).default(sql`nanoid(21, '6789BCDFGHJKLMNPQRTWbcdfghjkmnpqrtwz')`).primaryKey().notNull(),
  // ...
})
```

What Drizzle Studio shows in schema tab:
```js
export const user = pgTable("_user", {
  id: char("id", { length: 21 }).default(nanoid(21, '6789BCDFGHJKLMNPQRTWbcdfghjkmnpqrtwz'::text)).primaryKey().notNull(),
  // ...
})
```

Obviously, there I have no `nanoid` function in my TS code. I can't edit the schema tab to make Drizzle kit studio aware of the correct schema so I can test my drizzle queries on Drizzle Runner.

Any help would be appreciated.

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3220.
