### ISSUE TITLE
Cannot read properties of undefined (reading 'insertId')

### ISSUE THREAD

**Issue by fahadsaleem020** [drizzle-team/drizzle-kit-mirror#552]
I'm getting this error "Cannot read properties of undefined (reading 'insertId')" on every update/delete/insert operation.
[bug-report.zip](https://github.com/user-attachments/files/16708863/bug-report.zip)

**Comment by cannap** [comment]
i have the same

**Comment by inducingchaos** [comment]
Any fixes? Also getting the same error with a PlanetScale connection.

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3229.
