### ISSUE TITLE
Error trying to access D1 Database through NuxtHub

### ISSUE THREAD

**Issue by alduboishc** [drizzle-team/drizzle-kit-mirror#557]
[bug-report(1).zip](https://github.com/user-attachments/files/16854964/bug-report.1.zip)

**Comment by onmax** [comment]
Hey do you refer to this error after running `nuxi dev`?


![image](https://github.com/user-attachments/assets/2eea8c98-4316-4507-80b3-feb99823b191)

I have the same issue with [this repo](https://github.com/nimiq/validators-api).

## Steps

1. Download the repo
2. Install dependencies (using pnpm)
3. Run `pnpm db:generate`
4. Run `pnpm dev`
5. Open DevTools > Database

**Comment by alduboishc** [comment]
Hey, in my case, my problem occurs only when accessing the ORM in NuxtHub Admin Panel https://hub.nuxt.com/ :

![image](https://github.com/user-attachments/assets/90f74349-1f1f-4e2b-a2e5-8a75576915b8)

Works fine in dev 
![image](https://github.com/user-attachments/assets/695828e2-5afd-42f7-baa7-52c8b5cd4e99)

**Comment by alduboishc** [comment]
I found a github issue for my case : https://github.com/nuxt-hub/core/issues/183

I'll close this one as this is now resolved on my side.
