### ISSUE TITLE
Migrate fails silently when tables were dropped manually

### ISSUE THREAD

**Issue by scsskid** [drizzle-team/drizzle-kit-mirror#568]
related #341 ?

drizzle-orm: 0.33.0
drizzle-kit: 0.24.2

when dropping tables after previous migrations, new migrations fail silently

<img width="276" alt="image" src="https://github.com/user-attachments/assets/bd1a833b-5288-42c3-98fd-d0e0541d2c86">

but database has no tables

**deleting the migrations folder with meta folder resolves the issue**

**Comment by L-Mario564** [comment]
We'll keep track of this over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3214.
