### ISSUE TITLE
`TypeError: f.map is not a function` running Drizzle Studio using schema with `constructor` column

### ISSUE THREAD

**Issue by seppewyns** [drizzle-team/drizzle-kit-mirror#569]
I'm getting the following error when running Drizzle Studio using a schema that has a table with a column named `constructor`.
The error occurs when the database column itself is named `constructor`.

For example:
- `carConstructor: varchar("constructor")` throws an error
- `constructor: varchar("car_constructor")` does not throw an error

This might be related to the fact that the [`constructor` property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor) of an object typically refers to the constructor function.

Stack trace:
```
TypeError: f.map is not a function
    at https://local.drizzle.studio/index.js:14051:6036
    at Array.forEach (<anonymous>)
    at ori (https://local.drizzle.studio/index.js:14051:5671)
    at https://local.drizzle.studio/index.js:14040:6
    at Array.map (<anonymous>)
    at cri (https://local.drizzle.studio/index.js:14039:39)
    at bri (https://local.drizzle.studio/index.js:14060:306)
    at ykl (https://local.drizzle.studio/index.js:14123:34156)
```

Schema:
```ts
import { pgTable, uuid, varchar } from "drizzle-orm/pg-core";

export const cars = pgTable("cars", {
  id: uuid("id").primaryKey().defaultRandom(),
  carConstructor: varchar("constructor").notNull(),
});
```

Bug report: [bug-report.zip](https://github.com/user-attachments/files/17012174/bug-report.zip)

- drizzle-orm: 0.33.0
- drizzle-kit: 0.24.2
- Node.js: v20.17.0

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3227.
