### ISSUE TITLE
Timestamp Column Migration Issue - (Not generating migration file)

### ISSUE THREAD

**Issue by Jlh77** [drizzle-team/drizzle-kit-mirror#571]
I've come across an issue with Drizzle-Kit recently;

While creating my schema, I accidentally omitted setting the `{ mode: "date"  }` flag on a bunch of my timestamp columns.

So I edited all my timestamp columns  e.g.

```
...
followed_since: timestamp("followed_since", {
    withTimezone: true,
    mode: "date",
  }):
...
```
But then while running `npx drizzle-kit generate` I get 

> No schema changes, nothing to migrate 😴

Now I believe this behaviour may actually be correct, since from my understanding this only affects mapping within drizzle and wouldn't actually need any change in the database (? Not sure on this, if anyone can explain further that would be appreciated) and therefore not need a migration.

However, it means there is no way for me to push this change so I can introspect it for my other repos. (I am running a rather large project using Drizzle with multiple places sharing this schema with no issues so far)

To fix it I had to find all these other schemas and manually change this setting in all the fields for everyone. I am not sure if when I make another change in the future, and introspect that, will it just reset all those columns back to mode: string (since it just pulls down the schema directly)? Or will there be something there to tell it to keep that change, in which case is there a way to push that change and stop this issue altogether?

For reference I am running v0.24.2

**Comment by Jlh77** [comment]
OK after being required to make further changes, I can confirm that when introspecting again it will set the timestamps back to `mode: "string"` which is very irritating as it will happen every time. Is there anyway to fix this?

**Comment by L-Mario564** [comment]
I've made a feature request that aims to solve the issue you're facing. We'll keep track of this here: https://github.com/drizzle-team/drizzle-orm/issues/3239.
