### ISSUE TITLE
Problem viewing related data in Drizzle Studio

### ISSUE THREAD

**Issue by naitikprajapati1** [drizzle-team/drizzle-kit-mirror#573]
I am encountering an issue while accessing related data in Drizzle ORM. Specifically, I have a user keys table that is related to a user table. When I try to view the associated data, I encounter unexpected behavior or errors.

Steps to Reproduce
Set up a database with users and user keys tables, ensuring that user keys have a foreign key referencing users.
In my Drizzle ORM setup, I establish the relationship between the tables.
Attempt to fetch or view the related user data for a specific user.

Expected Behavior
I expect to see the user data associated with the specific user correctly displayed without errors.

Actual Behavior
Instead of seeing the related userkeys data, I either encounter an error or an empty result set.

**Error Message**

Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at eY (https://local.drizzle.studio/index.js:48:18191)
    at Object.ssl [as useMemo] (https://local.drizzle.studio/index.js:48:21923)
    at am.useMemo (https://local.drizzle.studio/index.js:19:6321)
    at bol.useSyncExternalStoreWithSelector (https://local.drizzle.studio/index.js:66:395)
    at fat (https://local.drizzle.studio/index.js:66:1227)
    at i (https://local.drizzle.studio/index.js:66:1538)
    at https://local.drizzle.studio/index.js:286:32621
    at nVl (https://local.drizzle.studio/index.js:402:67070)
    at https://local.drizzle.studio/index.js:499:4170
    at Array.map (<anonymous>)

**Comment by naitikprajapati1** [comment]
Here is Screenshot and Error Context Zip
[bug-report.zip](https://github.com/user-attachments/files/17071312/bug-report.zip)
![image](https://github.com/user-attachments/assets/1091b59a-fea5-4b23-b5d7-4c02f67971c1)

**Comment by melhawnuhra** [comment]
We are getting the same issue.
Our error context: 
[bug-report.zip](https://github.com/user-attachments/files/17072551/bug-report.zip)

![image](https://github.com/user-attachments/assets/899d5ec7-74e2-4520-8db8-eb69b5ce9796)

**Comment by anselanza** [comment]
Just hit this problem as well. Drizzle ORM appears to be working perfectly in my actual application (related entities and all), but when I click on any relations in Drizzle Studio I get the "React" error above.

**Comment by moiguitarrock** [comment]
Happening for me as well just now when click on the relation in Drizzle Studio, weird thing is that it was working just fine few days ago and I haven't made changes in the schemas 🤔

**Comment by naitikprajapati1** [comment]
> Our error context (minus our schema - sorry. Ping me if you need this):

Till now I have not gotten Solutions of it

**Comment by naitikprajapati1** [comment]
> Happening for me as well just now when click on the relation in Drizzle Studio, The weird thing is that it was working just fine a few days ago and I haven't made changes in the schemas 🤔

@moiguitarrock, the same thing happened to me

**Comment by plasherdev** [comment]
same issue happening for me as well

**Comment by naitikprajapati1** [comment]
> Just hit this problem as well. Drizzle ORM appears to be working perfectly in my actual application (related entities and all), but when I click on any relations in Drizzle Studio I get the "React" error above.

Yeah same thing happened to me @anselanza

**Comment by Astatine-213-Tian** [comment]
+1 encountered same issue here

**Comment by BenBab** [comment]
Issue happening for me too. 🤔
"drizzle-orm": "^0.30.10",
"drizzle-kit": "^0.21.2",

Although I also tried updating to the latest ORM and drizzle kit and the same issue occurred 
"drizzle-orm": "0.33.0"
 "drizzle-kit": "^0.24.2",

**Comment by renatorrocha** [comment]
same issue here, when i click on a relation in Drizzle Studio, i get the "Minified React error #310"

versions:
- "drizzle-kit": "^0.24.2"
-    "drizzle-orm": "^0.33.0",

**Comment by pinkth3floyd** [comment]
same with me updated drizzle kit and orm both to latest. Drizzle studio runs fine on my turso website but same database when opened with drizzle kit on local macine gives the error above

**Comment by macklinhrw** [comment]
> same issue here, when i click on a relation in Drizzle Studio, i get the "Minified React error #310"
> 
> versions:
> 
> * "drizzle-kit": "^0.24.2"
> * "drizzle-orm": "^0.33.0",

Same for me

**Comment by nagy135** [comment]
same here, on little older version, as I see it doesnt make sense to update to newer
```json
{
    "drizzle-kit": "^0.21.4",
    "drizzle-orm": "^0.30.10",
}
```

**Comment by sbbu** [comment]
Same issue

**Comment by stevenzhang68** [comment]
same

**Comment by BenBab** [comment]
If any of you are in the Drizzle discord, here is a link to the same issue there. 

https://discord.com/channels/1043890932593987624/1286771370990239815

Just incase the discord is monitored closer than the GitHub issues can we up vote or make some noise there as well which might get some attention as this is a pretty big blocker.

**Comment by PramodTKodag** [comment]
> same here, on little older version, as I see it doesnt make sense to update to newer
> 
> ```json
> {
>     "drizzle-kit": "^0.21.4",
>     "drizzle-orm": "^0.30.10",
> }
> ```
> 
> i m curious what could be the cause. If we all didnt update and randomly it stopped working, does it mean that this isnt a local tool? Does it fetch something external or rely on some server during run? That feels little bit sus not gonna lie and should be explained

That's really sus and make a concern about my data. Is drizzle share data outside ?

**Comment by nagy135** [comment]
> > same here, on little older version, as I see it doesnt make sense to update to newer
> > ```json
> > {
> >     "drizzle-kit": "^0.21.4",
> >     "drizzle-orm": "^0.30.10",
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i m curious what could be the cause. If we all didnt update and randomly it stopped working, does it mean that this isnt a local tool? Does it fetch something external or rely on some server during run? That feels little bit sus not gonna lie and should be explained
> 
> That's really sus and make a concern about my data. Is drizzle share data outside ?

i need to clarify, i didnt investigate and have 0 evidence ...its just that i didnt update anything and it stopped working. Are there other explanations?

**Comment by macklinhrw** [comment]
Drizzle-kit is open-sourced here as far as I know: https://github.com/drizzle-team/drizzle-orm/tree/main/drizzle-kit

**Comment by RomanNabukhotnyi** [comment]
Hi everyone! This should be fixed.

**Comment by anselanza** [comment]
Yeah... this is fixed.. by itself...

Would love to know how/why?

**Comment by AlexBlokh** [comment]
that was a regression in the web app

**Comment by pinkth3floyd** [comment]
> Yeah... this is fixed.. by itself...
> 
> Would love to know how/why?

I would love to know too.... Like why and how actually???
