### ISSUE TITLE
Error: Connection terminated unexpectedly

### ISSUE THREAD

**Issue by izaiasmorais** [drizzle-team/drizzle-kit-mirror#577]
When try to open drizzle-studio

![image](https://github.com/user-attachments/assets/5f26f712-2ff9-4869-bad0-c6f8d6d6e059)

```
"drizzle-kit": "^0.24.2",
"drizzle-orm": "^0.33.0",
```

My **drizzle.config.ts**

```ts
import { defineConfig } from "drizzle-kit";

export default defineConfig({
	schema: "./src/db/schema/*",
	out: "./drizzle",
	dialect: "postgresql",
	dbCredentials: {
		url: "postgresql://docker:docker@localhost:5434/prescriptions",
	},
});

```

**Comment by L-Mario564** [comment]
Update to the latest versions of ORM and Kit and see if the issue persists. If it does persist, please open an issue over on the [main repo](https://github.com/drizzle-team/drizzle-orm/issues) and provide the error context (click "Download Error Context").
