### ISSUE TITLE
Planetscale driverless defineConfig passes connection paramaters incorrectly

### ISSUE THREAD

**Issue by GentikSolm** [drizzle-team/drizzle-kit-mirror#579]
Current version of drizzle kit breaks with planetscales serverless driver. digging through the source code, i found this function
```js
    parseMysqlCredentials = (credentials2) => {
      if ("url" in credentials2) {
        const url = credentials2.url;
        const connectionUrl = new URL(url);
        const pathname = connectionUrl.pathname;
        const database = pathname.split("/")[pathname.split("/").length - 1];
        if (!database) {
          console.error(
            "You should specify a database name in connection string (mysql://USER:PASSWORD@HOST:PORT/DATABASE)"
          );
          process.exit(1);
        }
        return { database, url };
      } else {
        return {
          database: credentials2.database,
          credentials: credentials2
        };
      }
    };
```
if not passed a url, it returns `database` and `credentials`. Next in the code trail we find
```js
      const result = parseMysqlCredentials(it);
      ...
      ...
      if (await checkPackage("@planetscale/database")) {
        const { connect } = await import("@planetscale/database");
        const { drizzle } = await import("drizzle-orm/planetscale-serverless");
        const { migrate: migrate2 } = await import("drizzle-orm/planetscale-serverless/migrator");
        const connection = connect(result);
        const db = drizzle(connection);
```
which directly passes `result` to pscales `connect`. This connect inits function has the following deffinition
```ts
    constructor(config) {
        this.config = config;
        this.fetch = config.fetch || fetch;
        this.session = null;
        if (config.url) {
            const url = new URL(config.url);
            this.config.username = url.username;
            this.config.password = url.password;
            this.config.host = url.hostname;
            this.url = buildURL(url);
        }
        else {
            this.url = new URL(`https://${this.config.host}`).toString();
        }
    }
```
Note that the connect constructor expects a `host` field, but we are passing
```
{
  database: "dbname",
  credentials: {
     host: ...,
     user: ...,
     pass: ...,
  }
}
```
Here, host is nested under credentials causing it to be undefined, and furthermore pscale expects `username` and `password`  not `user` and `pass`. Id be more than happy to make a pr, but unfortunatly it still seems drizzle kit is closed source for some bizzare reason. If this could be a priority since it is a direct bug in the code causing planetscales serverless connection to be completely broken.

Drizzle kit version: `0.24.2`
Planetscale driver: `1.19.0`

**Comment by GentikSolm** [comment]
In the mean time, you can use the following drizzle.config.ts to get around this issue.
import { defineConfig } from "drizzle-kit";

import { env } from "@/env.mjs";

const url = new URL(`https://${env.DATABASE_HOST}/${env.DATABASE_NAME}`);
url.password = env.DATABASE_PASSWORD;
url.username = env.DATABASE_USERNAME;
url.searchParams.set("rejectUnathorized", "true");

console.log("URL: ", url.toString());

export default defineConfig({
  verbose: true,
  dialect: "mysql",
  out: "./out",
  schema: "./src/schema/schema.ts",
  dbCredentials: {
    url: url.toString(),
  },
});

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3236.
