### ISSUE TITLE
filtering by value of joined related model (many to one)

### ISSUE THREAD

**Issue by nagy135** [drizzle-team/drizzle-kit-mirror#582]
I am trying to achieve this filtering based on related table, as is in the documentation
<img width="756" alt="image" src="https://github.com/user-attachments/assets/4d736b2f-fa89-4d09-888e-9ba740b09deb">
https://orm.drizzle.team/docs/rqb#select-filters

<img width="726" alt="image" src="https://github.com/user-attachments/assets/600e56f6-e9ed-4d88-a962-723e054aa5de">

It works from the other side, as is in the documentation, but i cant get "many" where "one" follows certain condition. Am i not getting something obvious here or why is this the case?
I am forced to get all ids and filter by "inArray" here, which is suboptimal i think.

In my example multiple "productStorages" can have same "storage", and I only want those that have certain "storage"

**Comment by L-Mario564** [comment]
This will be addressed in RQB v2. Also, this is for Kit issues not ORM ones.
