### ISSUE TITLE
Drizzle Studio can't add records to PG table with generated identity column

### ISSUE THREAD

**Issue by masto** [drizzle-team/drizzle-kit-mirror#583]
If I define my primary key with .generatedAlwaysAsIdentity(), it seems like I can't add any records in Drizzle Studio because it tries to set the value of the column. This results in an error: *cannot insert a non-DEFAULT value into column "id"*

https://github.com/masto/drizzle-studio-bug is a simple demonstration of the problem.

[bug-report.zip](https://github.com/user-attachments/files/17180882/bug-report.zip)

**Comment by masto** [comment]
Probably related, though less impactful: attempting to use the "Drizzle runner" tab to execute an insert in code produces a false code sense error about the missing `id` column. Though ignoring the red squiggle and executing it anyway succeeds in inserting the row.

<img width="1245" alt="Screenshot 2024-09-29 at 3 15 56 PM" src="https://github.com/user-attachments/assets/24381ad8-4d4c-4842-a062-1af7d0ad46dc">

**Comment by cassianodaniel** [comment]
I am getting the exactly same behavior here. Thanks for raising this up, @masto.

**Comment by frederichoule** [comment]
I am having the same problem.

**Comment by Blackwidow-sudo** [comment]
The issue for me is that the push && migrate command dont even push the `generatedAlwaysAsIdentity()` to the DB.
I have the following schema:
```ts
export const users = pgTable('users', {
	id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
	username: varchar('username', { length: 256 }).notNull(),
	email: varchar('email', { length: 256 }).notNull().unique(),
	passwordHash: text('password_hash').notNull()
})
```
when i use `drizzle-kit push`, it generates the following:
```sql
CREATE TABLE IF NOT EXISTS "users" (
        "id" integer PRIMARY KEY NOT NULL,
        "username" varchar(256) NOT NULL,
        "email" varchar(256) NOT NULL,
        "password_hash" text NOT NULL,
        CONSTRAINT "users_email_unique" UNIQUE("email")
);
```

**Comment by L-Mario564** [comment]
We'll continue tracking this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3210.
