### ISSUE TITLE
Drizzle studio doesn't seem to work with PGlite + PGvector

### ISSUE THREAD

**Issue by ap-patel** [drizzle-team/drizzle-kit-mirror#584]
[bug-report.zip](https://github.com/user-attachments/files/17182019/bug-report.zip)

PGlite works fine as i can store and retrieve vectors. 
With drizzle-ORM i can generate and run migrations too.

But when i go to open drizzle studio i get this error. Any help is greatly appreciated 😓 been stuck on this for a few days. I hate not being able to make progress 

![image](https://github.com/user-attachments/assets/1b8b71a5-15ad-4f28-8e37-97fa40569d18)

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3222.
