### ISSUE TITLE
Unexpected error when open fts' config table

### ISSUE THREAD

**Issue by riazus** [drizzle-team/drizzle-kit-mirror#591]
I'm using drizzle studio for manage SQLite database. I've created new virtual table using `fts5` with the following command:
```
CREATE VIRTUAL TABLE table_name USING fts5(name);
```
On the left side, several tables appeared, one of them being `table_name_config`. When I tried to open this table, I received an unexpected error:
```
SQL_INPUT_ERROR: SQL input error: no such column: rowid (at offset 17)
```
[bug-repport.zip](https://github.com/user-attachments/files/17305708/bug-repport.zip)

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3235.
