### ISSUE TITLE
drizzle-kit up tries to use aws-data-api driver with dialect 'postgresql'

### ISSUE THREAD

**Issue by sisou** [drizzle-team/drizzle-kit-mirror#592]
I am upgrading from `drizzle-kit` v0.20.14 to v0.25.0.

The commit (where the issue appears) is here: https://github.com/sisou/bun-drizzle-chain-mirror/commit/2591878e60c10f7490a0e068254f3061e64f416c

When I try to generate a new migration with `bun drizzle-kit generate` it tells me the snapshots are outdated and I need to run `drizzle-kit up`. This is the output:

```bash
> bun drizzle-kit up             
No config path provided, using default 'drizzle.config.ts'
Reading config file '/home/[...]/bun-drizzle-chain-mirror/drizzle.config.ts'
 Error  Please provide required params for AWS Data API driver:
    [x] database: undefined
    [✓] secretArn: 'postgresql'
error: "drizzle-kit" exited with code 1
```

For some reason it wants to use `aws-data-api` driver, but I don't think anything in the config file points to that:

```ts
import type { Config } from "drizzle-kit";

export default {
	dialect: "postgresql",
	schema: "./db/schema.ts",
	dbCredentials: {
		url: process.env.DATABASE_URL!,
	},
	verbose: true,
	strict: true,
} satisfies Config;
```

`DATABASE_URL` is a `postgres://` URL.

**Comment by elijahmuraoka** [comment]
also getting this issue

**Comment by ksonny** [comment]
I got the same issue with latest drizzle-kit (0.23.1).
It seems to only affect `drizzle-kit up`.
I managed to get through the issue by downgrading to drizzle-kit (0.22) and drizzle-orm (0.33) and do the migration of snapshots with those.

**Comment by jaycenhorton** [comment]
The issue seems to come from [here](https://github.com/drizzle-team/drizzle-orm/blob/64b3c85953d35bf37342ba8cb2b48f2ad08ee7a8/drizzle-kit/src/cli/commands/utils.ts#L94).

As a temporary workaround, defining `out` in the config seems to work for me using the latest version (0.26.1).

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3226.
