### ISSUE TITLE
release notes?

### ISSUE THREAD

**Issue by robcresswell** [drizzle-team/drizzle-kit-mirror#593]
The past few releases dont seem to have notes. Are these available anywhere? I know you sometimes you post things to twitter, which isnt much use for those of us who dont use it unfortunately :) Thankyou!

**Comment by L-Mario564** [comment]
Release notes and everything Kit related has moved to the main repo. Kit releases can now be found here: https://github.com/drizzle-team/drizzle-orm/releases.
