### ISSUE TITLE
Inconsistency in SQLite table creation for integer primary key

### ISSUE THREAD

**Issue by KelechiOdom10** [drizzle-team/drizzle-kit-mirror#598]
When using drizzle-kit to generate SQLite migrations, there's an inconsistency in how integer primary keys are created. The generated SQL for my users table produces:

```sql
CREATE TABLE `users` (
`id` integer DEFAULT false NOT NULL,
...
);
```

This causes issues with foreign key constraints, as the id column is not explicitly set as the `PRIMARY KEY` and has an invalid `DEFAULT` value of false.

The expected output should be:
```sql
CREATE TABLE `users` (
`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
...
);
```

This issue affects the integrity of foreign key relationships and can lead to errors like:

`SQLITE_UNKNOWN: SQLite error: foreign key mismatch - "sessions" referencing "users"`

Steps to reproduce:

- Define a schema with an integer primary key column. Here's a simplified version of my schema:

```ts
export const users = sqliteTable("users", {
  id: int("id", { mode: "number" }).primaryKey({ autoIncrement: true }),
  // ... other fields
});

export const sessions = sqliteTable("sessions", {
  id: text("id").primaryKey(),
  userId: int("user_id")
    .notNull()
    .references(() => users.id, {
      onDelete: "cascade",
    }),
  // ... other fields
});
```
- Generate migrations using drizzle-kit
- Observe the generated SQL for the table creation

drizzle-orm version: 0.35.1
drizzle-kit version: 0.26.2
Using the `turso` dialect

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3232.
