### ISSUE TITLE
Drizzle studio not working with neon

### ISSUE THREAD

**Issue by naldiocj** [drizzle-team/drizzle-kit-mirror#602]
> drizzle-kit studio

No config path provided, using default 'drizzle.config.ts'
Reading config file '/home/naldio/dev/instagram-clone/drizzle.config.ts'
Using '@neondatabase/serverless' driver for database querying
 Warning  '@neondatabase/serverless' can only connect to remote Neon/Vercel Postgres/Supabase instances through a websocket

**Comment by L-Mario564** [comment]
I think the warning message explains it pretty clear. While using the `@neondatabase/serverless` driver, it has to be connected to a remote DB (not a local one) via websocket. Read more about the latter here: https://neon.tech/docs/serverless/serverless-driver#use-the-driver-over-websockets.
