### ISSUE TITLE
error when attempting to delete user on data base

### ISSUE THREAD

**Issue by TommyJackson85** [drizzle-team/drizzle-kit-mirror#603]
Was attempted to delete a user in order to try and fix a database issue that was suggesting i had two users with the same email , although i didnt have two users with the same email.

Upon trying to delter I got this reported error and was told to post it here. Any advice me to able to allow me delete users would be great. Thank you. 

`_@https://local.drizzle.studio/index.js:14123:3335`
schema file:
`_@https://local.drizzle.studio/index.js:14123:33353`
drizzle local storage:
`
{
  "drizzle-playground": {
    "state": {
      "currentFile": "sql",
      "drizzleValue": null,
      "sqlValue": null,
      "showRecordsAsJson": false,
      "drizzleResult": "{\"json\":null}",
      "sqlResult": "{\"json\":null}"
    },
    "version": 0
  },
  "drizzle-db-2d48b063452bb97e1f985df609628a85efd15cd9c82869891e6c25efa76917a5": {
    "state": {
      "styleMode": "default",
      "currentPage": "main",
      "filterViews": {},
      "isSidebarOpen": true,
      "isShowSidebarContent": true,
      "filtersVisible": false,
      "sidebarWidth": 268,
      "currentSchema": {
        "name": "public",
        "tables": [],
        "views": []
      },
      "currentTable": {
        "name": "users",
        "columns": [
          {
            "name": "id",
            "type": "number",
            "hasDefault": true,
            "isUnique": false,
            "hasCustomDefault": false,
            "notNull": true,
            "_type": "serial",
            "width": 120,
            "visible": true
          },
          {
            "name": "name",
            "type": "string",
            "hasDefault": false,
            "isUnique": false,
            "hasCustomDefault": false,
            "notNull": false,
            "_type": "varchar",
            "width": 120,
            "visible": true
          },
          {
            "name": "email",
            "type": "string",
            "hasDefault": false,
            "isUnique": true,
            "hasCustomDefault": false,
            "notNull": true,
            "_type": "varchar",
            "width": 120,
            "visible": true
          },
          {
            "name": "password_hash",
            "type": "string",
            "hasDefault": false,
            "isUnique": false,
            "hasCustomDefault": false,
            "notNull": true,
            "_type": "text",
            "width": 195,
            "visible": true
          },
          {
            "name": "role",
            "type": "string",
            "default": "'member'::character varying",
            "hasDefault": true,
            "isUnique": false,
            "hasCustomDefault": false,
            "notNull": true,
            "_type": "varchar",
            "width": 120,
            "visible": true
          },
          {
            "name": "created_at",
            "type": "date",
            "default": "now()",
            "hasDefault": true,
            "isUnique": false,
            "hasCustomDefault": false,
            "notNull": true,
            "_type": "timestamp",
            "width": 250,
            "visible": true
          },
          {
            "name": "updated_at",
            "type": "date",
            "default": "now()",
            "hasDefault": true,
            "isUnique": false,
            "hasCustomDefault": false,
            "notNull": true,
            "_type": "timestamp",
            "width": 250,
            "visible": true
          },
          {
            "name": "deleted_at",
            "type": "date",
            "hasDefault": false,
            "isUnique": false,
            "hasCustomDefault": false,
            "notNull": false,
            "_type": "timestamp",
            "width": 250,
            "visible": true
          }
        ],
        "primaryKeys": [],
        "type": "table",
        "id": "public.users",
        "relations": [
          {
            "name": "invitationsSent",
            "type": "many",
            "table": "users",
            "schema": "public",
            "columns": [
              "id"
            ],
            "refTable": "invitations",
            "refSchema": "public",
            "refColumns": [
              "invited_by"
            ],
            "visible": true
          },
          {
            "name": "activity_logs_user_id",
            "type": "many",
            "schema": "public",
            "table": "users",
            "columns": [
              "id"
            ],
            "refSchema": "public",
            "refTable": "activity_logs",
            "refColumns": [
              "user_id"
            ],
            "visible": true
          },
          {
            "name": "teamMembers",
            "type": "many",
            "table": "users",
            "schema": "public",
            "columns": [
              "id"
            ],
            "refTable": "team_members",
            "refSchema": "public",
            "refColumns": [
              "user_id"
            ],
            "visible": true
          }
        ],
        "filters": [],
        "sort": null,
        "pagination": {
          "limit": 50,
          "offset": 0
        },
        "records": [],
        "createdRecords": [],
        "editedFields": [],
        "schema": "public",
        "historyId": "ucE5_6TPPT4bfURKaThVm",
        "executionTime": 632
      }
    },
    "version": 0
  },
  "drizzle-version": "2.0.1",
  "drizzle-global": {
    "state": {
      "showCounts": true,
      "flatSchemas": false,
      "dataFormats": null
    },
    "version": 0
  },
  "drizzle-custom-theme-ids": []
}
`

introspected database schema:
`
{
  "drizzle": {
    "tables": {
      "__drizzle_migrations": {
        "name": "__drizzle_migrations",
        "type": "table",
        "indexes": {},
        "schema": "drizzle",
        "columns": {
          "id": {
            "name": "id",
            "type": "serial",
            "primaryKey": true,
            "isUnique": false,
            "notNull": true
          },
          "hash": {
            "name": "hash",
            "type": "text",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true
          },
          "created_at": {
            "name": "created_at",
            "type": "bigint",
            "primaryKey": false,
            "isUnique": false,
            "notNull": false
          }
        },
        "foreignKeys": {},
        "compositePrimaryKeys": {},
        "uniqueConstraints": {}
      }
    },
    "views": {},
    "enums": {}
  },
  "public": {
    "tables": {
      "invitations": {
        "name": "invitations",
        "type": "table",
        "indexes": {},
        "schema": "public",
        "columns": {
          "id": {
            "name": "id",
            "type": "serial",
            "primaryKey": true,
            "isUnique": false,
            "notNull": true
          },
          "team_id": {
            "name": "team_id",
            "type": "integer",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true
          },
          "email": {
            "name": "email",
            "type": "varchar(255)",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true
          },
          "role": {
            "name": "role",
            "type": "varchar(50)",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true
          },
          "invited_by": {
            "name": "invited_by",
            "type": "integer",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true
          },
          "invited_at": {
            "name": "invited_at",
            "type": "timestamp",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true,
            "default": "now()"
          },
          "status": {
            "name": "status",
            "type": "varchar(20)",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true,
            "default": "'pending'::character varying"
          }
        },
        "foreignKeys": {
          "invitations_team_id_teams_id_fk": {
            "name": "invitations_team_id_teams_id_fk",
            "schemaFrom": "public",
            "tableFrom": "invitations",
            "columnsFrom": [
              "team_id"
            ],
            "schemaTo": "public",
            "tableTo": "teams",
            "columnsTo": [
              "id"
            ],
            "onUpdate": "no action",
            "onDelete": "no action"
          },
          "invitations_invited_by_users_id_fk": {
            "name": "invitations_invited_by_users_id_fk",
            "schemaFrom": "public",
            "tableFrom": "invitations",
            "columnsFrom": [
              "invited_by"
            ],
            "schemaTo": "public",
            "tableTo": "users",
            "columnsTo": [
              "id"
            ],
            "onUpdate": "no action",
            "onDelete": "no action"
          }
        },
        "compositePrimaryKeys": {},
        "uniqueConstraints": {}
      },
      "activity_logs": {
        "name": "activity_logs",
        "type": "table",
        "indexes": {},
        "schema": "public",
        "columns": {
          "id": {
            "name": "id",
            "type": "serial",
            "primaryKey": true,
            "isUnique": false,
            "notNull": true
          },
          "team_id": {
            "name": "team_id",
            "type": "integer",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true
          },
          "user_id": {
            "name": "user_id",
            "type": "integer",
            "primaryKey": false,
            "isUnique": false,
            "notNull": false
          },
          "action": {
            "name": "action",
            "type": "text",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true
          },
          "timestamp": {
            "name": "timestamp",
            "type": "timestamp",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true,
            "default": "now()"
          },
          "ip_address": {
            "name": "ip_address",
            "type": "varchar(45)",
            "primaryKey": false,
            "isUnique": false,
            "notNull": false
          }
        },
        "foreignKeys": {
          "activity_logs_team_id_teams_id_fk": {
            "name": "activity_logs_team_id_teams_id_fk",
            "schemaFrom": "public",
            "tableFrom": "activity_logs",
            "columnsFrom": [
              "team_id"
            ],
            "schemaTo": "public",
            "tableTo": "teams",
            "columnsTo": [
              "id"
            ],
            "onUpdate": "no action",
            "onDelete": "no action"
          },
          "activity_logs_user_id_users_id_fk": {
            "name": "activity_logs_user_id_users_id_fk",
            "schemaFrom": "public",
            "tableFrom": "activity_logs",
            "columnsFrom": [
              "user_id"
            ],
            "schemaTo": "public",
            "tableTo": "users",
            "columnsTo": [
              "id"
            ],
            "onUpdate": "no action",
            "onDelete": "no action"
          }
        },
        "compositePrimaryKeys": {},
        "uniqueConstraints": {}
      },
      "users": {
        "name": "users",
        "type": "table",
        "indexes": {},
        "schema": "public",
        "columns": {
          "id": {
            "name": "id",
            "type": "serial",
            "primaryKey": true,
            "isUnique": false,
            "notNull": true
          },
          "name": {
            "name": "name",
            "type": "varchar(100)",
            "primaryKey": false,
            "isUnique": false,
            "notNull": false
          },
          "email": {
            "name": "email",
            "type": "varchar(255)",
            "primaryKey": false,
            "isUnique": true,
            "notNull": true
          },
          "password_hash": {
            "name": "password_hash",
            "type": "text",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true
          },
          "role": {
            "name": "role",
            "type": "varchar(20)",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true,
            "default": "'member'::character varying"
          },
          "created_at": {
            "name": "created_at",
            "type": "timestamp",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true,
            "default": "now()"
          },
          "updated_at": {
            "name": "updated_at",
            "type": "timestamp",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true,
            "default": "now()"
          },
          "deleted_at": {
            "name": "deleted_at",
            "type": "timestamp",
            "primaryKey": false,
            "isUnique": false,
            "notNull": false
          }
        },
        "foreignKeys": {},
        "compositePrimaryKeys": {},
        "uniqueConstraints": {
          "users_email_unique": {
            "name": "users_email_unique",
            "columns": [
              "email"
            ]
          }
        }
      },
      "teams": {
        "name": "teams",
        "type": "table",
        "indexes": {},
        "schema": "public",
        "columns": {
          "id": {
            "name": "id",
            "type": "serial",
            "primaryKey": true,
            "isUnique": false,
            "notNull": true
          },
          "name": {
            "name": "name",
            "type": "varchar(100)",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true
          },
          "created_at": {
            "name": "created_at",
            "type": "timestamp",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true,
            "default": "now()"
          },
          "updated_at": {
            "name": "updated_at",
            "type": "timestamp",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true,
            "default": "now()"
          },
          "stripe_customer_id": {
            "name": "stripe_customer_id",
            "type": "text",
            "primaryKey": false,
            "isUnique": true,
            "notNull": false
          },
          "stripe_subscription_id": {
            "name": "stripe_subscription_id",
            "type": "text",
            "primaryKey": false,
            "isUnique": true,
            "notNull": false
          },
          "stripe_product_id": {
            "name": "stripe_product_id",
            "type": "text",
            "primaryKey": false,
            "isUnique": false,
            "notNull": false
          },
          "plan_name": {
            "name": "plan_name",
            "type": "varchar(50)",
            "primaryKey": false,
            "isUnique": false,
            "notNull": false
          },
          "subscription_status": {
            "name": "subscription_status",
            "type": "varchar(20)",
            "primaryKey": false,
            "isUnique": false,
            "notNull": false
          }
        },
        "foreignKeys": {},
        "compositePrimaryKeys": {},
        "uniqueConstraints": {
          "teams_stripe_customer_id_unique": {
            "name": "teams_stripe_customer_id_unique",
            "columns": [
              "stripe_customer_id"
            ]
          },
          "teams_stripe_subscription_id_unique": {
            "name": "teams_stripe_subscription_id_unique",
            "columns": [
              "stripe_subscription_id"
            ]
          }
        }
      },
      "team_members": {
        "name": "team_members",
        "type": "table",
        "indexes": {},
        "schema": "public",
        "columns": {
          "id": {
            "name": "id",
            "type": "serial",
            "primaryKey": true,
            "isUnique": false,
            "notNull": true
          },
          "user_id": {
            "name": "user_id",
            "type": "integer",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true
          },
          "team_id": {
            "name": "team_id",
            "type": "integer",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true
          },
          "role": {
            "name": "role",
            "type": "varchar(50)",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true
          },
          "joined_at": {
            "name": "joined_at",
            "type": "timestamp",
            "primaryKey": false,
            "isUnique": false,
            "notNull": true,
            "default": "now()"
          }
        },
        "foreignKeys": {
          "team_members_user_id_users_id_fk": {
            "name": "team_members_user_id_users_id_fk",
            "schemaFrom": "public",
            "tableFrom": "team_members",
            "columnsFrom": [
              "user_id"
            ],
            "schemaTo": "public",
            "tableTo": "users",
            "columnsTo": [
              "id"
            ],
            "onUpdate": "no action",
            "onDelete": "no action"
          },
          "team_members_team_id_teams_id_fk": {
            "name": "team_members_team_id_teams_id_fk",
            "schemaFrom": "public",
            "tableFrom": "team_members",
            "columnsFrom": [
              "team_id"
            ],
            "schemaTo": "public",
            "tableTo": "teams",
            "columnsTo": [
              "id"
            ],
            "onUpdate": "no action",
            "onDelete": "no action"
          }
        },
        "compositePrimaryKeys": {},
        "uniqueConstraints": {}
      }
    },
    "views": {},
    "enums": {}
  }
}
`

introspected drizzle schema:
`
import { pgTable, pgSchema, serial, text, bigint, foreignKey, integer, varchar, timestamp, unique } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"

import { relations } from "drizzle-orm/relations";

export const drizzle = pgSchema("drizzle");

export const __drizzleMigrationsInDrizzle = drizzle.table("__drizzle_migrations", {
    id: serial("id").primaryKey().notNull(),
    hash: text("hash").notNull(),
    createdAt: bigint("created_at", { mode: "number" }),
});

export const invitations = pgTable("invitations", {
    id: serial("id").primaryKey().notNull(),
    teamId: integer("team_id").notNull().references(() => teams.id),
    email: varchar("email", { length: 255 }).notNull(),
    role: varchar("role", { length: 50 }).notNull(),
    invitedBy: integer("invited_by").notNull().references(() => users.id),
    invitedAt: timestamp("invited_at", { mode: 'string' }).defaultNow().notNull(),
    status: varchar("status", { length: 20 }).default(sql`'pending'::character varying`).notNull(),
});

export const activityLogs = pgTable("activity_logs", {
    id: serial("id").primaryKey().notNull(),
    teamId: integer("team_id").notNull().references(() => teams.id),
    userId: integer("user_id").references(() => users.id),
    action: text("action").notNull(),
    timestamp: timestamp("timestamp", { mode: 'string' }).defaultNow().notNull(),
    ipAddress: varchar("ip_address", { length: 45 }),
});

export const users = pgTable("users", {
    id: serial("id").primaryKey().notNull(),
    name: varchar("name", { length: 100 }),
    email: varchar("email", { length: 255 }).notNull(),
    passwordHash: text("password_hash").notNull(),
    role: varchar("role", { length: 20 }).default(sql`'member'::character varying`).notNull(),
    createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
    deletedAt: timestamp("deleted_at", { mode: 'string' }),
},
(table) => {
    return {
        usersEmailUnique: unique("users_email_unique").on(table.email),
    }
});

export const teams = pgTable("teams", {
    id: serial("id").primaryKey().notNull(),
    name: varchar("name", { length: 100 }).notNull(),
    createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
    stripeCustomerId: text("stripe_customer_id"),
    stripeSubscriptionId: text("stripe_subscription_id"),
    stripeProductId: text("stripe_product_id"),
    planName: varchar("plan_name", { length: 50 }),
    subscriptionStatus: varchar("subscription_status", { length: 20 }),
},
(table) => {
    return {
        teamsStripeCustomerIdUnique: unique("teams_stripe_customer_id_unique").on(table.stripeCustomerId),
        teamsStripeSubscriptionIdUnique: unique("teams_stripe_subscription_id_unique").on(table.stripeSubscriptionId),
    }
});

export const teamMembers = pgTable("team_members", {
    id: serial("id").primaryKey().notNull(),
    userId: integer("user_id").notNull().references(() => users.id),
    teamId: integer("team_id").notNull().references(() => teams.id),
    role: varchar("role", { length: 50 }).notNull(),
    joinedAt: timestamp("joined_at", { mode: 'string' }).defaultNow().notNull(),
});export const activityLogsRelations = relations(activityLogs, ({one}) => ({
    team: one(teams, {
        fields: [activityLogs.teamId],
        references: [teams.id]
    }),
    user: one(users, {
        fields: [activityLogs.userId],
        references: [users.id]
    }),
}));

export const teamsRelations = relations(teams, ({many}) => ({
    activityLogs: many(activityLogs),
    invitations: many(invitations),
    teamMembers: many(teamMembers),
}));

export const usersRelations = relations(users, ({many}) => ({
    activityLogs: many(activityLogs),
    invitations: many(invitations),
    teamMembers: many(teamMembers),
}));

export const invitationsRelations = relations(invitations, ({one}) => ({
    team: one(teams, {
        fields: [invitations.teamId],
        references: [teams.id]
    }),
    user: one(users, {
        fields: [invitations.invitedBy],
        references: [users.id]
    }),
}));

export const teamMembersRelations = relations(teamMembers, ({one}) => ({
    user: one(users, {
        fields: [teamMembers.userId],
        references: [users.id]
    }),
    team: one(teams, {
        fields: [teamMembers.teamId],
        references: [teams.id]
    }),
}));

`

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3225.
