### ISSUE TITLE
Drizzle studio does not run for aws data-api under drizzle-kit@0.26.2

### ISSUE THREAD

**Issue by valentinbeggi** [drizzle-team/drizzle-kit-mirror#605]
Hello,

When trying to run the studio, with AWS data-api postgres, i'm getting the following 

Error:

TypeError: Cannot destructure property 'resourceArn' of 'connection' as it is undefined.

I think the bug has been introduced in this commit, https://github.com/drizzle-team/drizzle-orm/commit/6f4fc4c552845a1b61179753e23e980e55d99d38#diff-b89d8d3caa6777e0a8c2194727aa2978387676f9b659726d5f91d5e365dd655fR124

`aws-data-api/pg driver.ts`

Connection param seems to come from the new API of drizzle, maybe it has not been propagated to drizzle.config.ts for the data-api ?

Thanks

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3224.
