### ISSUE TITLE
npx drizzle-kit generate not detecting column name changes

### ISSUE THREAD

**Issue by albin-baby-2002** [drizzle-team/drizzle-kit-mirror#607]
**Current schema in database**

![image](https://github.com/user-attachments/assets/a8e8f4ce-5e3a-4d18-b7a1-cd8765950c9c)

**New Schema Changes**

export const categories = pgTable("categories", {
  categoryId: uuid("id").defaultRandom().primaryKey(),
  categoryInternalId: integer("categoryId")
    .generatedAlwaysAsIdentity({
      startWith: 1000,
      increment: 1,
    })
    .unique(),
  name: varchar({ length: 256 }).notNull().unique(),
  description: varchar({ length: 256 }).notNull(),
  onOffer: boolean("onOffer").default(false).notNull(),
  offerName: varchar({ length: 256 }).notNull(),
  offerDiscount: integer("offerDiscount").default(0).notNull(),
});

**Command I Run and Its Output**

$ npx drizzle-kit generate

No config path provided, using default 'drizzle.config.ts'
Reading config file 'C:\Users\alan_j5\OneDrive\Desktop\lanes\drizzle.config.ts'
2 tables
categories 7 columns 0 indexes 0 fks
users 5 columns 0 indexes 0 fks

No schema changes, nothing to migrate 😴

**Version**

"drizzle-orm": "^0.34.1",
"drizzle-kit": "^0.25.0",

**Comment by jhoan2** [comment]
Have the same problem

**Comment by L-Mario564** [comment]
If you're talking about these two fields:

```ts
categoryId: uuid("id"),
categoryInternalId: integer("categoryId")
```

Then there is nothing to migrate unless you change the alias for these fields:

```ts
categoryId: uuid("categoryId"),
categoryInternalId: integer("categoryInternalId")
```
