### ISSUE TITLE
drizzle-kit push doesn't allow non-destructive force push 

### ISSUE THREAD

**Issue by Thinkscape** [drizzle-team/drizzle-kit-mirror#608]
Sadly a continuation of #132 

[Current options](https://orm.drizzle.team/docs/drizzle-kit-push#extended-list-of-configurations) for `drizzle-kit push`:

| command | description |
| -- | -- |
| verbose | print all SQL statements prior to execution |
| strict | always ask for approval before executing SQL statements |
| force | auto-accept all data-loss statements |

Options when interactive:

```
[✓] Pulling schema from database...
· You're about to add unique_foo unique constraint to the table, which contains 217627 items. If this statement fails, you will receive an error from the database. Do you want to truncate foo?

❯ No, add the constraint without truncating the table
  Yes, truncate the table
```

There is no way to push in CI/CD without truncating, or specify the first option from interactive.
Note: `--force` will only select the second option.

**Comment by nasso** [comment]
i miss the time when CLI tools weren't interactive-first 😕

**Comment by andiskim** [comment]
following, having the same issue

**Comment by L-Mario564** [comment]
We'll track this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3209.
