### ISSUE TITLE
Can't run a help command from pnpx

### ISSUE THREAD

**Issue by cmgriffing** [drizzle-team/drizzle-kit-mirror#609]
Not sure what the fix is yet

![Notification_Center_and_cmgriffing_Chriss-Mac-mini-962343___Volumes_T7_repos_lithium_playgrounds_app](https://github.com/user-attachments/assets/ac9553a7-e46c-4e3a-a0cf-c4c910701702)

**Comment by cmgriffing** [comment]
Trying to run `pnpm add -D drizzle-orm/casing` gave this error:
![Notification_Center](https://github.com/user-attachments/assets/571fd6da-3a63-45fe-af8d-445f0e64bcff)

**Comment by L-Mario564** [comment]
Try running `pnpm exec drizzle-kit --help` instead.
