### ISSUE TITLE
Unexpected error happened 

### ISSUE THREAD

**Issue by synthronAcc** [drizzle-team/drizzle-kit-mirror#612]
[bug-report.zip](https://github.com/user-attachments/files/17577636/bug-report.zip)

**Comment by neslob** [comment]
I did you try in a different browser or incognito window? For me Chrome fails, but incognito and Safari work fine.

**Comment by L-Mario564** [comment]
Can you please provide more information as to how this error occurred in a new issue on the [main repo](https://github.com/drizzle-team/drizzle-orm/issues)? I'm working on moving issues right now.
