### ISSUE TITLE
Renaming view columns

### ISSUE THREAD

**Issue by imhoffd** [drizzle-team/drizzle-kit-mirror#616]
This isn't a bug or anything. Just some friction I noticed with the query builder variant of view declarations, but this probably bleeds into Drizzle ORM as it's also "difficult" to rename columns in a query (if, say, you want to call `toSQL()` on it and inspect the results in an intelligible manor). 

`Column` instances doesn't have `.as()` like `SQL` does, so to rename columns you have to wrap it in ```sql``.as()```, like below. 

```ts
const myView = pgView('my_view').as((qb) =>
  qb
    .select({
      id: myTable.id,
      someCamelCasedColumn: sql`${myTable.someCamelCasedColumn}`.as('some_camel_cased_column'), // <-- easier way?
```

Seems like there's room for the ability to do `myTable.someCamelCasedColumn.as('some_camel_cased_column')`, especially now that column names of queries generated by the query builder are able to be persisted in views.

Thanks! Loving the view stuff.

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/2391.
