### ISSUE TITLE
`introspect:pg` ends with `process.exit(1)`

### ISSUE THREAD

**Issue by Pr0gramWizard** [drizzle-team/drizzle-kit-mirror#63]
Version: 0.18.0
Platform: macOS

Running `drizzle-kit introspect:pg` causes the process to end with an error.
I dug into the source code and found that `introspect:pg` ends with `process.exit(1)`.
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/18315564/f5f17a89-5fe2-4073-a6b5-a78a934a5578)
I assume that this is a bug and not intended.

**Comment by AndriiSherman** [comment]
Agree, thanks a lot! Will fix it 
We will open source it soon so you can also contribute

**Comment by AndriiSherman** [comment]
Fixed in `drizzle-kit@0.18.1`
