### ISSUE TITLE
Postgres - migrating from integer to 'serial' generates incorrect migration

### ISSUE THREAD

**Issue by neiled** [drizzle-team/drizzle-kit-mirror#64]
Steps to reproduce:
- Create schema with table with integer primary key
- Generate migration and run it into database
- Realise you meant to create a serial type instead of integer type so change schema
- Generate migration

Migration will show and ALTER TABLE trying to change the data type to SERIAL. However, that doesn't exist, it's a shortname that can only be used at table creation. Script would have to create a sequence and assign it as the default value of the column instead.

See here for more info:
https://stackoverflow.com/a/54189007

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/2183 over on the main repo.
