### ISSUE TITLE
Use SQL compatible syntax for breakpoints

### ISSUE THREAD

**Issue by machour** [drizzle-team/drizzle-kit-mirror#68]
This is affecting `MySQL` migrations.

Instead of generating 

```mysql
--> statement-breakpoint
```

could this be generated instead ?

```mysql
-- > statement-breakpoint
```

in order to keep the generated migration file SQL compatible? (`mysql db < drizzle/funky_name.sql`)

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3218.
