### ISSUE TITLE
PostgreSQL: generated ALTER TABLE incorrectly adds schema on rename

### ISSUE THREAD

**Issue by RRikor** [drizzle-team/drizzle-kit-mirror#69]
Follow up from https://github.com/drizzle-team/drizzle-kit-mirror/issues/40

A table rename from one migration to the next incorrectly adds the schema name on the renamed table. Although it makes some sense, PostgreSQL does not like it. 

expected:
```sql
ALTER TABLE "foo"."bar" RENAME TO "baz";
```

generated:
```sql
ALTER TABLE "foo"."bar" RENAME TO "foo"."baz";

ERROR:  syntax error at or near "."
LINE 1: ...foo"."bar" RENAME TO "foo"."baz...
```

**Comment by AndriiSherman** [comment]
Fixed in 0.19.0
