### ISSUE TITLE
all indexes have all the columns doubled

### ISSUE THREAD

**Issue by capaj** [drizzle-team/drizzle-kit-mirror#71]
I have introspected my schema and all of my indexes have been generated with duplicated columns.
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/1305378/6bcac659-883c-4fb7-b1c4-098caa98ea99)
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/1305378/795a064e-038d-401a-98d1-491a34e1643f)

this was my output:

```

drizzle-kit: v0.18.1
drizzle-orm: v0.26.3

No config path provided, using default 'drizzle.config.ts'
Reading config file '/home/capaj/work-repos/official/official-graphql2/graphql/drizzle.config.ts'
[✓] 101  tables fetched
[✓] 1891 columns fetched
[✓] 22   enums fetched
[✓] 224  indexes fetched
[✓] 682  foreign keys fetched

[✓] Your SQL migration file ➜ drizzle/0000_blushing_sabra.sql 🚀
[✓] You schema file is ready ➜ drizzle/schema.ts 🚀

````

**Comment by L-Mario564** [comment]
This should no longer be an issue in latest.
