### ISSUE TITLE
`drizzle-kit push:mysql` failing on Planetscale

### ISSUE THREAD

**Issue by skeswa** [drizzle-team/drizzle-kit-mirror#74]
Hey folks,

Thanks for the awesome library! Unfortunately, my team is facing an issue with `drizzle-kit push:mysql`.
```
> chortle@0.1.0 db:migration:push
> npx drizzle-kit push:mysql --config=drizzle.config.ts

drizzle-kit: v0.18.1
drizzle-orm: v0.26.1

Reading config file '/Users/redacted/repos/redacted/chortle/drizzle.config.ts'
/Users/redacted/repos/redacted/chortle/node_modules/drizzle-kit/index.js:43643
        const localErr = new Error();
                         ^

Error: target: chortle.-.primary: vttablet: rpc error: code = InvalidArgument desc = missing bind var __vtschemaname (CallerID: czib4smsrxy4yudt19n5)
    at PromiseConnection.execute (/Users/redacted/repos/redacted/chortle/node_modules/drizzle-kit/index.js:43643:26)
    at fromDatabase (/Users/redacted/repos/redacted/chortle/node_modules/drizzle-kit/index.js:21453:32)
    at mysqlPushIntrospect (/Users/redacted/repos/redacted/chortle/node_modules/drizzle-kit/index.js:45601:25)
    at Command2.<anonymous> (/Users/redacted/repos/redacted/chortle/node_modules/drizzle-kit/index.js:51269:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ER_UNKNOWN_ERROR',
  errno: 1105,
  sql: 'select * from information_schema.columns\n' +
    "\twhere table_schema = '' and table_name != '__drizzle_migrations'\n" +
    '\torder by table_name, ordinal_position;',
  sqlState: 'HY000',
  sqlMessage: 'target: chortle.-.primary: vttablet: rpc error: code = InvalidArgument desc = missing bind var __vtschemaname (CallerID: redacted)'
}
```

The repo itself is quite new and has very little in it, you can checkout the state that churned out this error here: https://github.com/khanyakeswa/chortle/tree/64fc3c15b429c0af91beeff2e4d1c5c2a439a713

I ended up climbing in and debugging this a bit, and it looks like the issue is here:
```
    const columns = await db.execute(`select * from information_schema.columns
	where table_schema = '${inputSchema}' and table_name != '__drizzle_migrations'
	order by table_name, ordinal_position;`);
```

Planetscale MySQL is fine with the `table_schema` column, but it seems to have no idea what I'm talking about with `table_name`. Take a look at this (fooling around in the mysql CLI):

```
chortle/dev> select (table_schema) from information_schema.columns limit 1;
+--------------+
| TABLE_SCHEMA |
+--------------+
| mysql        |
+--------------+
chortle/dev> select (table_schema, table_name) from information_schema.columns limit 1;
ERROR 1241 (21000): target: chortle.-.primary: vttablet: rpc error: code = FailedPrecondition desc = Operand should contain 1 column(s) (errno 1241) (sqlstate 21000) (CallerID: planetscale-admin): Sql: "select (table_schema, table_name) from information_schema.`columns` limit :vtg1", BindVars: {REDACTED}
```

Any hunches on why `push:mysql` might be failing? It wouldn't surprise me if I configured something wrong, lol.

**Comment by skeswa** [comment]
I did some digging and this seems to be specific to PlanetScale in my particular case. I filed a [discussion item](https://github.com/planetscale/discussion/discussions/478) with them.

As such, I'm gonna close his I think.

**Comment by skeswa** [comment]
I decided to re-open this after finding out that this drizzle-kit query is broken on Planetscale in particular.

I would love it if we could patch `drizzle-kit` to issue a different query that doesn't break on Planetscale. I would also be happy to work on this, but I have struggled so far to find drizzle-kits source code.

**Comment by AndriiSherman** [comment]
@skeswa I guess you just didn't provide a database in the connectionString you are using for the push command. I'll add a warning for his case in the next release. Working on it

**Comment by AndriiSherman** [comment]
I've added a check so the database should be always present in a connection. Should work in 0.19.0
