### ISSUE TITLE
column xxx cannot be cast automatically to type timestamp without time zone

### ISSUE THREAD

**Issue by warflash** [drizzle-team/drizzle-kit-mirror#75]
I recon this happens quite often but I didn't find a mention of this error in the discord nor the issues here so figured I'd just ask.
When running into a situation like that where kit generates invalid migration code is it safe to manually update the generated migrations? In this case the previous type was a string which pg can't cast to a timestamp.
> ALTER TABLE "yy" ALTER COLUMN "xx" SET DATA TYPE timestamp;

Just want to make sure manual actions don't collide with kit internals in the future ☺

Thank you!

**Comment by L-Mario564** [comment]
You're free to alter the migrations as you see fit. We're going to improve how Kit handles `set data type` for PG eventually, there's issues that track this over on the [main repo](https://github.com/drizzle-team/drizzle-orm/issues).
