### ISSUE TITLE
Invalid input from drizzle config

### ISSUE THREAD

**Issue by rkreddy99** [drizzle-team/drizzle-kit-mirror#76]
I am trying to introspect from postgres db using pg dialect in nodejs

Command : `npx drizzle-kit introspect:pg --config=drizzle.config.ts`

and the drizzle config file contains
```typescript
import type { Config } from "drizzle-kit";
 
export default {
  schema: "./src/schema.ts",
  out: "./drizzle",
  connectionString: process.env.DATABASE_URL
} satisfies Config;
```

When I run the introspect command I am getting the log
```
drizzle-kit: v0.18.1
drizzle-orm: v0.26.3

Reading config file '<dir>\drizzle.config.ts'
Invalid input
```

**Comment by vzotov-trawa** [comment]
@rkreddy99 There is a messy zod validator output. You can display the full message. Go to
`your-package/node_modules/drizzle-kit/index.js`. find line 51405 and paste this
```ts
    console.log(res, drizzleConfig)
```
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/127960008/3ee4ad3f-bf45-4d2f-bef8-f9330ea88ffa)

**Comment by rgripper** [comment]
@rkreddy99 There is a messy zod validator output in the kit. You can display the full error message. Go to
`your-package/node_modules/drizzle-kit/index.js`. find line 51405 and paste this
```ts
    console.log(res, drizzleConfig)
```
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/127960008/3ee4ad3f-bf45-4d2f-bef8-f9330ea88ffa)
