### ISSUE TITLE
when unknown type is detected, would be nice to emit a TODO comment instead of undefined

### ISSUE THREAD

**Issue by capaj** [drizzle-team/drizzle-kit-mirror#8]
currently for unknown types the "undefined" is emitted. 
![image](https://user-images.githubusercontent.com/1305378/216302181-4c424e9a-2735-4b6b-b21c-0d29547e449f.png)

Would be much nicer to do something like:
![image](https://user-images.githubusercontent.com/1305378/216302555-e52f15f5-7bcb-430a-bd50-9a02d92e37c7.png)

**Comment by AndriiSherman** [comment]
Fixed in [0.17.0](https://github.com/drizzle-team/drizzle-kit-mirror/releases/tag/v0.17.0)
