### ISSUE TITLE
Allow absolute path to migration output directory

### ISSUE THREAD

**Issue by namdien177** [drizzle-team/drizzle-kit-mirror#81]
I'm working on a project containing many custom CLI tooling to trigger different CLI commands from different libraries. To have the most reliable file path to execute, we will normally use absolute paths for all configs.

With that said, Drizzle-ORM Kit is currently auto-adding a relative prefix path (`./`) to the config path without checking whether it is absolute or not when using `drizzle-kit generate:mysql` command. We can have a workaround to modify our custom CLI to handle this library specifically but it would be best to have the kit to handle it automatically.

Another reason is, the same absolute path in the migrate function (provided by `drizzle-orm/<provider>/migrator`) will work perfectly fine. It's better to have this behavior consistent.

The idea can be: checking if the path provided is a valid "absolute" path, or will add the prefix afterward.

Below is the current behavior.

![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/29449869/9c9d1d3a-5be8-4cd2-b0e3-eea70078326c)

**Comment by arily** [comment]
migration (drizzle-kit generate) won't work.

**Comment by fcanela** [comment]
I found this issue after being affected by the same behavior. While it is easy to fix, it is also a bad surprise.

**Comment by L-Mario564** [comment]
We'll track this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3217.
