### ISSUE TITLE
drizzle-kit introspect:pg is not generating relations 

### ISSUE THREAD

**Issue by akarabach** [drizzle-team/drizzle-kit-mirror#83]
Run `drizzle-kit introspect:pg` on existing db. There are a lot of ` one to many` and `many to many` relations. drizzle-kit has generated foreign keys but I don't see any relations created automatically. Is it possible to generate it using the tool or we have to do it manually ?

**Comment by nachaos** [comment]
I'm facing the same issue with `drizzle-kit introspect:mysql`

**Comment by Jonatthu** [comment]
Same here on latest with pg

**Comment by Sejmou** [comment]
IIUC, `drizzle-kit introspect:pg` is not even _supposed to_ generate relations, as they aren't a database concept, but rather a higher level abstraction we can introduce on the application level. See also [this discussion](https://orm.drizzle.team/docs/rqb#foreign-keys) in the docs.

So, I guess you will always have to add them by hand? Would be interested to know, if one could still somehow generate relations automatically too
After all, I suppose we very often would also want to use one-to-one, one-to-many or many-to-many relations that exist on DB level also at the application level 🤔 

Would be nice to hear a maintainer's take on this :)

**Comment by nobleach** [comment]
Foreign key relations absolutely are a database concept. While one _could_ represent those at the app level, that is a lot of manual process. DDL is specifically designed to represent table relations. SO I man be misunderstanding what you're saying.

I did read your attached discussion, so that does seem to explain a little bit. I still maintain that it's very common for an ORM/Migration tool to represent table relations.

I don't know what the right thing to do here though.

**Comment by 0xYao** [comment]
adding support for this will be great

**Comment by draew6** [comment]
This is needed. It would help to migrate from prisma.

**Comment by cloud303-mbrughelli** [comment]
Throwing in my +1 as well.  Would be amazing to have these automatically generated via introspect.

**Comment by Jonatthu** [comment]
Not to be that guy, but prisma supports this scenario when pull or introspection on database 😐

**Comment by hi-reeve** [comment]
+1 need this feature

**Comment by OndrejDrapalik** [comment]
+1 for me on this one

**Comment by pfurini** [comment]
+1 and very surprised not seeing relations generated in the first place

**Comment by JohnAllenTech** [comment]
@AndriiSherman any plans to support this in the future?

**Comment by L-Mario564** [comment]
This has been addressed in newer versions of Kit.
