### ISSUE TITLE
Option to generate migration file without foreign key statements.

### ISSUE THREAD

**Issue by namdien177** [drizzle-team/drizzle-kit-mirror#84]
Currently, the `drizzle-kit generate:<type>` command will always generate foreign key statements if we use `relations`, which will make us have to remove them manually afterward.

The reasons why we should have this option are:
- Some database providers (like PlanetScale) don't allow the table to have foreign keys (for many reasons).
- We don't want FKs, yet still want to use all the features related to relational queries or have a clear relationship described in the schema.

Suggestion options: `--no-foreign-key`, `--no-fk`

**Comment by L-Mario564** [comment]
Foreign keys within the TS schema aren't necessary for RQB to work.
