### ISSUE TITLE
Push:mysql Unrecognized Command

### ISSUE THREAD

**Issue by jlong5795** [drizzle-team/drizzle-kit-mirror#88]
When trying to do an initial push I get the following error:
```bash
npm run db:push

> docdb-next@0.1.0 db:push
> drizzle-kit push:mysql --config ./drizzle.config.ts

'"-S"' is not recognized as an internal or external command,
operable program or batch file.
```

I've tried to clean install drizzle-kit but no change. Including my drizzle.config.ts. Application is NextJS (t3 scaffold) and PlanetScale is the DB.

```js
export default {
    schema: "./src/server/db/schema.ts",
    connectionString: process.env.DATABASE_CONNECTION_STRING as string,
    out: "./src/server/db/generated",
};
```

**Comment by AndriiSherman** [comment]
if you are using 0.19.0 any higher please refer to a new config structure. But we will still improve an error you’ve got. It shouldn’t be the way you have it 

https://github.com/drizzle-team/drizzle-kit-mirror/releases/tag/v0.19.0

https://orm.drizzle.team/kit-docs/config-reference

**Comment by AndriiSherman** [comment]
Also in 0.19.1 Config type was fixed, to provide proper types

**Comment by jlong5795** [comment]
I've updated to the config you linked and it returns the same error about the unrecognized command.

```bash
'"-S"' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by jlong5795** [comment]
Closing:
This appears to be something strange on my local machine that I can't replicate on another machine.

As a note, example docs are out of date on both this config implementation and lack guidance on use of connection string version when using Planetscale. If there is a process to PR doc updates happy to dive in there.

**Comment by AndriiSherman** [comment]
Did you check this part? 
https://orm.drizzle.team/kit-docs/config-reference

would love to get more feedback about what was outdated and what is missing on docs? Seems like everything was updated on release 

also going to add more blog post examples about mysql:push. Currently have only SQLite one: 
https://driz.li/sqlite-push

**Comment by jlong5795** [comment]
That link was helpful. Specifically the (quick start guide) ["https://orm.drizzle.team/kit-docs/quick"] is the out of date component I was referrring to. 

Also, yes, examples for each adapter would be fantastic.

**Comment by AndriiSherman** [comment]
Thanks a lot! Will work on that!

**Comment by ShashankSirmour** [comment]
getting same error " '-S' is not recognized as an internal or external command"  here is my config file i am using windows

```
export default {
  schema: './src/shared/db/schema/*',
  out: './migration',
  driver: 'pg',
  dbCredentials: {
    user: process.env.DATABASE_USERNAME,
    password: process.env.DATABASE_PASSWORD,
    host: process.env.DATABASE_HOST as string,
    port: parseInt(process.env.DATABASE_PORT as string, 10),
    database: process.env.DATABASE_NAME as string,
  },
} satisfies Config;
```

**Comment by AlexBlokh** [comment]
@ShashankSirmour @jlong5795 please update `drizzle-kit@win` and let me know if it works

**Comment by ShashankSirmour** [comment]
@

> @ShashankSirmour @jlong5795 please update `drizzle-kit@win` and let me know if it works

@AlexBlokh thanks updated to drizzle-kit@win and it fixed error
