### ISSUE TITLE
Drizzle-Kit Using Next as client

### ISSUE THREAD

**Issue by jlong5795** [drizzle-team/drizzle-kit-mirror#89]
I'm trying to set up my database and I'm getting validation errors about my environment variables. It seems that when I try to push the db drizzle-kit is using my environment variables as though they were being used in the browser. Since I don't want my db connection string in the bundle I am looking for a work-around that won't expose my credentials in the browser.

**Comment by XMadFoX** [comment]
Drizzle kit is designed to be run standalone (e.g. in npm script) or using migrate function
So I think you have a few options:
- don't prefix env with `NEXT_PUBLIC_` ([docs](https://nextjs.org/docs/app/building-your-application/configuring/environment-variables))
- pass env in terminal inline e.g. `DB_URL=... npm run db:push` or `DB_URL=... npm exec drizzle-kit push:mysql`
- use [dotenv](https://www.npmjs.com/package/dotenv#%EF%B8%8F-usage) package in migration file
