### ISSUE TITLE
[PG] char is undefined during introspection

### ISSUE THREAD

**Issue by AlexandrLi** [drizzle-team/drizzle-kit-mirror#9]
Hello everyone. I'm trying to run introspect for my existing pg database. In resulted schema columns with data-type char marked as undefined.
![image](https://user-images.githubusercontent.com/12869457/218162152-edfe5f43-a8c3-48f4-a1a6-fa016b2a309a.png)

Another observation is that [customer_id, interchange, part_code] declared as composite key, but in schema they are defined as separate primary keys.

**Comment by AndriiSherman** [comment]
Fixed in [0.17.0](https://github.com/drizzle-team/drizzle-kit-mirror/releases/tag/v0.17.0)
