### ISSUE TITLE
drizzle-kit introspect imports AnyMySqlColumn without `type`

### ISSUE THREAD

**Issue by 205g0** [drizzle-team/drizzle-kit-mirror#90]
pretty much the title and tsserver shows these errors:

'AnyMySqlColumn' is declared but its value is never read.ts(6133)
'AnyMySqlColumn' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.ts(1444)

**Comment by L-Mario564** [comment]
This should be fixed in latest. If you still encounter this bug after upgrading, feel free to open a new issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues.
