### ISSUE TITLE
Adding a "Not null" column with default value, still causes data loss.

### ISSUE THREAD

**Issue by MendyLanda** [drizzle-team/drizzle-kit-mirror#91]
Adding this:
<img width="614" alt="image" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/54242706/14682af8-f937-4f05-85a5-8a57f197ba9a">
Causes this:
<img width="795" alt="image" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/54242706/21e93098-5086-494d-b0b2-929b02b33f41">

Although I'm not proficient with the workings of MySQL, I'm aware that in PostgreSQL, such operations are not expected to result in any data loss.

- drizzle-kit: `v0.19.1`
- drizzle-orm: `v0.27.0`
- db: `PlanetScale`

**Comment by MendyLanda** [comment]
Btw, doing it in two stages worked just fine:
1. <img width="482" alt="image" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/54242706/8b5653a6-5bb6-4717-9443-2226695f5e28">

2. <img width="584" alt="image" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/54242706/77c6128b-cf56-4f60-8809-ed2c49d7fedc">

**Comment by AndriiSherman** [comment]
Agree, this is a bug. Will include in the next release

**Comment by MendyLanda** [comment]
@AlexBlokh can I close this?

**Comment by L-Mario564** [comment]
This should be fixed in newer versions of Kit. If anyone experiences this same issue after upgrading, feel free to file a new issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues.
