### ISSUE TITLE
After updating to 0.19.x the drizzle-kit command is not running anymore

### ISSUE THREAD

**Issue by makuko** [drizzle-team/drizzle-kit-mirror#93]
After I updated from v0.18.1 the command is not working anymore. It looks like the problem is coming from the latest version including a loader. When I look at the generated commands in `node_modules/.bin` I find this file:

``` cmd
@ECHO off
GOTO start
:find_dp0
SET dp0=%~dp0
EXIT /b
:start
SETLOCAL
CALL :find_dp0

IF EXIST "%dp0%\-S.exe" (
  SET "_prog=%dp0%\-S.exe"
) ELSE (
  SET "_prog=-S"
  SET PATHEXT=%PATHEXT:;.JS;=;%
)

endLocal & goto #_undefined_# 2>NUL || title %COMSPEC% & "%_prog%" node --loader drizzle-kit/loader.mjs --no-warnings "%dp0%\..\drizzle-kit\index.cjs" %*
```

Notice that the command that will be executed is `-S.exe` which obviously cannot be found. The command should be `node.exe`. After changing it manually I can run drizzle-kit but run into another error in `loader.mjs`:

`TypeError [ERR_INVALID_RETURN_PROPERTY_VALUE]: Expected a URL string to be returned for the "url" from the "drizzle-kit/loader.mjs 'resolve'" function but got instance of String.`

This might be a Windows only issue.

**Comment by AndriiSherman** [comment]
Working on a fix here
https://github.com/drizzle-team/drizzle-orm/issues/781

**Comment by FelixTellmann** [comment]
Same issue here

**Comment by AndriiSherman** [comment]
Explained a fix [here](https://github.com/drizzle-team/drizzle-orm/issues/781#issuecomment-1600679308)

Will be in latest today
