### ISSUE TITLE
Unable to run old versions of drizzle-kit

### ISSUE THREAD

**Issue by iainsproat** [drizzle-team/drizzle-kit-mirror#95]
Since the release of `v0.19.0`, I've been unable to use `v0.18.1` of drizzle-kit. The output of running any command is as follows:

```
drizzle-kit: v0.18.1
drizzle-orm: v0.27.0

This version of drizzle-kit is outdated
Please update drizzle-kit package to the latest version 👍
```

I expect not to be forced to upgrade, a reminder and gentle nudge is fine but blocking all functionality is not ok.

I need repeatability and need to pin the version of the tools used to generate artefacts. I need them to work long after new versions have been released. This is required for audit-ability and for maintenance of legacy branches.

**Comment by AndriiSherman** [comment]
Explained a fix [here](https://github.com/drizzle-team/drizzle-orm/issues/781#issuecomment-1600679308)

Will be in latest today
