### ISSUE TITLE
FeatureRequest | Exclude index.ts file when using schema folder

### ISSUE THREAD

**Issue by ShashankSirmour** [drizzle-team/drizzle-kit-mirror#96]
is there any way to exclude/ ignore files nonrelated to the schema but placed inside the schema?

I created a schema folder and inside that, I created files but to export schema from one file I keep an index.ts file inside schema but when I am using drizzle-kit with this configuration it gives the error ` code: 'ERR_MODULE_NOT_FOUND'`

please add a way to exclude or ignore nonrelated files after using "schema/*" in drizzle.config.ts

**Comment by AndriiSherman** [comment]
What version of drizzle-kit do you have?

**Comment by ShashankSirmour** [comment]
Hi @AndriiSherman  thanks for reply i am using latest one 0.19.1

**Comment by ShashankSirmour** [comment]
thanks @AndriiSherman  in 0.19.2 I am not getting any error closing this
