### ISSUE TITLE
Prisma Studio alternative?

### ISSUE THREAD

**Issue by PhilippMolitor** [drizzle-team/drizzle-kit-mirror#98]
One thing I really dig with Prisma is their integrated Database web interface tool. This way I don't have to download an SQL tool to each of my dev workstations, there is no need to know about which database dialect I am using, and i can instantly click and select relational types.

Are there any plans on adding something like Prisma Studio to drizzle-kit (or a dedicated package)? I think this would round off the developer experience even more.

Thanks for your hard work so far with drizzle-orm and drizzle-kit!

**Comment by AndriiSherman** [comment]
https://orm.drizzle.team/drizzle-studio/overview
