### ISSUE TITLE
Getting Error Executing the Command push:pg

### ISSUE THREAD

**Issue by ShashankSirmour** [drizzle-team/drizzle-kit-mirror#99]
Drizzle-kit: v0.19.2
for the remote database using supabase

Attempting to execute the command `drizzle-kit push:pg`,
but encountering an error:

Error: Unknown command 'push:pg'.
(Did you mean `drizzle-kit up:pg`?)

**Comment by wSedlacek** [comment]
It appears to be coming soon.

![Screenshot 2023-06-22 at 07 35 49](https://github.com/drizzle-team/drizzle-kit-mirror/assets/8206108/e0ff2344-5d58-48e4-a4a9-f09f9ec10db9)

**Comment by ShashankSirmour** [comment]
Thanks @wSedlacek, in doc neon is added as remote db example so got confused

**Comment by briansunter** [comment]
This is confusing because push:pg is in the docs but I don't see it as an option either

https://orm.drizzle.team/kit-docs/commands#prototype--push

**Comment by L-Mario564** [comment]
`push` command is available in newer versions of Kit.
